#!/usr/bin/env bash

. lib.bash || exit

usenfs=0

while getopts :n OPT; do
	case $OPT in
	n) usenfs=1;;
	*) lib::die_getopts;;
	esac
done; shift $((OPTIND-1))

host=${1%%.*}
script=$2

[[ $host ]] || die "missing hostname parameter"

if (( usenfs )); then
	targetdir=/n/$host/Dropbox
else
	targetdir=~/Dropbox
fi

if [[ ! $script ]]; then
	script=$(mktemp /tmp/job.XXXXXXXX.sh)
	cat <<-! > "$script"
	#!/bin/bash
	!
	${EDITOR:-vi} "$script"
	if ! grep -vqs "^#!" "$script"; then
		notice "script is empty, exiting"
		rm -f "$script"
		exit
	fi
elif [[ ! -f $script ]]; then
	die "script file '$script' not found"
elif [[ ! -s $script ]]; then
	notice "script is empty, ignoring"
	exit
fi

dest=$targetdir/$host-$(date +%s).sh
cp "$script" "$dest.tmp"
chmod u+x "$dest.tmp"
mv "$dest.tmp" "$dest"
rm "$script"

log "task $dest submitted"
