#!/usr/bin/env bash

: ${WINEPREFIX:=~/.wine}

case $1 in
	i|install)
		setup_dxvk install --without-dxgi --symlink
		;;
	u|uninstall)
		setup_dxvk uninstall
		;;
esac

cd "$WINEPREFIX/dosdevices"

ls -l --color c:/windows/system32/{d3d{9,10,10_1,10core,11},dxgi}.dll
