#!/usr/bin/env python3
from collections import defaultdict
import os
import sys

roots = sys.argv[1:]

for root in roots:
    seen = defaultdict(set)
    total = 0

    for dirpath, dirnames, filenames in os.walk(root):
        dirpath = os.path.relpath(dirpath, root)
        for item in [*dirnames, *filenames]:
            path = os.path.join(dirpath, item)
            cfpath = path.casefold()
            seen[cfpath].add(path)
            total += 1

    for cfpath in sorted(seen):
        if len(seen[cfpath]) > 1:
            print("Colliding paths:")
            for ogpath in sorted(seen[cfpath]):
                print("  %s" % ogpath)

    print("Scanned %s items with %s unique paths" % (total, len(seen)))
