#!/bin/bash

# The backlight percentages are rounded *down* to the nearest discrete value,
# so on fujitsu we have to increment by 15% in order to reach the next higher
# value, but decrementing by 15% actually results in going two values down.
case $1 in
	+) exec xbacklight -inc 15%;;
	-) exec xbacklight -dec 1%;;
esac
