#!/usr/bin/env python
# unwrap LDIF files
import sys

buf = ""
for line in sys.stdin:
    line = line.rstrip("\r\n")
    if line.startswith(" "):
        buf += line[1:]
    else:
        print(buf)
        buf = line
if buf:
    print(buf)
