#!/usr/bin/env bash
dest=$1
sources=( "${@:2}" )

find "${sources[@]}" -type d -printf '%P\0' |
sort -z -u |
while read -r -d '' dir; do
	mkdir -v -p "$dest/$dir"
done

find "${sources[@]}" -type f -printf '%H\0%P\0' |
while read -r -d '' fsource && read -r -d '' fpath; do
	cp -v -a "$fsource/$fpath" "$dest/$fpath"
done
