#!/usr/bin/env bash
# motd - display /etc/motd only when it is updated

. lib.bash || exit

usage() {
	echo "Usage: $progname [-dq] [-o <cache-path>] [<motd-path>]"
	echo ""
	echo_opt "-d"		"show diff if cached motd exists"
	echo_opt "-o PATH"	"use a different local cache path"
	echo_opt "-q"		"do not display modification time"
	echo_opt "PATH"		"use a different motd path"
	echo ""
	echo "'motd -dq' is suitable for login scripts."
}

mtime() { perl -e 'print ((stat $ARGV[0])[9])' "$1"; }
strftime() { perl -MPOSIX -e 'print strftime $ARGV[0], localtime $ARGV[1]' "$@"; }
strdate() { strftime "%F %H:%M" "$1"; }
when() { strdate "$(mtime "$motd")"; }

copy() { mkdir -p "${2%/*}"; cp "$1" "$2" && touch -r "$1" "$2"; }

# set defaults
motd=/etc/motd
cached=$XDG_CACHE_HOME/motd-$HOSTNAME
diff=false
quiet=false

# parse options
while getopts ":do:q" OPT; do
	case $OPT in
	d) diff=true;;
	o) cached=$OPTARG;;
	q) quiet=true;;
	*) die_getopts;;
	esac
done; shift $((OPTIND-1))

[ "$1" ] && motd=$1

# do the job
if [ ! -f "$cached" ]; then
	# motd added (first run on this host)
	if [ -s "$motd" ]; then
		cat "$motd"
		$quiet || msg "$motd added (last update $(when))"
		copy "$motd" "$cached"
	elif [ -f "$motd" ]; then
		$quiet || msg "$motd is empty (last update $(when))"
		copy "$motd" "$cached"
	else
		$quiet || msg "$motd is missing"
	fi

elif [ ! -f "$motd" ]; then
	# motd removed
	if $diff; then
		diff -uN "$cached" "$motd"
	else
		msg "$motd is gone"
	fi
	rm "$cached"

elif ! cmp -s "$cached" "$motd"; then
	# motd updated
	if $diff; then
		diff -uN "$cached" "$motd"
	else
		cat "$motd"
	fi
	msg "$motd updated (last update $(when))"
	copy "$motd" "$cached"

else
	# no change
	if ! $diff; then
		$quiet || cat "$motd"
	fi
	$quiet || msg "$motd unchanged (last update $(when))"
	copy "$motd" "$cached" # in case local copy is newer
fi
