#!/usr/bin/env perl

my $tree = {};
my $maxdepth = 0;

sub put {
	my $branch = shift;
	my @path = split m|/|, shift;
	while (@path) {
		my $head = shift @path;
		$branch = ($branch->{$head} //= {});
	}
}

sub tree {
	my $branch = shift // $tree;
	my $depth = shift // 0;
	for my $item (sort keys %$branch) {
		print "    "x$depth, $item, "\n";
		if (!$maxdepth || $depth < $maxdepth) {
			tree($branch->{$item}, $depth+1);
		}
	}
}

if ($ARGV[0] =~ /^-(\d+)$/) {
	$maxdepth = $1;
}

while (<STDIN>) {
	chomp; put($tree, $_);
}

tree();
