#!/usr/bin/env bash

. lib.bash || exit

host='mail.nullroute.lt'
user='grawity'
from='grawity@nullroute.lt'

do: swaks \
	--server "$host" \
	--tls-on-connect \
	--tls-verify \
	--auth GSSAPI \
	--auth-user "$user" \
	--auth-password "foo" \
	--from "$from" \
	"$@"
