#!/usr/bin/env python3
# testcidr -- check whether a host is within a network prefix
import argparse
import ipaddress
import os

parser = argparse.ArgumentParser()
parser.add_argument("host")
parser.add_argument("network")
args = parser.parse_args()

host = ipaddress.ip_address(args.host)
net = ipaddress.ip_network(args.network)

#if host.version != net.version:
#    exit("error: mismatching address versions")

if host in net:
    exit(0)
else:
    exit(1)
