#!/usr/bin/env bash

file=~/lib/todo

date_fmt="'%y %b %_d"

date_sep=" – "

_todo_show() {
	nl -ba -s". " -w3 "$file"
}

todo() {
	local arg=$*
	if [[ $arg == /* ]]; then
		if [[ $arg != /*/ ]]; then
			arg+='/'
		fi
		_todo_show | sed -n "${arg}p"
	elif [[ $arg ]]; then
		echo "$(date +"$date_fmt")$date_sep$*" >> "$file"
		_todo_show | tail -n 1
	elif [[ -s ~/lib/todo ]]; then
		_todo_show
	fi
}

vitodo() {
	eval "${EDITOR:-vi} ~/lib/todo"
}

rmtodo() {
	local pcmd dcmd addr
	if (( ! $# )); then
		set -- '$'
	fi
	for addr; do
		if [[ ! $addr ]]; then
			addr='$'
		elif [[ $addr == /* && $addr != /*/ ]]; then
			addr+='/'
		elif [[ $addr == *, ]]; then
			addr+='$'
		fi
		pcmd+="${addr}p;"
		dcmd+="${addr}d;"
	done
	local tmp=${file%/*}/.todo.tmp
	_todo_show | sed -n "$pcmd" &&
	sed "$dcmd" "$file" > "$tmp" &&
	cp "$tmp" "$file" &&
	rm -f "$tmp"
}

if [[ ! -d ${file%/*} ]]; then
	mkdir -p "${file%/*}"
fi

if [[ -f ~/todo ]] && [[ ! -e $file ]]; then
	mv ~/todo "$file"
	ln -s 'lib/todo' ~/todo
fi

cmd=${0##*/}

case $cmd in
    todo|vitodo|rmtodo)
	$cmd "$@";;
    *)
	todo;;
esac
