#!/usr/bin/env bash
# moves files from a given directory to one level above

. lib.bash || exit

shopt -s dotglob

for dir; do
	if [[ ! -d "$dir" ]]; then
		err "item '$dir' is not a directory"
		continue
	fi
	dir=${dir%/}

	for file in "$dir"/*; do
		file=${file#"$dir/"}
		if [[ "$file" == . || "$file" == .. ]]; then
			:
		elif [[ -e "$file" ]]; then
			err "file would conflict: '$file'"
		fi
	done

	(( !errors )) || continue

	find "$dir" -mindepth 1 -maxdepth 1 \
		-not -name "$dir" \
		-print -exec mv -t "$PWD" {} +

	rmdir -v "$dir"
done

lib::exit
