#!/usr/bin/env bash
# moves files from a given directory to one level above

for dir; do
	dir=${dir%/}
	err=

	shopt -s dotglob

	for file in "$dir"/*; do
		file=${file#"$dir/"}
		if [ "$file" = . ] || [ "$file" = .. ]; then
			continue
		elif [ -e "$file" ]; then
			echo "conflict: $file" >&2
			err=1
		fi
	done

	if [ "$err" ]; then
		exit 1
	fi

	find "$dir" -mindepth 1 -maxdepth 1 \
		-not -name "$dir" \
		-print -exec mv -t "$PWD" {} +

	rmdir -v "$dir"
done
