#!/usr/bin/env python3
import requests

ua = requests.Session()

resp = ua.get("https://upgrade.mikrotik.com/routeros/winbox/LATEST.3",
              # One of the web hosts is unreachable.
              timeout=1)
resp.raise_for_status()
version = resp.text.strip()

resp = ua.get(f"https://upgrade.mikrotik.com/routeros/winbox/{version}/CHANGELOG")
resp.raise_for_status()
changelog = resp.text
print(changelog, end="")
