#!/usr/bin/env bash

full=1

if (( full )); then
	for file; do
		hash=$(zipinfo -v "$file" | grep -v '^Archive:' | sha1sum | awk '{print $1}')
		echo "$hash $file"
	done
else
	for file; do
		hash=$(zipinfo -v "$file" | grep "32-bit CRC value" | grep -v 00000000 | sort | sha1sum | awk '{print $1}')
		echo "$hash $file"
	done
fi
