#!/usr/bin/env bash
# display ACLs for parent items (like `namei -l`)

. lib.bash || exit

dir=${1:-$PWD}
args=()

if [[ ! -e "$dir" ]]; then
	die "$dir: not found"
fi

dir=$(readlink -f "$dir")

while [[ $dir ]]; do
	args+=("$dir")
	dir=${dir%/*}
done

if [[ ${args[-1]} != "/" ]]; then
	args+=("/")
fi

exec getfacl -atp "${args[@]}"
