#!/usr/bin/env perl
use feature qw(say state switch);
use Data::Dumper;
use Net::DBus;
use Linux::Inotify2;

my $bus = Net::DBus->session;

my $HOME = $ENV{HOME};
my $Downloads = "$HOME/Downloads";
my $Pictures = "$HOME/Pictures";

sub Notifications {
	$bus
	->get_service("org.freedesktop.Notifications")
	->get_object("/org/freedesktop/Notifications")
}

sub notify {
	state $id = 0;
	my %hints = (
		urgency => Net::DBus::dbus_byte(0),
		transient => Net::DBus::dbus_byte(1),
	);
	$id = Notifications->Notify(
			"inorite",
			$id,
			"icon",
			shift,
			shift,
			[],
			\%hints,
			3000);
}

sub event {
	my $event = shift;
	my $name = $event->name;
	my $oldpath = $event->fullname;
	my $target = file($name);
	if (defined $target) {
		if ($target ~~ m|/$|) {
			$target .= $name;
		}
		say "$name -> $target";
		if (rename($oldpath, $target)) {
			notify($name, "Saved as $target");
		} else {
			warn "$!";
		}
	}
}

sub file {
	my $name = shift;
	given ($name) {
		when (/\.(part|crdownload)$/) {
			undef;
		}
		when (/^201\d-\d+-\d+-SR\d\.\d+/) {
			"$Pictures/Webcomics/Heart Shaped Skull/Comic/";
		}
	}
}

sub loop {
	my $inotify = Linux::Inotify2->new;
	$inotify->watch($Downloads,
		IN_MOVED_TO,
		\&event);
	$inotify->poll while 1;
}

loop;
