#!/usr/bin/env bash

exec acpi_listen | while read line; do
    set -- $line
    case $1 in
        button/power)
            ...
            ;;
        button/sleep)
            ...
            ;;
    esac
done
