#!/usr/bin/env bash
# Does not work. cindex discards some files as non-text.

IndexName=chatlogs

export CSEARCHINDEX="${XDG_CACHE_HOME:-~/.cache}/codesearch/${IndexName}.index"
export TMPDIR="/var/tmp"

if [[ "$1" == "reindex" ]]; then
	cindex ~/Attic/Chatlogs
else
	csearch "$@"
fi
