#!/usr/bin/env bash

begin() {
	declare -g id="$1"
}

this() {
	declare -Ag "$1[$id]=$2"
}

begin 'ssh-agent'
this name 'SSH agent'
if [[ $SSH_AUTH_SOCK ]]; then
	if ssh-add -l >&/dev/null || (( $? == 2 )); then
		this state 'running'
		_nkeys=$(ssh-add -l | wc -l)
		this exstate "$_nkeys keys"
	else
		this state 'broken'
	fi
else
	this state 'inactive'
fi

begin 'kerberos'
this name 'Kerberos'
if klist -5s; then
	this state 'active'
	_nprinc=$(pklist -lP)
	this exstate "$_nprinc principals"
elif [[ $KRB5CCNAME ]]; then
	this state 'broken'
else
	this state 'inactive'
fi

begin 'gpg-agent'
this name 'GPG agent'
if gpg-agent >&/dev/null; then
	this state 'running'
elif [[ $GPG_AGENT_INFO ]]; then
	this state 'broken'
else
	this state 'inactive'
fi

begin 'audit'
this name 'audit session'
_uid=$(</proc/self/loginuid)
_sid=$(</proc/self/sessionid)
if (( _uid == 0xFFFFFFFF || _sid == 0xFFFFFFFF )); then
	this state 'broken'
	this exstate 'not inside a session'
else
	this state 'active'
	this exstate "session $_sid"
fi

declare -p state
