#!/usr/bin/env perl
use Data::Dumper;
use Web::oEmbed;
use feature 'say';

my $cons = Web::oEmbed->new({format => "json"});

$cons->register_provider({
	name => 'Kickstarter',
	url => 'http://*.kickstarter.com/*',
	api => 'http://www.kickstarter.com/services/oembed',
});

for my $url (@ARGV) {
	my $resp = $cons->embed($url, {discovery => 1});
	if ($resp) {
		say "provider: ", $resp->provider_name;
		say "title: ", $resp->title;
		say "html: ", $resp->render;
		say "author name: ", $resp->author_name;
		say "author url: ", $resp->author_url;
	}
}
