#!/usr/bin/env python
import binascii
import socket

def readpacket(sock):
	hdr = sock.recv(4)
	if not hdr:
		return None
	if hdr == b'PACK':
		print("have pack")
		return None
	print("hdr:", hdr)
	length = int(hdr, 16)
	if length == 0:
		return None
	if length == 4:
		return b''
	return sock.recv(length-4)

def writepacket(sock, data):
	length = 4+len(data)
	hdr = ("%04x" % length).encode("us-ascii")
	sock.send(hdr + data)

def writeflushpacket(sock):
	sock.send(b"0000")

caps = ["no-progress"]

a = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
a.connect(("207.97.227.239", 9418))
writepacket(a, b'git-upload-pack /grawity/dotfiles.git\0host=github.com\0')
while True:
	p = readpacket(a)
	if p:
		print(p)
	else:
		break

print("send wants")

writepacket(a, b'want 8779a4b5a72a5748be9caabcd71400a41cb43be2\n')

writepacket(a, b'want 8779a4b5a72a5748be9caabcd71400a41cb43be2\n')
writeflushpacket(a)

print("send haves")

#while True:
#	p = readpacket(a)
#	if p:
#		print(p)
#	else:
#		break

print("done haves")

writepacket(a, b'done\n')
writeflushpacket(a)
p = readpacket(a)
print(p)

pack = open("foo.pack", "wb")
while True:
	p = a.recv(4096)
	if len(p):
		pack.write(p)
	else:
		break

while False:
	p = readpacket(a)
	if p[0] == b'\001':
		print("packfile:", p)
	elif p[0] == b'\002':
		print("progress:", p)
	elif p[0] == b'\003':
		print("error:", p)

