#!/usr/bin/env bash

verbose=0

for addr; do
	{
	name=$(addr2name "$addr")
	if [[ ! "$name" || "$name" == "$addr" ]]; then
		if (( verbose )); then
			name="-"
		else
			continue
		fi
	fi
	echo "$addr $name"
	} &
done | natsort
