#!/usr/bin/env bash

. lib.bash || exit
. libks.bash || exit

hosts=(
	uk-pf-a9
	uk-pf-a73
	uk-pf-m7
	uk-pf-m18
	uk-pf-u2
	uk-pf-wisp
)

for host in "${hosts[@]}"; do
	log2 $host
	ks:sshrun $host "$@"
done
log2 done
