#!/usr/bin/env bash

. lib.bash || exit
. libks.bash || exit

is_git() { git rev-parse --git-dir >&/dev/null; }

is_annex() { git rev-parse refs/heads/git-annex >&/dev/null; }
is_annex!() { is_annex || die "not a git-annex repository"; }

is_remote() { git config --get "remote.$1.annex-uuid" >&/dev/null; }
is_remote!() {
    if ! [[ $1 ]]; then
        die "missing remote name"
    elif ! is_remote "$1"; then
        die "'$1' is not a git-annex remote"
    fi
}

cmd=$1; shift || true

case $cmd in
    setup)
        name=$1
        dir=$PWD/$name
        if [[ ! $name ]]; then
            die "missing name (e.g. Videos)"
        elif [[ -d $dir ]]; then
            die "'$dir' already exists"
        fi
        mkdir "$dir"
        cd "$dir"
        if is_annex; then
            die "'$PWD' is already a git-annex repository"
        elif is_git; then
            die "'$PWD' is already a non-annex Git repository"
        fi
        log "setting up git-annex repository"
        git init
        git annex init
        git annex direct
        log "setting up origin repository"
        rdir="Attic/$name.git"
        if ! ssh virgule "[ -d $rdir ]"; then
            ssh virgule "git init --bare $rdir && cd $rdir && git annex init"
        fi
        log "initial sync"
        git remote add origin "annex:${rdir%.git}"
        git annex sync
        ;;
    link)
        base=$(git config --get nullroute.annex-name \
                || basename "$(git -c core.bare=false rev-parse --show-toplevel)")
        for name; do
            case $name in
                fs1)
                    dir="fs1:/Attic";;
                origin)
                    dir="annex:Attic";;
                vol3)
                    dir="/run/media/grawity/vol3_tombstone/Attic";;
                vol4)
                    dir="/run/media/grawity/vol4_grimoire/Attic";;
                frost|rain)
                    dir="/home/grawity/.$name/Attic";;
                *)
                    err "unknown remote '$name'"; continue;;
            esac
            git remote add "$name" "$dir/$base"
            git annex sync "$name"
        done
        git annex sync
        ;;
    want-get|missing)
        git annex find --want-get --not --in .
        ;;
    want-drop)
        git annex find --want-drop --in .
        ;;
    diff)
        is_annex!
        git annex find --want-get --not --in . | sed $'s/.*/\e[;32mwant\e[m &/'
        git annex find --want-drop --in . | sed $'s/.*/\e[;31mdrop\e[m &/'
        ;;
    examine)
        is_annex!
        if (( ! $# )); then
            exec 2>/dev/null
            set -- uuid.log group.log trust.log preferred-content.log
        fi
        for arg; do
            if [[ $arg != */* && $arg != *.* ]]; then
                arg+=".log"
            fi
            if (( $# > 1 )); then
                echo -e "\e[1m--- $arg ---\e[m"
            fi
            git show "git-annex:$arg"
        done
        ;;
    log-format)
        perl -E '
            use List::MoreUtils qw(uniq);
            while (<>) {
                chomp;
                my ($key, $value, $time) = /^(\S+) (.*) timestamp=([0-9.]+)s$/;
                if (!$items{$key}) {
                    push @items, $key;
                    $items{$key} //= [];
                }
                push @{$items{$key}}, [$time, $value, $_];
            }
            for my $key (@items) {
                my @items = uniq
                            grep {/./}
                            map {$_->[1]}
                            sort {$a->[0] <=> $b->[0]}
                            @{$items{$key}};
                my $last = pop @items;
                say "$key";
                say " - $_" for $last;
                say " \e[38;5;242m- $_\e[m" for reverse @items;
            }
        '
        ;;
    hash)
        for f; do
            n=${f##*/}
            e=$(echo "$n" | perl -ne '
                no locale;
                chomp;
                s/[^a-z0-9.]//g;
                @ext = reverse grep {length($_) <= 4} split(/\./);
                print @ext ? join(".", "", reverse grep {defined} @ext[0..1]) : "";
            ')
            s=$(stat -c %s "$f")
            h=$(sha256sum "$f")
            h=${h%% *}
            echo "SHA256E-s$s--$h$e"
        done
        ;;
    inject)
        for f; do
            h=$(annex hash "$f")
            git annex setkey "$h" "$f"
        done
        ;;
    addurls|registerurls)
        shopt -s nullglob
        if (( ! $# )); then
            set -- **
        fi
        for file; do
            if [[ -d $file ]]; then
                :
            elif [[ -L $file && ! -e $file ]]; then
                :
            elif [[ ! -f $file ]]; then
                warn "item '$file' is not a file" || true
            else
                git annex add "$file"

                if ! annex hasurls "$file"; then
                    url=$(attr -L -q -g xdg.origin.url "$file" 2>/dev/null)
                    if [[ $url == @(http|https|ftp)://* ]]; then
                        debug "adding origin URL '$url' to file '$file'"
                        git annex addurl --file="$file" "$url"
                    elif [[ $url ]]; then
                        warn "ignoring non-web origin '$url' for file '$file'"
                    else
                        warn "no origin URL for file '$file'"
                    fi
                else
                    debug "skipping '$file' (already present in web)"
                fi

                url=$(attr -L -q -g xdg.referrer.url "$file" 2>/dev/null)
                if [[ $url == @(http|https|ftp)://* ]]; then
                    debug "maybe adding referer URL '$url' to file '$file'"
                    git annex metadata --set "referer?=$url" "$file" >/dev/null
                fi
            fi
        done
        ;;
    hasurls)
        r=0
        for file; do
            if key=$(git annex lookupkey "$file"); then
                git annex readpresentkey "$key" "00000000-0000-0000-0000-000000000001"
                (( r += $? ))
            fi
        done
        (( !r ))
        ;;
    commit|ci)
        git annex sync --no-pull --no-push
        ;;
    dupes)
        find "$(git rev-parse --git-dir)/annex/objects" \
            -type f -name "*.map" \
            -exec wc -l {} \; \
            | awk '$1 > 1 {print $2}' \
            | xargs -n 1 cat
        ;;
    push)
        is_remote! "$1"
        log "syncing with '$1' before copy"
        annex sync "$1" --no-push
        log "copying files to '$1'"
        annex copy --fast -J5 --to "$@"
        log "syncing with '$1' after copy"
        annex sync "$1" --no-pull --no-commit
        ;;
    # overrides
    addurl)
        if (( $# == 2 )) && [[ -f $1 || -L $1 ]]; then
            set -- --file="$1" "$2"
        elif (( $# == 1 )); then
            set -- --file="$(urlencode -dS "${1##*/}")" "$1"
        fi
        ;;&
    get)
        set -- -J2 "$@"
        args=()
        for arg in "$@"; do
            if [[ -L ${arg%@} ]]; then
                arg=${arg%@}
            fi
            args+=("$arg")
        done
        set -- "${args[@]}"
        ;;&
    info)
        if (( ! $# )); then
            set -- --fast
        elif [[ $* == @(-v|--slow) ]]; then
            set --
        fi
        ;;&
    *)
        if [[ $cmd ]]; then
            set -- "$cmd" "$@"
        fi
        exec git annex "$@"
        ;;
esac

# vim: ts=4:sw=4:et
