#!/usr/bin/env python3
import fnmatch
import os
import sys
from nullroute.core import *
from nullroute.misc import fmt_size, unquote
from subprocess import Popen, PIPE
import subprocess

def confirm(msg):
    print(msg, end=" ", flush=True)
    try:
        return sys.stdin.readline().lower().startswith("y")
    except KeyboardInterrupt:
        sys.exit(1)

def prompt(msg):
    print(msg, end=" ", flush=True)
    try:
        return sys.stdin.readline().strip()
    except KeyboardInterrupt:
        sys.exit(1)

def annex(*cmd):
    return subprocess.Popen(["git", "annex", *cmd],
                            stdout=subprocess.PIPE)

def annex_run(*cmd):
    return subprocess.call(["git", "annex", *cmd])

def getkeysize(key):
    kk = key.split("--")
    kk = kk[0].split("-")
    for item in kk:
        if item.startswith("s"):
            return int(item[1:])
    raise ValueError("no 'size' field in key %r" % key)

def annex_unused(remote=None):
    if remote and remote != "here":
        args = ["--from=%s" % remote]
    else:
        args = []

    with annex("unused", *args) as proc:
        for line in proc.stdout:
            line = line.decode("utf-8")
            if line.startswith("    "):
                num, key = line.strip().split()
                if num == "NUMBER":
                    continue
                yield int(num), key

def get_last_path(key):
    with subprocess.Popen(["git", "log", "--format=",
                                         "--name-only",
                                         "--no-renames",
                                         "-S%s" % key,
                                         "-n1"],
                          stdout=subprocess.PIPE) as proc:
        for line in proc.stdout:
            line = line.decode("utf-8")
            try:
                line = unquote(line.strip())
            except ValueError:
                print(repr(line))
                raise
            return line

def print_items(items):
    _total = 0
    for num, size, key, name in items:
        print("  %-4d  %8s  %s" % (num, fmt_size(size), name))
        _total += size
    print("= %-4d  %8s  %s" % (len(items), fmt_size(_total), "total"))

remote = None
if len(sys.argv) > 1:
    remote = sys.argv[1]

key_names = {}

Core.info("searching for unused data in %s" % (remote or "local"))
unused = list(annex_unused(remote))
Core.info("listing %d unused files" % len(unused))
n_files = len(unused)
total = 0
items = []
for num, key in unused:
    size = getkeysize(key)
    total += size
    name = get_last_path(key)
    if name:
        name = os.path.basename(name)
        key_names[key] = name
    else:
        name = key
    items.append((num, size, key, name))
items.sort(key=lambda x: x[3].casefold())
dropped = set()
print_items(items)

while n_files:
    r = prompt("Drop %d files (%s) from %s?" % (n_files,
                                                fmt_size(total),
                                                remote or "local")).split(None, 1)
    if not r:
        Core.info("exiting")
        break
    if r[0] in {"y", "yes"}:
        Core.info("dropping all unused files from %s" % (remote or "local repository"))
        if remote:
            annex_run("dropunused", "--from=%s" % remote, "--force", "all")
        else:
            annex_run("dropunused", "--force", "all")
        Core.info("dropped %d files (%s)" % (len(items), fmt_size(total)))
        break
    elif r[0] in {"d", "drop"}:
        Core.info("dropping files matching %r" % r[1])
        nums = []
        sizes = 0
        for num, size, key, name in items:
            if fnmatch.fnmatch(name, r[1]):
                Core.debug("queued %r for drop" % name)
                nums.append(num)
                dropped.add(key)
                sizes += size
        if nums:
            nums = [str(n) for n in nums]
            if remote:
                r = annex_run("dropunused", "--from=%s" % remote, "--force", *nums)
            else:
                r = annex_run("dropunused", "--force", *nums)
            if r == 0:
                Core.info("dropped %d files (%s)" % (len(nums), fmt_size(sizes)))
                n_files -= len(nums)
                total -= sizes
            else:
                Core.err("drop failed")
        else:
            Core.err("no files matched %r" % r[1])
    elif r[0] in {"r", "recover"}:
        Core.info("recovering files matching %r" % r[1])
        names = []
        sizes = 0
        for num, size, key, name in items:
            if fnmatch.fnmatch(name, r[1]):
                Core.debug("creating placeholder for %r" % name)
                subprocess.call(["ln", "-nsf", ".git/annex/objects/%s" % key, name])
                names.append(name)
                dropped.add(key)
                sizes += size
        if names:
            annex_run("add", *names)
            n_files -= len(names)
            total -= sizes
            Core.info("recovered %d files (%s)" % (len(names), fmt_size(sizes)))
        else:
            Core.err("no files matched %r" % r[1])
    elif r[0] in {"/", "print"}:
        _items = [i for i in items if i[2] not in dropped]
        if len(r) > 1:
            _items = [i for i in items if fnmatch.fnmatch(i[3], r[1])]
        print_items(_items)
    elif r:
        Core.err("unknown command %r" % r[0])
    else:
        Core.info("exiting")
        break
