#!/usr/bin/env bash

. lib.bash || exit
. libks.bash || exit

is_git() { git rev-parse --git-dir >&/dev/null; }
is_annex() { git rev-parse refs/heads/git-annex >&/dev/null; }
is_annex!() { is_annex || die "not a git-annex repository"; }

set -e

cmd=$1; shift

case $cmd in
    setup)
        name=$1
        dir=$PWD/$name
        if [[ ! $name ]]; then
            die "missing name (e.g. Videos)"
        elif [[ -d $dir ]]; then
            die "'$dir' already exists"
        fi
        mkdir "$dir"
        cd "$dir"
        if is_annex; then
            die "'$PWD' is already a git-annex repository"
        elif is_git; then
            die "'$PWD' is already a non-annex Git repository"
        fi
        log "setting up git-annex repository"
        git init
        git annex init
        git annex direct
        log "setting up origin repository"
        rdir="Attic/$name.git"
        if ! ssh virgule "[ -d $rdir ]"; then
            ssh virgule "git init --bare $rdir && cd $rdir && git annex init"
        fi
        log "initial sync"
        git remote add origin "annex:${rdir%.git}"
        git annex sync
        ;;
    link)
        base=$(git config --get nullroute.annex-name || basename "$PWD")
        for name; do
            case $name in
                fs1)    dir="fs1:/Attic";;
                origin) dir="annex:Attic";;
                vol3)   dir="/run/media/grawity/vol3_tombstone/Attic";;
                vol4)   dir="/run/media/grawity/vol4_grimoire/Attic";;
                *)      err "unknown remote '$name'"; continue;;
            esac
            git remote add "$name" "$dir/$base"
            annex sync "$name"
            annex info "$name"
        done
        ;;
    want-get|missing)
        exec git annex find --want-get --not --in .
        ;;
    want-drop)
        exec git annex find --want-drop --in .
        ;;
    diff)
        is_annex!
        git annex find --want-get --not --in . | sed $'s/.*/\e[;32mwant\e[m &/'
        git annex find --want-drop --in . | sed $'s/.*/\e[;31mdrop\e[m &/'
        ;;
    examine)
        is_annex!
        if (( ! $# )); then
            exec 2>/dev/null
            set -- uuid.log group.log trust.log preferred-content.log
        fi
        for arg; do
            if [[ $arg != */* && $arg != *.* ]]; then
                arg+=".log"
            fi
            if (( $# > 1 )); then
                echo -e "\e[1m--- $arg ---\e[m"
            fi
            git show "git-annex:$arg"
        done
        ;;
    log-format)
        perl -E '
            use List::MoreUtils qw(uniq);
            while (<>) {
                chomp;
                my ($key, $value, $time) = /^(\S+) (.*) timestamp=([0-9.]+)s$/;
                if (!$items{$key}) {
                    push @items, $key;
                    $items{$key} //= [];
                }
                push @{$items{$key}}, [$time, $value, $_];
            }
            for my $key (@items) {
                my @items = uniq
                            grep {/./}
                            map {$_->[1]}
                            sort {$a->[0] <=> $b->[0]}
                            @{$items{$key}};
                my $last = pop @items;
                say "$key";
                say " - $_" for $last;
                say " \e[38;5;242m- $_\e[m" for reverse @items;
            }
        '
        ;;
    # overrides
    info)
        if (( ! $# )); then
            set -- --fast
        elif [[ $* == @(-v|--slow) ]]; then
            set --
        fi
        ;;&
    # rest
    '')
        exec git annex
        ;;
    *)
        exec git annex "$cmd" "$@"
        ;;
esac

# vim: ts=4:sw=4:et
