#!/usr/bin/env bash
# archlog -- show changelog for an Arch Linux package

. lib.bash || exit

basedir="${XDG_CACHE_HOME:-$HOME/.cache}/asp"
verbose=0

while getopts :v OPT; do
	case $OPT in
	v) verbose=1;;
	*) lib:die_getopts;;
	esac
done; shift $((OPTIND-1))

if (( ! $# )); then
	vdie "package name not specified"
fi

if [[ ! -d $basedir ]]; then
	mkdir -p "$basedir"
fi

for pkg; do
	# Fix up tab-completion
	pkg=${pkg#*/}

	# Look up pkgbase if a binary package is specified
	pkgbase=$(expac -S -1 %e "$pkg" || echo "$pkg")
	if [[ "$pkg" != "$pkgbase" ]]; then
		vmsg "using '$pkgbase' as source package name for '$pkg'"
		pkg=$pkgbase
	fi

	dir="$basedir/$pkg"
	url="https://gitlab.archlinux.org/archlinux/packaging/packages/$pkg.git"

	# Update the repository
	if [[ ! -d $dir ]]; then
		vmsg "cloning '$pkg'"
		git clone --quiet "$url" "$dir"
	else
		vmsg "updating '$pkg'"
		git -C "$dir" pull --quiet --ff-only
	fi || vdie "repository '$pkg' could not be updated"

	# Always hide really verbose PGP-key diffs
	if [[ ! -e $basedir/.gitattributes ]]; then
		cat > "$basedir/.gitattributes" <<-!
		# Symlinked into each repository's .git/info/attributes
		/keys/pgp/*.asc -diff
		!
	fi
	if [[ ! -e $dir/.git/info/attributes ]]; then
		ln -rnsf "$basedir/.gitattributes" "$dir/.git/info/attributes"
	fi

	# Optionally hide redundant .SRCINFO diffs
	paths=()
	if (( !verbose )); then
		paths+=(":!/.SRCINFO")
		paths+=(":!/keys/pgp")
	fi

	settitle "asplog [$pkg]"

	tig -C "$dir" "$ref" -- "${paths[@]}"
done
