#!/usr/bin/env bash
# asn1 -- convenience wrapper for 'dumpasn1', which requires seek() support for
# certain functions

. lib.bash || exit

args=()
temp=()

for arg; do
	debug "input arg '$arg'"

	if [[ $arg == "-" ]]; then
		arg=$(mktemp /tmp/asn1.XXXXXXXX)
		temp+=("$arg")
		cat > "$arg"
		debug "stored '$arg' from stdin"
	fi

	if grep -qs "^-----" "$arg"; then
		raw=$(mktemp /tmp/asn1.XXXXXXXX)
		temp+=("$raw")
		sed -n '/^-----BEGIN .*-----/,/^-----END .*-----/ {
				/^[A-Za-z0-9+/=]*$/p
			}' < "$arg" | base64 -d > "$raw"
		debug "PEM-decoded '$raw' from '$arg'"
		arg=$raw
	fi

	args+=("$arg")
done

do: dumpasn1 "${args[@]}"

if [[ $temp ]]; then
	rm -f "${temp[@]}"
fi
