#!/usr/bin/env bash
# asn1 -- convenience wrapper for 'dumpasn1', which requires seek() support for
# certain functions

. lib.bash || exit

args=()
temp=()
optargs=0

for arg; do
	debug "input arg '$arg'"
	detect=0

	if (( optargs )); then
		debug "- consuming as optarg"
		(( optargs -= 1 ))
	elif [[ $arg == - ]]; then
		debug "- consuming as stdin"
		detect=1
		arg=$(mktemp /tmp/asn1.XXXXXXXX)
		temp+=("$arg")
		cat > "$arg"
	elif [[ $arg == -[cfwm] ]]; then
		debug "- consuming as option with optargs"
		optargs=1
	elif [[ $arg == -* ]]; then
		debug "- consuming as option"
	else
		debug "- consuming as arg"
		detect=1
	fi

	if (( detect )) && [[ -f $arg ]] && [[ -s $arg ]]; then
		debug "arg is a file, detecting contents"
		if grep -qs "^-----" "$arg"; then
			raw=$(mktemp /tmp/asn1.XXXXXXXX)
			temp+=("$raw")
			sed -n '/^-----BEGIN .*-----/,/^-----END .*-----/ {
					/^[A-Za-z0-9+/=]*$/p
				}' < "$arg" | base64 -d > "$raw"
			debug "PEM-decoded '$raw' from '$arg'"
			arg=$raw
		fi
	fi

	args+=("$arg")
done

do: dumpasn1 "${args[@]}"

if [[ $temp ]]; then
	rm -f "${temp[@]}"
fi
