#!/usr/bin/env bash

. lib.bash || exit

ahost=nullroute:pkg/aur

pkgname() {
	local pkgname
	[[ -s PKGBUILD ]] || die "no PKGBUILD here"
	eval "$(grep ^pkgname= PKGBUILD)"
	[[ $pkgname ]] || die "no pkgname in PKGBUILD"
	echo "$pkgname"
}

cmd=$1; shift

case $cmd in
	apush)
		pkgname=$(pkgname) || exit
		log "pushing '$pkgname' to $ahost"
		git push "$ahost" HEAD:$pkgname
		;;
	aclone)
		pkgname=$1
		[[ $pkgname ]] || die "missing pkgname parameter"
		[[ ! -e $pkgname ]] || die "path '$pkgname' already exists"
		log "downloading '$pkgname' from $ahost"
		git init "$pkgname"
		git -C "$pkgname" remote add origin aur:$pkgname
		git -C "$pkgname" fetch "$ahost" $pkgname:origin/master
		git -C "$pkgname" merge origin/master
		;;
	pkgname)
		pkgname
		;;
	*)
		die "unknown command '$cmd'"
		;;
esac
