#!/usr/bin/env perl
use Socket;

sub resolve {
	my $addr = shift;
	my $name = gethostbyaddr(inet_aton($addr), AF_INET);
	print "$addr $name\n" if $name;
}

if (@ARGV) {
	resolve($_) for @ARGV;
} else {
	while (<>) { chomp($_); resolve($_); }
}
