#!/usr/bin/env bash

key=~/.pki/private/auth-grawity.pem

case $1 in
	nullbot)	host=decay.nullroute.eu.org port=+17010;;
	failturing)	host=decay.nullroute.eu.org port=+17020;;
esac

settitle "$1 (at $host:$port)"

case $port in
	+*) exec telnet-ssl -z ssl -z cert="$key" "$host" "${port#+}";;
	*)  exec telnet "$host" "$port";;
esac
