#!/bin/sh

days=30

if [ -t 2 ]; then
	verbose='-print'
else
	verbose=''
fi

find ~/src/_makepkg/ -maxdepth 1 \
	-type f \( -ctime +$days -not -perm +1111 \) \
	$verbose -delete

rm -f ~/src/_makepkg/google-chrome-unstable_current_amd64.deb

find ~/pkg/ -maxdepth 3 -xtype l $verbose -delete
