#!/usr/bin/env bash

. lib.bash || exit

if (( $# )); then
	run=("$@")
	pos=()
	for (( i = 0; i < $#; i++ )); do
		if [[ "${run[i]}" == "{}" ]]; then
			pos+=($i)
		fi
	done
else
	run=
fi

old=""
while sleep 1; do
	new=$(xclip -out -selection clipboard)
	if [[ "$old" != "$new" ]]; then
		if [[ "$run" ]]; then
			for i in "${pos[@]}"; do
				run[i]=$new
			done
			log "$new"
			("${run[@]}")
		else
			echo "$new"
		fi
	fi
	old=$new
done
