#!/bin/sh
type=$1 url=$2

do_rsync() { rsync -avzh "$@"; }

case $type+$url in
	cvs+http://*.sourceforge.net/*)
		project=${url#http://}
		project=${project%%.*}
		repourl="rsync://$project.cvs.sourceforge.net/cvsroot/$project/"
		do_rsync "$repourl" "$project.sfnet/"
		;;
	cvs+http://sourceforge.net/p/*)
		project=${url#http://sourceforge.net/p/}
		project=${project%%/*}
		repourl="rsync://$project.cvs.sourceforge.net/cvsroot/$project/"
		do_rsync "$repourl" "$project.sfnet/"
		;;
esac

# vim: ts=4:sw=4
