#!/usr/bin/env bash

if [[ $1 == -u ]]; then
	shift
	auracle sync "$@"
elif [[ $1 == -i ]]; then
	shift
	auracle info "$@"
elif [[ $1 == -s ]]; then
	shift
	auracle search "$@"
else
	/usr/bin/cower "$@"
fi
