#!/usr/bin/env python
import sys

def split_ranges(string):
    for i in string.split():
        for j in i.split(","):
            if "-" in j:
                x, y = j.split("-", 1)
                if y == "end":
                    yield int(x), 0
                else:
                    yield int(x), int(y)+1
            else:
                yield int(j), int(j)+1

def dd(infh, outfh, max):
    block = 4 * 1024 * 1024
    if max > 0:
        while max > 0:
            if block > max:
                block = max
            print("still need %d bytes, copying block of %d" % (max, block), file=sys.stderr)
            buf = infh.read(block)
            if len(buf) > 0:
                max -= len(buf)
                outfh.write(buf)
            else:
                raise IOError("foo, early EOF")
    else:
        while True:
            buf = infh.read(block)
            if len(buf) > 0:
                outfh.write(buf)
            else:
                return

infile, sranges, outfile = sys.argv[1:]

ranges = split_ranges(sranges)

with open(infile, "rb") as infh:
    with open(outfile, "wb") as outfh:
        for start, end in ranges:
            infh.seek(start)
            if end > 0:
                print("copying %d bytes (%d - %d)" % (end-start, end, start), file=sys.stderr)
                dd(infh, outfh, end-start)
            else:
                dd(infh, outfh, 0)

