#!/usr/bin/env bash

prepare_message() {
	local temp=$(mktemp ~/cpunk.XXXXXXXX)

	{
		echo "::"
		echo "Anon-To: $1"
		echo ""
		echo "##"
		echo "Subject: "
		echo ""
	} > "$temp"

	if [[ -t 0 ]]; then
		vim "$temp" </dev/tty >/dev/tty 2>/dev/tty
	else
		echo "Reading from stdin"
		cat >> "$temp"
	fi

	if (( $(wc -l < "$temp") <= 5 )); then
		rm -f "$temp"
		return 1
	fi

	echo "$temp"
}

encrypt_for() {
	local input=$1
	local temp=$(mktemp ~/cpunk.XXXXXXXX)

	{
		echo "::"
		echo "Encrypted: PGP"
		echo ""
		gpg -a -r "$remailer_addr" -e
	} > "$temp"

	echo "$temp"
}

get_addr() {
	local remailer=$1
	if [[ $remailer == *@* ]]; then
		echo "$remailer"
		return 0
	else
		local _name _addr
		while read _name _addr; do
			if [[ $_name == "$remailer" ]]; then
				echo "$_addr"
				return 0
			fi
		done < ~/remailers
		return 1
	fi
}

recipient=$1; shift

# first hop

remailer=$1; shift
remailer_addr=$(get_addr "$remailer")
if [[ -z $remailer_addr ]]; then
	echo "Address for $remailer unknown"
	exit 1
fi

rawtext=$(prepare_message "$recipient")
layer=$(encrypt_for "$remailer_addr" < "$rawtext")

#mail -s "" "$remailer_addr" < "$layer"
cat "$layer"

rm -f "$rawtext" "$layer"
