#!/usr/bin/env python3
# cputemp -- visually monitor CPU temperature
import argparse
from collections import defaultdict
import enum
from glob import glob
import math
import os
import signal
import sys
import time

class RollingAverage():
    def __init__(self, depth=3):
        assert depth > 0
        self._depth = depth
        self._hist = [0] * depth
        self._roll = 0
        self._count = 0

    def add(self, value):
        if self._count == 0:
            self._hist = [value] * self._depth
            self._roll = value * self._depth
        else:
            self._roll -= self._hist[self._count % self._depth]
            self._hist[self._count % self._depth] = value
            self._roll += value
        self._count += 1

    def get(self):
        return self._roll / self._depth

def fround(val):
    # Round 0.5 up (Python rounds 0.5 down)
    return round(val + 0.1)

def put(s):
    print(s, end="", flush=True)

def set_title(text):
    print("\033]0;%s\033\\" % text, end="", flush=True)

def set_wname(text):
    if os.environ["TERM"].startswith("tmux"):
        print("\033k%s\033\\" % text, end="", flush=True)

def get_loadavg():
    with open("/proc/loadavg", "r") as fh:
        a, b, c, *_ = fh.read().split()
    return float(a), float(b), float(c)

def put_bar(color, width, char):
    bar = ""
    if width <= 0:
        return
    if color:
        bar += "\033[%sm" % color
    if len(char) == 2:
        bar += char[0] * (width-1) + char[1]
    else:
        bar += char[0] * width
    if color:
        bar += "\033[m"
    print(bar, end="")

def clamp(val, low, high):
    return min(max(val, low), high)

def normalize(val, low, high):
    return (val - low) / (high - low)

def mix(a, b, t):
    return a*(1-t) + b*t

def vec_mix(a, b, t):
    assert len(a) == len(b)
    return [mix(a[i], b[i], t) for i in range(len(a))]

def vec_gamma_scale(a, gamma):
    return [x**gamma for x in a]

def linear_gradient(stops, value, gamma=1.0):
    n = 1 / (len(stops) - 1)
    ratio = value / n
    i = math.floor(ratio)
    if i == len(stops) - 1:
        return stops[len(stops) - 1]
    frac = ratio % 1
    stops = [vec_gamma_scale(x, gamma) for x in stops]
    result = vec_mix(stops[i], stops[i+1], frac)
    return vec_gamma_scale(result, 1/gamma)

def ansicolor_for_temp(temp):
    low, high = 25, 65
    stops = [
        (0, 0, 5), # blue
        (0, 5, 0), # green
        (5, 5, 0), # yellow
        (5, 0, 0), # red
    ]

    t = clamp(temp, low, high)
    t = normalize(t, low, high)
    r, g, b = [int(x) for x in linear_gradient(stops, t, gamma=2.2)]

    color = 16 + r*36 + g*6 + b
    return f"38;5;{color}"

def rsuffix(string, old, new):
    if string.endswith(old):
        return string[:-len(old)] + str(new)
    return string

class Sensor:
    def __init__(self, dev, subdev):
        self.dev = dev
        self.subdev = subdev

    def read(self):
        with open(self.subdev, "r") as fh:
            temp = int(fh.read())
            return temp / 1000

    @classmethod
    def find_hwmon_by_name(self, name):
        for dev in glob("/sys/class/hwmon/hwmon*"):
            if os.path.exists("%s/name" % dev):
                with open("%s/name" % dev, "r") as fh:
                    dev_name = fh.read().strip()
                if dev_name == "coretemp":
                    return dev
        raise RuntimeError("no %r hwmon device found" % name)

    @classmethod
    def find_sensor(self):
        dev = self.find_hwmon_by_name("coretemp")

        subdev = None
        subdev_pkg = None
        subdev_cr0 = None
        for path_label in glob("%s/temp*_label" % dev):
            path_input = rsuffix(path_label, "_label", "_input")
            with open(path_label, "r") as fh:
                label = fh.read().strip()
            if label == "Package id 0":
                subdev_pkg = path_input
            elif label == "Core 0":
                subdev_cr0 = path_input
        if subdev_pkg:
            subdev = subdev_pkg
        elif subdev_cr0:
            subdev = subdev_cr0
        else:
            raise RuntimeError("no 'coretemp/Core 0' hwmon sensor found")

        with open("%s/name" % dev, "r") as fh:
            dev_name = fh.read().strip()
        with open(rsuffix(subdev, "_input", "_label"), "r") as fh:
            subdev_name = fh.read().strip()
        print("Using sensor %r (%s:%s)" % (subdev, dev_name, subdev_name), file=sys.stderr)

        return Sensor(dev, subdev)

def print_histogram(data, *, width=5, unit="", barwidth=50):
    def buckets(data, width):
        res = defaultdict(int)
        for k, v in data.items():
            lo = k - (k % width)
            hi = lo + width
            res[lo, hi] += v
        return res

    total = sum(data.values())
    grouped = buckets(data, width)
    for (lo, hi), v in sorted(grouped.items()):
        percentage = 100 * v / total
        width = barwidth * percentage / 100
        label = f"[{lo:-2d}, {hi:-2d})"
        bar = "=" * round(width)
        suffix = f"({v}{unit}, {percentage:.1f}%)"
        print(f"{label:9} | {bar}  {suffix}")

    bar = "-" * barwidth
    print(f"{'':9} +-{bar}")

class MeterBar:
    def __init__(self, interval):
        # Last values for redraw/overdraw
        self.last_ts = 0
        self.last_temp = 0
        self.last_load = 0

        # Statistics
        self.interval = interval
        self.max_temp = 0
        self.time_temps = defaultdict(int)

    def _draw_bar(self, is_current, ts, temp, load):
        global ravg
        color = ansicolor_for_temp(ravg.get())

        width = int(temp) - 20
        put(time.strftime("%T ", time.localtime(ts)))
        if is_current:
            char = "█"
        else:
	        char = "-║"
        put_bar(color, width, char)
        put(f" {temp:3d}°C")
        put(f"  \033[2m{load:.2f}\033[m")
        print(flush=True)

    def overdraw_bar(self):
        put("\033[A") # One line up
        put("\r\033[K") # Reset position after signal
        self._draw_bar(False, self.last_ts, self.last_temp, self.last_load)

    def update(self, ts, temp, load):
        temp = fround(temp)

        self._draw_bar(True, ts, temp, load)
        set_title(f"{hostname}: {temp}°C (load {load:.2f})")
        set_wname(f"{temp}°C")

        # Store values for overdraw
        self.last_ts = ts
        self.last_temp = temp
        self.last_load = load

        # Update stats
        self.max_temp = max(self.max_temp, temp)
        self.time_temps[fround(temp)] += args.interval

    def print_stats(self, from_signal=False):
        if from_signal:
            self.overdraw_bar()

        print()
        print("Statistics:")
        print_histogram(self.time_temps, unit="s")
        for _min in [60, 70, 80, 90]:
            temp_secs = sum([_time
                             for (_temp, _time) in self.time_temps.items()
                             if _temp >= _min])
            if temp_secs:
                print(f"Spent {temp_secs}s at or above {_min}°C")

        max_temp = self.max_temp
        max_temp_secs = self.time_temps[max_temp]
        print(f"Maximum temperature: {max_temp}°C (for {max_temp_secs}s)")

        if from_signal:
            print()
            self._draw_bar(True, self.last_ts, self.last_temp, self.last_load)

parser = argparse.ArgumentParser()
parser.add_argument("-r", "--raw", action="store_true",
                    help="output only temperature value")
parser.add_argument("-n", "--interval", metavar="SECS", type=int, default=1,
                    help="specify update interval")
args = parser.parse_args()

hostname = os.uname().nodename
sensor = Sensor.find_sensor()

if args.raw:
    try:
        while True:
            temp = sensor.read()
            print(f"{temp:.1f}", flush=True)
            time.sleep(args.interval)
    except KeyboardInterrupt:
        exit(0)
else:
    try:
        ravg = RollingAverage(3)
        m = MeterBar(interval=args.interval)
        signal.signal(signal.SIGQUIT, lambda s, f: m.print_stats(True))
        while True:
            if m.last_temp:
                time.sleep(args.interval)
                m.overdraw_bar()
            ts = time.time()
            temp = sensor.read()
            temp = fround(temp)
            ravg.add(temp)
            load = get_loadavg()[0]
            m.update(ts, temp, load)
    except RuntimeError as e:
        exit(f"error: {e}")
    except KeyboardInterrupt:
        m.print_stats()
        exit(0)
