#!/bin/sh
# wrapper for cronjobs, to set basic environment

test "$XDG_RUNTIME_DIR"	|| export XDG_RUNTIME_DIR="/run/user/1000"
test "$SSH_AUTH_SOCK"	|| export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent"

. ~/lib/dotfiles/environ || exit

if [ "$1" = "-c" ]; then
	set -- sh "$@"
fi

nice chronic "$@"
