#!/usr/bin/env bash
# vim: ts=4:sw=4:et

. lib.bash || exit

cmd=$1; shift

case $cmd in
    pkcs7-sign)
        sign_file=$1
        signer_cert=$2
        signer_key=$3

        openssl smime \
            -sign \
            -in "$sign_file" \
            -outform DER \
            -signer "$signer_cert" \
            -inkey "$signer_key" \
            -nocerts \
            ;
        ;;
esac
