#!/usr/bin/env bash
# darkmode -- Toggle between light/dark mode in GNOME

schema=org.gnome.desktop.interface
key=color-scheme
value="'prefer-dark'"

bdev=/sys/class/backlight/intel_backlight/brightness

case $(gsettings get $schema $key) in
	"$value")
		sudo sh -c "echo 3043 > $bdev" &
		gsettings reset $schema $key
		text=disabled;;
	*)
		sudo sh -c "echo 743 > $bdev" &
		gsettings set $schema $key "$value"
		text=enabled;;
esac

if [ -t 1 ]; then
	echo "Dark Mode has been $text."
else
	notifysend -r hotkey -e -i "dark-mode-symbolic" \
		"Dark Mode" "Dark Mode has been $text."
fi
