#!/usr/bin/env python3
# dhcpsearch - Generate DHCP option 119 (domain search list)
import argparse
from nullroute.io import DnsPacketWriter

parser = argparse.ArgumentParser()
parser.add_argument("domain", nargs="+",
                    help="domain suffix")
args = parser.parse_args()

print("Domains:")
pkt = DnsPacketWriter()
for domain in args.domain:
    print(f"\t{domain}")
    pkt.write_domain(domain)

buf = pkt.fh.getvalue()
hex = buf.hex()

print()
print(f"Option code: 119")
print(f"Option data: {buf!r}")
print()
print(f"Mikrotik RouterOS:")
print(f"/ip dhcp-server option")
print(f"add name=domain-search code=119 value=0x{hex.upper()}")
