#!/usr/bin/env bash

h=${XDG_CACHE_HOME:-$HOME/.cache}/dmenu.history

p='run »'

ign='mm'

_ign="^($ign)( |\$)"

r=$(dmenu-print-history "$h" | dmenu -l 7 -p "$p")

if [[ "$r" ]]; then
	if ! [[ "$r" =~ $_ign ]]; then
		echo "$(date +%s) $r" >> "$h"
	fi

	echo "$r" | ${SHELL:-/bin/sh} &
fi
