#!/bin/sh

d=~/Downloads; cd "$d"

p='downloads »'

r=$(perl -E 'say for
		map {pop $_}
		sort {$b->[9] <=> $a->[9]}
		map {[stat $_, $_]}
		grep {!/\.(part|added)$/}
		grep {-f}
		<*>' | dmenu -l 15 -p "$p")

if [ "$r" ]; then
	xdg-open "$r" &
fi
