#!/usr/bin/env bash

. lib.bash || exit

g_show_osd() {
	busctl call --user \
		org.gnome.Shell /org/gnome/Shell \
		org.gnome.Shell ShowOSD \
		a{sv} 2 \
			icon  s "$1" \
			label s "$2" &
}

schema=org.gnome.desktop.peripherals.touchpad
key=disable-while-typing

val=$(gsettings get $schema $key)
case $val in
	true) val=false;;
	false) val=true;;
esac
gsettings set $schema $key $val

if [[ ! -t 1 ]]; then
	case $val in
		true) status="resumed"; icon="touchpad-disabled";;
		false) status="paused"; icon="input-touchpad";;
	esac
	g_show_osd "$icon-symbolic" "DWT $status"
fi
