#!/usr/bin/env bash
# each -- reverse xargs
#
# Syntax not set in stone yet.
#
# Usage 1:
#
#   - for x in one two three; do frob "$x"; done
#   + each frob {} -- one two three
#
# Usage 2:
#
#   - find ./foo/ | xargs -I -d '\n' frob {}
#   + find ./foo/ | each frob

args=()
cmd=()
flag=0

if [[ -t 0 ]]; then
	for arg; do
		if (( flag == 1 )); then
			args+=("$arg")
		elif [[ $arg == "--" ]]; then
			flag=1
		else
			cmd+=("$arg")
		fi
	done

	for arg in "${args[@]}"; do
		"${cmd[@]}" "$arg"
	done
else
	for arg; do
		cmd+=("$arg")
	done

	while IFS= read -r arg; do
		"${cmd[@]}" "$arg" </dev/tty
	done
fi
