#!/usr/bin/env python
# exiftouch -- update JPEG file modification time from Exif 'Date Original'
import argparse
import datetime
import exif
import os
from pprint import pprint

def get_time_exif(path):
    def parse_dt(dt):
        return datetime.datetime.strptime(dt, "%Y:%m:%d %H:%M:%S").astimezone()

    with open(path, "rb") as fh:
        img = exif.Image(fh)

    try:
        return parse_dt(img.datetime_original)
    except AttributeError:
        try:
            print(f"{path}: has no datetime_original, try datetime")
            return parse_dt(img.datetime)
        except AttributeError:
            print(f"{path}: EXIF data has no datetime")
            return None
    except KeyError:
        print(f"{path}: has no EXIF data")
        return None

parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", action="store_true")
parser.add_argument("file", nargs="+")
args = parser.parse_args()

for path in args.file:
    tm = get_time_exif(path)
    if not tm:
        continue

    if args.verbose:
        print(repr(when), repr(tm))
        #print(repr(tm))
        #print(tm.timestamp())
    atime = int(datetime.datetime.now().timestamp())
    mtime = int(tm.timestamp())
    os.utime(path, times=(atime, mtime))
    if args.verbose:
        pass
        #print(repr(img.datetime), type(img.datetime))
        #print(img.gps_datestamp, img.gps_timestamp)
