#!/bin/sh

f=$1

case $f in
*.tar.bz2|*.tbz)
	pv "$f" | bzip2 -d | tar x ;;
*.bz2)
	pv "$f" | bzip2 -d > "${f%.bz2}" ;;
*.tar.gz|*.tgz)
	pv "$f" | gzip -d | tar x ;;
*.gz)
	pv "$f" | gzip -d > "${f%.gz}" ;;
*.tar.xz|*.txz)
	pv "$f" | xz -d | tar x ;;
*.xz)
	pv "$f" | xz -d > "${f%.xz}" ;;
esac
