#!/usr/bin/env bash

. lib.bash || exit

sizes=(
	[144]=1474560
	[720]=737280
)

case $1 in
    make|mk)
	name=$2
	size=${sizes[144]}
	case $name in
	*.vfd|*.dsk|*.ima|*.img)
		name=${name%.*}.img;;
	*)
		name+=.img;;
	esac
	if [[ -e $name ]]; then
		die "file $name already exists"
	fi
	fallocate -l "$size" "$name"
	echo "created: $name"
	mkfs.vfat "$name"
	;;
    mount|m)
	name=$2
	mtpt=$XDG_RUNTIME_DIR/fd
	mkdir -p "$mtpt"
	sudo mount "$name" "$mtpt" -o loop,uid=$UID
	echo "mounted: $name -> $mtpt"
	;;
    umount|unmount|u)
	mtpt=$XDG_RUNTIME_DIR/fd
	ldev=$(findmnt -n -o SOURCE "$mtpt")
	file=$(losetup -n -O BACK-FILE "$ldev")
	sudo umount "$mtpt"
	until rmdir "$mtpt" 2>/dev/null; do sleep 1; done &
	echo "unmounted: $file -> $mtpt"
	;;
    '')
	{
	echo "usage: fd make <name>"
	echo "       fd mount <name>"
	echo "       fd umount"
	} >&2
	;;
    *)
	die "unknown command '$1'"
	;;
esac
