#!/bin/sh
host=$1
case $host in
	*.*.*.*)
		filter="host $host";;
	*:*:*:*:*:*)
		systemd-hwdb query OUI:$(echo $host | sed 's/[:-]//g' | tr 'a-z' 'A-Z')
		filter="ether host $host";;
	*)
		echo "bad filter"; exit 2;;
esac
for file in cap*.pcap; do
	echo "-- $file --"
	tcpdump -n -e -r "$file" "$filter"
done
