#!/bin/sh
p=""
p="$p application.name='Firestorm Viewer'"
p="$p application.icon_name='firestorm-viewer'"
export PULSE_PROP_OVERRIDE="$p"
export SDL_VIDEO_X11_WMCLASS='firestorm-viewer'
exec ~/.local/firestorm/firestorm "$@"
