#!/usr/bin/env bash

. lib.bash || exit

for nic in /sys/class/net/*; do
	device=$(readlink -f $nic/device)
	driver=$(readlink -f $device/driver)
	parent=$(readlink -f $device/..)

	# 2019-04-08: hopefully fixed by 23c78343ec369 (in stable 5.0.6)
	[[ $driver == */@(r8169|iwl*) ]] || continue

	sudo: ctl $device/remove=1

	sudo: ctl $parent/rescan=1
done
