#!/usr/bin/env bash

if [[ $1 == -v ]]; then
	arg=-v
	shift
else
	arg=-n
fi

find "$@" -type f -name '*\[*\]*Imgur.*' |
while read -r f; do
	export h=$(sha1sum "$f" | awk '{print $1}')
	prename $arg -b -i '
	# entities
		s/&#(\d+)/chr($1)/ge;
		s/&quot;//g;
	# "caption [source]" → "source <hash>"
		s{(.+)/.*?\[(?:Daily )?(.+?)(?: #\d+)?\].*?\.(.+?)$}{$1/$2 $ENV{h} - Imgur.$3};
	' "$f"
done
