#!/usr/bin/env bash

. lib.bash || exit

for nic in /sys/class/net/*; do
	device=$(readlink -f $nic/device)
	driver=$(readlink -f $device/driver)
	parent=$(readlink -f $device/..)

	[[ $driver == */r8169 ]] || continue

	sudo: ctl $device/remove=1

	sudo: ctl $parent/rescan=1
done
