#!/usr/bin/env bash

for nic in /sys/class/net/eth*; do
	dev=$(readlink -f $nic/device)
	bus=$(readlink -f $dev/..)

	echo "removing $dev"
	echo 1 > $dev/remove

	if [ -e $dev ]; then
		echo "waiting for $dev to disappear"
		while [ -e $dev ]; do
			sleep 0.2
		done
		echo "ok"
	fi

	echo "rescanning $bus"
	echo 1 > $bus/rescan
done
