#!/usr/bin/env bash

opt="-n"

if [[ $1 == -v ]]; then
	opt="-v"
fi

find -type f -name "* - ????????????????????????????????.*" -exec \
	prename $opt -b -i '
	use warnings;
	use strict;
	use List::MoreUtils qw(uniq);

	if (my @m = m!^
			# dir
			(.+) /
			# characters
			(?:
				(.+?) \s
			)??
			# copyrights
			(?:
				\( (.+?) \) \s
			)?
			# artists
			(?:
				drawn \s by \s (.+?) \s
			)?
			- \s
			# tail . ext
			([a-f0-9]{32,40} \. \w+)
		$!x) {
		my ($dir, $characters, $copyrights, $artists, $tail) = @m;

		$characters //= "";
		$copyrights //= "";
		$artists    //= "";

		$characters =~ s/,? and /, /;
		$copyrights =~ s/,? and /, /;
		$artists    =~ s/,? and /, /;

		my @characters = split(/, /, $characters);
		my @copyrights = split(/, /, $copyrights);
		my @artists    = split(/, /, $artists);
		my @tags       = (@artists, @copyrights, @characters);

		for (@tags) {
			s/[ ]/_/g;
			s/_movie$//;
			s/_\(artist\)//;
			s/suzumiya_haruhi_no_yuuutsu/haruhi_suzumiya/;
			s/^(others|marshall)$//;
		}

		@tags = uniq grep {/./} @tags;

		$_ = "$dir/@tags $tail";
	}
	' {} +
