#!/usr/bin/env bash

if [[ $1 == -a ]]; then
	set -- wolke sky star ember wind
elif ! (( $# )); then
	set -- fs1
fi

for host; do
	case $host in
		fs1) dir="/srv/http/$host";;
		fs*) dir="pub/$host";;
		wind) dir="~ /$host";;
		*) dir='~';;
	esac
	ssh $host.nullroute.eu.org "df -h $dir" \
	| awk -v host=$host 'NR > 1 { printf "%-8s %4s out of %s free (%s of %s used)\n",
					host ":", $4, $2, $5, $1 }'
done
