#!/bin/sh

# http://lists.freedesktop.org/archives/mesa-dev/2013-March/036586.html

export GALLIUM_HUD="cpu0+cpu1+cpu2+cpu3:100,cpu:100,fps;draw-calls,requested-VRAM+requested-GTT,VRAM-usage+GTT-usage"

exec "$@"
