#!/usr/bin/env python3
import os
import sys

oui = []

if oui:
    assert(0 < len(oui) < 6)
    buf = os.urandom(6 - len(oui))
    buf = [*oui, *buf]
else:
    buf = os.urandom(6)
    buf = [*buf]
    buf[0] &= ~1 # clear multicast bit
    buf[0] |= 2 # set local bit

buf = ["%02x" % x for x in buf]
print(*buf, sep=":")
