#!/usr/bin/env python
import sys
import subprocess
from collections import defaultdict

def get_refs():
    proc = subprocess.Popen(["git", "show-ref"], stdout=subprocess.PIPE)
    for line in proc.stdout:
        yield line.rstrip(b"\n").split(None, 1)

def get_commits(range):
    proc = subprocess.Popen(["git", "rev-list", range], stdout=subprocess.PIPE)
    for line in proc.stdout:
        yield line.rstrip(b"\n").split()[0]

def fmt(b):
    return b.decode("utf-8")

try:
    range = sys.argv[1]
except IndexError:
    range = "HEAD"

refs = defaultdict(set)

for ref_hash, ref_name in get_refs():
    refs[ref_hash].add(ref_name)

for commit_hash in get_commits(range):
    if commit_hash in refs:
        for ref in refs[commit_hash]:
            print(fmt(commit_hash), fmt(ref))
