#!/usr/bin/env bash

dir=$(git rev-parse --git-dir)

for objid; do
	loose=$dir/objects/${objid:0:2}/${objid:2}

	if [ -e "$loose" ]; then
		rm -f "$loose"
		echo "Removed $loose"
	fi

	if ! git cat-file -e "$objid"; then
		continue
	fi

	for pack in "$dir/objects/pack"/*.pack; do
		idx=${pack%.pack}.idx
		if git show-index <"$idx" 2>/dev/null | fgrep -wqs "$objid"; then
			echo "Unpacking $pack"
			tmp=$(mktemp "$dir/objects/pack.XXXXXXXX.tmp")
			mv "$pack" "$tmp"
			git unpack-objects <"$tmp"
			rm -f "$tmp" "$idx"
		fi
	done

	if [ -e "$loose" ]; then
		rm -f "$loose"
		echo "Removed $loose after unpacking"
	fi
done
