#!/usr/bin/env perl

exec {"/usr/bin/gnome-terminal"}
		"gnome-terminal", @ARGV;

=off

my $count	= scalar grep {$_ eq $ENV{USER}} split /\s+/, `users`;

my $top		= 100;
my $left	= $top + 70;
my $spacing	= 20;

my $offset	= $spacing * $count;

$top	+= $offset;
$left	+= $offset;

my $geom	= "+$left+$top";

exec {"/usr/bin/gnome-terminal"}
		"gnome-terminal", "--geometry", $geom;

=cut
