#!/usr/bin/env bash
# go - quick connection script

. lib.bash || exit

progname='goto-server'

usage() {
	echo "Usage: $progname <host>"
}

do_rdp() {
	local host=$1
	debug "using RDP to $host"
	mstsc "$host" "${@:2}"
	debug "spawned 'mstsc...'"
}

cd ~

case ${0##*/} in
    go|goto-server|@)
	;;
    *)
	set -- "${0##*/}" "$@"
	;;
esac

case $1 in
    "")
	usage >&2
	die "missing host name"
	;;
    *)
	lib::find_file server_list= ~/lib/servers.txt config:servers.txt \
		|| die "server list '$server_list' not found"

	name="$1"
	if [[ $2 && $2 != /* ]]; then
		name+="-$2"; shift
	fi
	debug "looking for name '$name'"

	ip= rest=
	while read -r _name _ip _rest; do
		if [[ $name == "$_name" ]]; then
			ip=$_ip
			rest=$_rest
		fi
	done < "$server_list"
	debug "resulting ip='$ip' rest='$rest'"

	case $ip in
	    imap://*|imaps://*)
		exec mutt -f "$ip$2" $rest;;
	    rdp://*)
		do_rdp "${ip#rdp://}" $rest;;
	    *://*)
		die "unknown protocol '${ip%%//*}//'";;
	    "")
		die "unknown host '$name'";;
	    *)
		do_rdp "$ip" $rest;;
	esac
	;;
esac
# vim: sts=8
