#!/usr/bin/env bash
# go - quick connection script

. lib.bash || exit

do_sshfs() {
	local src=$1 mtpt=$2
	mkdir -p "$mtpt"
	mountpoint -q "$mtpt" ||
		sshfs -o idmap=none "$src" "$mtpt"
	echo "Mounted sshfs#$src on $mtpt"
}

do_rdp() {
	local host=$1
	debug "using RDP to $host"
	spawn mstsc "$host" -D -g workarea
	#spawn mstsc "$host" -f
	debug "spawned 'mstsc...'"
}

do_ssh() {
	debug "using SSH to $1"
	exec ssh "$@"
}

cd ~

case ${0##*/} in
    go|goto-server)
	;;
    *)
	set -- "${0##*/}" "$@"
	;;
esac

case $1 in
    snow)
	host="snow"
	if [[ $2 == "fs" ]]; then
		do_sshfs "$host:/" "$XDG_RUNTIME_DIR/fs/snow"
	elif [[ $2 == "suspend" || $2 == "hibernate" ]]; then
		do_ssh "$host" -oControlPersist=no \
			-oServerAliveInterval=1 \
			-oServerAliveCountMax=5 \
			"$2" &
	elif [[ $2 == "rdp" || (! $2 && ! -t 0) ]]; then
		do_rdp "$host"
	else
		do_ssh "$host" "${@:2}"
	fi
	;;
    dga)
	host="193.219.181.252"
	do_rdp "$host:1969"
	;;
    '')
	echo "Usage: $progname <host>" >&2
	die "missing host name"
	;;
    *)
	die "unknown host '$1'";
esac
