#!/usr/bin/env python3
# hi -- show recent IRC highlights
import argparse
from nullroute.core import Env
import os
import subprocess

def download_log(remote_host, remote_path, local_path):
    try:
        size = os.stat(local_path).st_size
        rcmd = f"tail -c +{size+1} '{remote_path}'"
    except FileNotFoundError:
        size = 0
        rcmd = f"cat '{remote_path}'"

    with open(local_path, "ab") as fh:
        subprocess.run(["ssh", remote_host, rcmd],
                       stdout=fh,
                       check=True)

    return os.stat(local_path).st_size - size

os.umask(0o077)

cache_path = Env.find_cache_file("highlights.txt")
config_path = Env.find_config_file("irc.conf")

rhost = "star"
rpath = "irclogs/perl.highmon.log"

delta = download_log(rhost, rpath, cache_path)
if delta == 0:
    print("No new items.")
