#!/usr/bin/env bash

hosts=' wolke sky star ember '
hosts+=' radius gw-core '

(for host in $hosts; do ssh $host 'printf "%s\t%s\t%s\t[%s]\n" "$(hostname)" "$(uname -r)" "$(uptime -p | sed "s/,.*//")" "$(uname -v)"' & done; wait) | sort -V -k 2 -r | column -t -s $'\t' -N HOST,KERNEL,UPTIME,BUILD
