#!/usr/bin/env bash

hosts='wolke sky star ember ghost'
hosts+=' radius gw-core'

(for host in $hosts; do ssh $host 'printf "%-10s: %-30s [%s]\n" "$(hostname)" "$(uname -r)" "$(uname -v)"' & done; wait) | sort -V -k 3 -r
