#!/usr/bin/env bash

hosts=' wolke sky star ember '
hosts+=' radius gw-core '

(for host in $hosts; do ssh $host 'printf "%-10s: %-20s %-14s [%s]\n" "$(hostname)" "$(uname -r)" "$(uptime -p | sed "s/,.*//")" "$(uname -v)"' & done; wait) | sort -V -k 3 -r
