#!/usr/bin/env expect
# htelnet -- telnet to a host that wants ^H for Backspace

set stty_init "erase ^H"

spawn -noecho telnet {*}$argv

interact {
	# Exit on Ctrl-]
	"\035" { send_user "\033\[1m<Disconnecting>\033\[m\n"; exit }
	# Exit on Ctrl-Backslash
	"\034" { send_user "\033\[1m<Disconnecting>\033\[m\n"; exit }
	# Translate Backspace to ^H
	"\177" { send "\010" }
}
