#!/usr/bin/env bash

interval=3
nlines=$(stty size | awk '{print $1}')
nlines=$(( nlines - 5 ))
nlines=20

txlast=0
rxlast=0
last=0
iter=0

while true; do
	sleep $interval &
	url="http://192.168.1.254:8000/ltpd8iyjpxe/IGD/upnp/IGD.xml"
	data=$(upnpc -u "$url" -S)
	txbytes=$(echo "$data" | awk '/^Bytes:/{print $3}')
	rxbytes=$(echo "$data" | awk '/^Bytes:/{print $5}')
	now=$(date +%s)

	if (( ++iter >= nlines )); then
		printf '\e[%dA\e[1M\e[%dB' $((nlines-1)) $((nlines-2))
	fi

	if (( last > 0 )); then
		txdelta=$(( txbytes - txlast ))
		rxdelta=$(( rxbytes - rxlast ))
		if (( txdelta < 0 || rxdelta < 0 )); then
			echo "negative delta:"
			echo "tx = ($txbytes - $txlast) => ($txdelta)"
			echo "rx = ($rxbytes - $rxlast) => ($rxdelta)"
		fi
		txrate=$(( txdelta / interval ))
		rxrate=$(( rxdelta / interval ))
		if (( txrate > 70000 )); then
			txcolor=31
		elif (( txrate > 50000 )); then
			txcolor=33
		elif (( txrate > 10000 )); then
			txcolor=32
		else
			txcolor=
		fi
		rxcolor=
		date=$(date +%T -d "@$now")
		txrate=$(numfmt --to=iec --suffix=B/s -- $txrate | sed -r 's/[0-9.]+/& /')
		rxrate=$(numfmt --to=iec --suffix=B/s -- $rxrate | sed -r 's/[0-9.]+/& /')
	else
		txcolor=35
		rxcolor=35
		date="Total"
		txrate=$(numfmt --to=iec --suffix=B -- $txbytes | sed -r 's/[0-9.]+/& /')
		rxrate=$(numfmt --to=iec --suffix=B -- $rxbytes | sed -r 's/[0-9.]+/& /')
	fi

	printf "\e[2m%8s\e[m  "                   "$date"
	printf "\e[%sm%12s\e[m \e[2mup\e[m  "     "$txcolor" "$txrate"
	printf "\e[%sm%12s\e[m \e[2mdown\e[2m\n"  "$rxcolor" "$rxrate"

	txlast=$txbytes
	rxlast=$rxbytes
	last=$now
	wait
done
