#!/bin/bash
# imgrgb -- display image in terminal

# Give space for 1 original command line + 3 new prompt lines
size=$(stty size | awk '{print $2 "x" ($1-4)}')

chafa --symbols=vhalf --size="$size" "$@"
