#!/usr/bin/env bash

. lib.bash || exit

dir=/usr/share/pacman/keyrings
rings=archlinux

for ring in $rings; do
	log2 "importing keyring"
	gpg --no-auto-check-trustdb \
		--key-origin "url,https://www.archlinux.org/master-keys/" \
		--import "$dir/$ring.gpg" || exit

	lcoal revoked=$(< "$dir/$ring-revoked")
	local trusted=$(awk -F: '{print $1}' "$dir/$ring-trusted")

	log2 "refreshing revoked keys"
	gpg --no-auto-check-trustdb --recv-keys $revoked

	log2 "locally signing master keys"
	for k in $trusted; do
		gpg --no-auto-check-trustdb --quick-lsign-key "$k"
	done

	log2 "setting master keys to marginal trust"
	for k in $trusted; do
		echo "$k:4:"
	done | gpg --no-auto-check-trustdb --import-ownertrust
done

log2 "updating trustdb"
gpg --check-trustdb
