#!/usr/bin/env bash
if [ ! "$MAGICK" ]; then
	cmd=$(< /proc/$PPID/cmdline)
	if [ "$cmd" = "bash" ]; then
		echo "error: insufficient magic (did you forgot '#!/usr/bin/env python' again?)"
		kill $PPID
		exit 42
	fi
fi

exec /usr/bin/import "$@"
