#!/usr/bin/python
# print summarized CIDR masks for a given IP address range

import sys
import nullroute as lib
from ipaddress import *

try:
    first_addr = ip_address(sys.argv[1])
    last_addr  = ip_address(sys.argv[2])

    masks = summarize_address_range(first_addr, last_addr)

    for net in masks:
        print(net)
except ValueError as e:
    lib.die(e)
