#!/usr/bin/env bash

. lib.bash || exit

host=$1; shift

[[ $host ]] || die "BMC address not specified"

# load alias database

declare -A hosts_args=()
while read r_host r_args; do
	if [[ $r_host && $r_host != '#'* && $r_args ]]; then
		hosts_args["$r_host"]=$r_args
	fi
done < ~/.config/nullroute.eu.org/ipmi-servers.txt

# resolve host aliases

args="@$host"
while [[ $args == @* ]]; do
	debug "chasing alias '$host' => '$args'"
	host=${args#@}
	args=${hosts_args["$host"]}
done
debug "configured options: '$args'"

# find credentials

fqdn=$(fqdn "$host")

for host in "$host" "$fqdn" "bmc.$host" "bmc.$fqdn"; do
	username=$(getnetrc -dsf %u "ipmi/$host") &&
	password=$(getnetrc -dsf %p "ipmi/$host") &&
	[[ $username && $password ]] && break
done

[[ $username && $password ]] || die "credentials for 'ipmi/$host' not found"

privlvl=$(getnetrc -dsf %a "ipmi/$host")
kgkey=$(getnetrc -dsf %p "rmcp/$host")

case ${privlvl,,} in
	a|admin*|"")	privlvl=ADMINISTRATOR;;
	o|oper*)	privlvl=OPERATOR;;
	u|user)		privlvl=USER;;
esac

# launch the client

info "connecting to $host"

if [[ $1 == console ]]; then
	info "escape character is '&'"
	exec ipmiconsole -h "$host" -k "$kgkey" -u "$username" -p "$password" -l "$privlvl" "${@:2}"
elif [[ $1 == config ]]; then
	exec ipmi-config -D lanplus -h "$host" -k "$kgkey" -u "$username" -p "$password" -l "$privlvl" "${@:2}"
else
	export IPMI_PASSWORD=$password
	export IPMI_KGKEY=$kgkey
	exec ipmitool -I lanplus -H "$host" -K -U "$username" -E -L "$privlvl" "$@"
fi
