#!/usr/bin/env bash

. lib.bash || exit

host=$1; shift

[[ $host ]] || die "BMC address not specified"

declare -A hosts_args=()
while read r_host r_args; do
	if [[ $r_host && $r_host != '#'* && $r_args ]]; then
		hosts_args["$r_host"]=$r_args
	fi
done < ~/.config/nullroute.eu.org/ipmi-servers.txt

args="@$host"
while [[ $args == @* ]]; do
	debug "chasing alias '$host' => '$args'"
	host=${args#@}
	args=${hosts_args["$host"]}
done
debug "configured options: '$args'"

username=$(getnetrc -df %u "ipmi/$host")
password=$(getnetrc -df %p "ipmi/$host")
[[ $username && $password ]] || die "credentials for 'ipmi/$host' not found"

info "connecting to $host"
export IPMI_PASSWORD=$password
eval 'exec ipmitool -H "$host" -U "$username" -E' "$args" '"$@"'
