#!/usr/bin/env bash

. lib.bash || exit

host=virgule.cluenet.org

export MOSH_TITLE_NOPREFIX='y'

opt=(
	1049	# alternate screen
	2004	# bracketed paste
	#1006	# SGR mouse tracking
	1005	# UTF-8 mouse tracking
	1002	# cell mouse tracking
)

lock=$XDG_RUNTIME_DIR/.irc.lock@$XDG_SESSION_ID
exec {fd}<> "$lock"
flock -xn $fd || die "already connected from $HOSTNAME/$XDG_SESSION_ID"

r=0

printf '\e[H\e[2J'
printf '\e[?%sh' ${opt[@]}
printf '\e[H\e[2J'
mosh $host -- tmux attach -t irc || {
	r=$?
	err "mosh exited with status $r"
	read -rsN1
}
printf '\e[?%sl' $(printf '%s\n' ${opt[@]} | tac)
printf '\e[H\e[2J'

hi >&/dev/null {fd}>&- &

if (( r )); then
	err "mosh exited with status $r"
fi

rm -f "$lock"
exit $r
