#!/usr/bin/env bash
# isputty -- Check whether xterm is being emulated by PuTTY
#
# This is needed for things like Neovim, which strictly adhere to terminfo data
# and do not recognize the (or rather, incorrectly recognize) Home/End keys,
# which PuTTY sends as \e[1~ and \e[4~ whereas terminfo(xterm-256color) says
# khome/kend are \eOH and \eOF respectively.

# Don't bother checking when inside tmux
if [[ $TERM != @(xterm|xterm-256color) ]]; then
	exit 1
fi

# Request secondary DA, then primary DA
printf '\e[>c'	# returns '\e[>XXXc'
printf '\e[c'	# returns '\e[?XXXc'

if read -r -s -d '?' -t 2 ans1 &&
   read -r -s -d 'c' -t 2 ans2; then
	ans="${ans1}?${ans2}c"
	if [[ $ans == $'\e[>0;136;0c\e[?6c' ]]; then
		exit 0
	else
		exit 1
	fi
else
	echo "${0##*/}: Did not receive Primary DA reply from terminal" >&2
	exit 4
fi
