#!/usr/bin/env bash
# isputty -- Check whether xterm is being emulated by PuTTY
#
# Issues the Secondary DA and Primary DA queries and checks for a known reply.
#
# This is needed for things like Neovim, which strictly adhere to terminfo data
# and do not recognize the (or rather, incorrectly recognize) Home/End keys,
# which PuTTY sends as \e[1~ and \e[4~ whereas terminfo(xterm-256color) says
# khome/kend are \eOH and \eOF respectively.

if [[ $TERM == @(putty|putty-*) ]]; then
	exit 0
elif [[ $TERM != @(xterm|xterm-*) ]]; then
	exit 1
fi

trap "stty echo" EXIT
stty -echo

# Hack to detect terminals that fail to parse the Secondary DA query
if [[ ! $COLORTERM ]]; then
	printf '\e[c'
	if read -r -d '?' -t 2 ans1 && read -r -d 'c' -t 2 ans2; then
		ans="${ans1}?${ans2}c"
		if [[ $ans == *$'\e[?1;2c' ]]; then
			# Probably JuiceSSH -- definitely not PuTTY
			exit 1
		fi
	else
		echo "${0##*/}: Did not receive Primary DA reply from terminal" >&2
		exit 4
	fi
fi

printf '\e[>c\e[c'
if read -r -d '?' -t 2 ans1 && read -r -d 'c' -t 2 ans2; then
	ans="${ans1}?${ans2}c"
	if [[ $ans == *$'\e[>0;136;0c\e[?6c' ]]; then
		exit 0
	else
		exit 1
	fi
else
	echo "${0##*/}: Did not receive Primary DA reply from terminal" >&2
	exit 4
fi
