#!/usr/bin/env bash
# java-redir - prevent Java programs from littering $HOME

. lib.bash || exit

redir="$XDG_DATA_HOME/java-home"

debug "setting Java homedir to '$redir'"

if [[ ! -d "$redir" ]]; then
	mkdir "$redir"
fi

if [[ ! -e "$redir/.java" ]]; then
	ln -r -s -f "$HOME/.java" "$redir/.java"
fi

exec java -Duser.home="$redir" "$@"
