#!/usr/bin/env bash
# java-redir - prevent Java programs from littering $HOME

. lib.bash || exit

# 2017-12: temporary, to deal with Java 9 not rendering airControl2 correctly
export MESA_GL_VERSION_OVERRIDE="3.0"

origname=${progname%-redir}
progname="java-redir"
homedir="$XDG_DATA_HOME/java-home"

for dir in ~/.local/bin /usr/bin; do
	java="$dir/$origname"
	if [[ -x "$java" ]]; then
		break
	fi
done

if [[ ! -x "$java" ]]; then
	die "could not find '$origname'"
fi

debug "Java runtime: '$java'"
debug "Java homedir: '$homedir'"

case $origname in
	java)
		set -- -Duser.home="$homedir" "$@";;
	javaws)
		set -- -J-Duser.home="$homedir" "$@";;
	*)
		die "unknown program '$origname'";;
esac

if [[ ! -d "$homedir" ]]; then
	mkdir "$homedir"
fi

if [[ ! -e "$homedir/.java" ]]; then
	ln -n -r -s -f "$HOME/.java" "$homedir/.java"
fi

exec "$java" "$@"
