#!/usr/bin/env bash
# lcpkg -- list the contents of a system package, in color

case ${0##*/} in
	llpkg)
		opts="-lh";;
	*)
		opts="";;
esac

for pkg; do
	lspkg "$pkg" | xargs -d '\n' ls $opts -d --color=always 2>&1 | ${PAGER:-less}
done
