#!/usr/bin/env bash

case $TERM in xterm*|tmux*)
	# Display emphasis in manual pages as italics instead of underline.
	# This only works with the "classic" output mode i.e. GROFF_NO_SGR
	# (grotty -c). Note that Debian patches groff to use classic mode for
	# manual pages by default (with GROFF_SGR to re-enable modern mode).
	export LESS_TERMCAP_us=$'\e[3m'
	export LESS_TERMCAP_ue=$'\e[23m'
esac

exec /usr/bin/less "$@"
