#!/bin/sh

locate -Abi "$@" | grep -v '/\.old/'

case $(hostname) in frost)
	# frost is low on disk capacity, so a large part of ~/Dropbox has been
	# mounted from /n/ember.
	on -C. ember locate -Abi "$@" | grep -v '/\.old/'
esac
