#!/bin/sh
# vim: sw=4

do_list() {
    local f=$1
    case $f in
	*.rar)
	    unrar vb "$f";;
	*.rpa)
	    unrpa -l "$f";;
	*.tar.*|*.tbz2|*.tgz|*.txz)
	    tar tf "$f";;
	*.zip)
	    unzip -l "$f";;
	*.7z|*.cab|*.deb|*.iso|*.rpm)
	    bsdtar tf "$f";;
	*.msi)
	    7za l "$f";;
	*)
	    echo Unknown file type >&2; exit 1;;
    esac
}

do_extract() {
    local f=$1 d=${1%.*}.out/
    mkdir -p "$d"
    case $f in
	*.tar.*|*.cab|*.tbz2|*.tgz|*.txz)
	    bsdtar -xvf "$f" -C "$d";;
	*.bz2)
	    do_pv "$f" bzip2;;
	*.gz)
	    do_pv "$f" gzip;;
	*.7z|*.msi)
	    7za x -o"$d" "$f";;
	*.rar)
	    rar x "$f" "$d/";;
	*.zip)
	    unzip -d "$d" "$f";;
	*)
	    echo Unknown file type >&2; exit 1;;
    esac
}

do_pv() {
    local f=$1 o=${f%.*} c=$2
    pv -c "$f" | "$c" -d | pv -c > "$o"
}

case ${0##*/} in
    lsar)
	do_list "$@";;
    unar)
	do_extract "$@";;
esac
