#!/usr/bin/env perl
# Linden Dollar to USD rate calculator

sub get_rate { 250; }

my ($pow, $from, $to, $fromc, $toc);

($from, $fromc) = @ARGV;

if (lc $fromc eq 'lsl') {
	$pow = 1;
	($fromc, $toc) = ("LSL", "USD");
}
elsif (lc $fromc eq 'usd') {
	$pow = -1;
	($fromc, $toc) = ("USD", "LSL");
}
else {
	exit 1;
}

my $to = $from / (get_rate() ** $pow);

print "$from $fromc = $to $toc\n";
