#!/usr/bin/env perl

my $pattern = $ARGV[0];
my $count = int $ARGV[1];
my @missing;

$pattern =~ s/[\[\]]/\\$&/g;

for my $i (1..$count) {
	my $name = sprintf($pattern, $i);
	my @files = glob($name);
	if (!@files) {
		push @missing, $i;
	}
}

if (@missing) {
	print "Missing: ", join(", ", @missing), "\n";
}
