#!/usr/bin/env perl
use Nullroute::Lib;

if (@ARGV < 1) {
	_die("missing file pattern");
}
if (@ARGV < 2) {
	_die("missing max counter");
}

my $pattern = $ARGV[0] =~ s/[\[\]]/\\$&/gr;

if ($pattern !~ /%\d*[ds]/) {
	_die("file pattern doesn't have %d specifier");
}

my $count = int $ARGV[1];

my @missing = grep {@a = glob(sprintf($pattern, $_)); grep {!-e $_} @a} 1..$count;

if (@missing) {
	print "Missing: ", join(", ", @missing), "\n";
}
