#!/usr/bin/env perl

my $pattern = $ARGV[0] =~ s/[\[\]]/\\$&/gr;
my $count = int $ARGV[1];

my @missing = grep {@a = glob(sprintf($pattern, $_)); !@a} 1..$count;

if (@missing) {
	print "Missing: ", join(", ", @missing), "\n";
}
