#!/usr/bin/env bash

for arg; do
	gvfs-set-attribute "$arg" metadata::evince::continuous 0
	gvfs-set-attribute "$arg" metadata::evince::sizing_mode 'automatic'
	#gvfs-set-attribute "$arg" metadata::evince::window_maximized 1
done
