#!/usr/bin/env bash

boundary=MARK-$(head -c 12 /dev/urandom | base64)

base_mime="Content-Type: text/plain"
seen_mime=0
mp_mime="Content-Type: multipart/related; boundary=\"$boundary\""

while IFS='' read -r line; do
	if [[ "$line" == Content-Type:* ]]; then
		# header line
		base_mime=$line
		seen_mime=1
		echo "$mp_mime"
	elif [[ ! "$line" && "$base_mime" ]]; then
		# finished all headers
		if (( ! seen_mime )); then
			echo "$mp_mime"
		fi
		echo ""
		echo "--$boundary"
		echo "$base_mime"
		echo ""
		base_mime=""
	else
		echo "$line"
	fi
done

for input; do
	unset temp

	case $input in
		http://*|https://*)
			temp=$(mktemp /tmp/attach.XXXXXX)
			curl -sSf "$input" -o "$temp"
			file=$temp
			;;
		*)
			file=$input
			;;
	esac

	mime=$(file --dereference --brief --mime-type "$file")

	echo "--$boundary"
	echo "Content-Type: $mime"
	echo "Content-Disposition: attachment; filename=\"${input##*/}\""
	echo "Content-Transfer-Encoding: base64"
	echo ""
	base64 < "$file"

	if [[ "$temp" ]]; then
		rm -f "$temp"
	fi
done

echo "--$boundary--"
