#!/usr/bin/env bash

from="iso8859-1"
to="cp1251"

while getopts ":f:" OPT; do
	case $OPT in
	f) from=$OPTARG;;
	*) die_getopts;;
	esac
done; shift $((OPTIND-1))

to=${1:-"$to"}

iconv -t "$from" | iconv -f "$to" # [sic]
