#!/bin/bash
# 2010 grawity@gmail.com
# WTFPL v2 <http://sam.zoy.org/wtfpl/>

usage() {
	echo "usage: $(basename "$0") [-dhq] [-o oldpath] [path]"
	exit 2
}

sdate() { date -d "@$1" +"%Y-%m-%d %H:%M"; }
sfdate() { sdate "$(mtime "$1")"; }
mtime() { stat -Lc %Y "$1"; }

# set defaults
motd=/etc/motd
last=$HOME/tmp/motd-$(hostname)
diff=false
conddiff=false
force=false
quiet=false

# parse options
while getopts ":Ddfho:q" OPT; do
	case $OPT in
	D)	diff=true conddiff=false ;;
	d)	diff=true conddiff=true ;;
	f)	force=true ;;
	o)	last=$OPTARG ;;
	h)	usage ;;
	q)	quiet=true ;;
	\?)	echo "motd: illegal option '$OPTARG'" >&2
		usage ;;
	esac
done; shift $(( OPTIND-1 ))

[ "$1" ] && motd=$1

# do the job
if [ ! -f "$last" ] || $force; then
	# motd added (first run on this host?)
	if [ -f "$motd" ]; then
		if $diff && ! $conddiff; then
			diff -uN "$last" "$motd" && echo "motd: no changes"
		else
			cat "$motd"
		fi
		$quiet || echo "motd: last updated $(sfdate "$motd")" >&2
		cp -p "$motd" "$last"
	else
		$quiet || echo "no motd" >&2
	fi

elif [ ! -f "$motd" ]; then
	# motd removed
	if $diff; then
		diff -uN "$last" "$motd"
	fi

	$diff || echo "motd: removed" >&2
	rm "$last"

elif ! cmp -s "$last" "$motd"; then
	# motd updated
	if $diff; then
		diff -uN "$last" "$motd"
	else
		cat "$motd"
	fi

	echo "motd: updated $(sfdate "$motd")" >&2
	cp -p "$motd" "$last"

else
	# no change
	$quiet || echo "motd: no changes (last updated $(sfdate "$motd"))" >&2
	cp -p "$motd" "$last" # in case local copy is newer
fi
