#!/usr/bin/env bash

. lib.bash || exit

args=() files=()

while (( $# )); do
	arg=$1
	case $arg in
	-kind|-type)
		kind=$2; shift;;
	-title)
		args+=(-song "$2"); shift;;
	-disc|-disk)
		if [[ $2 == */* ]]; then
			args+=(-disk "${2%%/*}" -disks "${2##*/}")
		else
			args+=(-disk "$2")
		fi; shift;;
	-track)
		if [[ $2 == */* ]]; then
			args+=(-track "${2%%/*}" -tracks "${2##*/}")
		else
			args+=(-track "$2")
		fi; shift;;
	-[a-z]*)
		args+=("$arg" "$2"); shift;;
	*)
		files+=("$arg");;
	esac
	shift
done

if [[ $kind ]]; then
	args+=(-type "$kind")
fi

for file in "${files[@]}"; do
	log "tagging $file"
	mtime=$(stat -c %Y "$file")
	mp4tags "${args[@]}" "$file"
	touch --date="@$mtime" "$file"
done
