#!/bin/sh
# wrapper for 'mpDris2' implementing -k and daemonization

name='mpDris2'
exe='/usr/bin/mpDris2'
if [ "$1" = "-k" ] || [ "$1" = "--kill" ]; then
	exec pkill -F "$(spawn -P "$name")"
else
	#if [ "$DESKTOP_SESSION" = "gnome" ]; then
	#	dbus-name --wait org.gnome.SettingsDaemon
	#fi
	#exec spawn -l "$name" "$exe" "$@"
	exec spawn "$exe" "$@"
fi
