#!/usr/bin/env perl
use warnings;
use strict;
use lib "/home/grawity/Dropbox/Code recycle bin/mq/perl";
use Nullroute::Mq::Client;

if (@ARGV < 2) {
	warn "Usage: mq-send <channel> <text> [<text>...]\n";
	exit 2;
}

my $mq = Nullroute::Mq::Client->new;

my @args;

for my $str (@ARGV) {
	if ($str eq "-") {
		$str = STDIN->getline;
		chomp $str;
	} elsif ($str eq "@") {
		my $str = do { local $/; STDIN->getline };
		chomp $str;
	} else {
		$str =~ s/^-//;
	}
	utf8::decode($str);
	push @args, $str;
}

my (undef, $id) = $mq->send(@args);
