#!/usr/bin/env bash
# look up the next free UID in LDAP

(( $# )) || set -- "nullroute.eu.org"

base="ou=people,dc=${1//./,dc=}"

ldapsearch -Q -b "$base" 'objectClass=posixAccount' uidNumber | awk \
	'BEGIN         { uid = 0 }
	 /^uidNumber:/ { if (uid < $2) {uid = $2} }
	 END           { print uid + 1 }'
