#!/usr/bin/env bash

colors=auto

while getopts "c" OPT; do
	case $OPT in
	c) colors=yes;;
	*) exit 2;;
	esac
done; shift $((OPTIND-1))

nmcli \
  -f "in-use,ssid,mode,chan,signal,bars,security,bssid" \
  -c $colors \
  dev wifi list
