#!/usr/bin/env bash

. lib.bash || exit

declare -- dir=/usr/lib/pkcs11
declare -A modules=(
	[etoken]=libeTPkcs11.so
	[cryptotech]=libccpkip11.so
	[gemalto]=libgclib.so
	[opensc]=opensc-pkcs11.so
	[cryptocard]=libgtop11dotnet.so
)
declare -A modnames=(
	[etoken]="Aladdin eToken (SafeNet)"
	[cryptotech]="CryptoTech"
	[gemalto]="Gemalto Classic Client"
	[opensc]="OpenSC"
	[cryptocard]="Gemalto Cryptocard"
)
declare -A databases=(
	[shared]="sql:$HOME/.pki/nssdb"
	[firefox]="$HOME/.mozilla/firefox/ov6jazas.default"
	[thunderbird]="$HOME/.thunderbird/1xrzgg5b.default"
)

database=shared

while getopts "d:" OPT; do
	case $OPT in
	d) database=$OPTARG;;
	esac
done; shift $((OPTIND-1))

dbpath=${databases[$database]:-$database}

while (( $# )); do
	cmd=$1; shift
	case $cmd in
	add)
		mod=$1; shift
		modname=${modnames[$mod]}
		modpath=$dir/${modules[$mod]}
		if [[ $modname && -f $modpath ]]; then
			do: modutil -dbdir "$dbpath" -add "$modname" -libfile "$modpath"
		else
			die "unknown module '$mod'"
		fi
		;;
	rm)
		mod=$1; shift
		modname=${modnames[$mod]}
		if [[ $modname ]]; then
			do: modutil -dbdir "$dbpath" -delete "$modname"
		else
			die "unknown module '$mod'"
		fi
		;;
	ls|list)
		do: modutil -dbdir "$dbpath" -list
		;;
	*)
		die "unknown command '$cmd'"
		;;
	esac
done
