#!/usr/bin/env bash

profile_default=()

profile_rain=(
	--repository	~/Backup/obnam-repository
	--encrypt-with	D24F6CB2C1B52632
	--keep		10d10w
)

#

if [[ $1 == @* ]]; then
	profile=profile_${1#@}[@]; shift
else
	profile=profile_default[@]
fi

exec /usr/bin/obnam "${!profile}" "$@"
