#!/bin/bash

get_git() {
	local u=$(git remote -v \
		| awk '$1 == "origin" && $3 == "(fetch)" {print $2}')
	local h=$(git rev-parse HEAD)
	echo "<$u> $h"
}

get_hg() {
	local u=$(hg paths default)
	local r=$(hg id -r tip -n)
	local h=$(hg id -r tip -i)
	echo "<$u> $r:$h"
}

get_svn() {
	local l="file://$PWD"
	local u=$(svn propget --revprop -r 0 svn:sync-from-url "$l")
	local r=$(svn propget --revprop -r 0 svn:sync-last-merged-rev "$l")
	echo "<$u> r$r"
}

for dir; do
	(cd "$dir"
	if test -f ".hg/hgrc"; then
		type=hg url=$(get_hg)
	elif test -f "config" && test -f "HEAD"; then
		type=git url=$(get_git)
	elif test -d "db/revprops"; then
		type=svn url=$(get_svn)
	fi
	echo "$dir:"
	echo "  ${type:-none} ${url:-none}")
done
