#!/usr/bin/env bash

if [[ $1 == sign ]]; then
	set -- "$1" \
		-pkcs11engine /usr/lib/openssl-1.0/engines/libpkcs11.so \
		-pkcs11module /usr/lib/pkcs11/opensc-pkcs11.so \
		-certs ~/Private/keys/identity/x509-code-signing/mantas@utenos-kolegija.lt-TERENA3-driversign-20160318.crt \
		"${@:2}"
fi

exec osslsigncode "$@"
