#!/usr/bin/env bash
package=$1
file=$2
if [[ $file != /* ]]; then
	file=$(readlink -m "$PWD/$file")
fi
url=$(pacman -Sp "$package")
pkg=/var/cache/pacman/pkg/${url##*/}
if [[ ! -s $pkg ]]; then
	sudo pacman -Sddw --noconfirm --quiet "$package" >&2
fi
bsdtar xfO "$pkg" "${file#/}"
