#!/usr/bin/env bash
# pclip -- put/paste text from clipboard

. lib.bash || exit

case ${0##*/} in
	gclip)
		if [ "$WAYLAND_DISPLAY" ] && have wl-copy; then
			cmd="wl-copy"
		elif [ "$DISPLAY" ] && have xsel; then
			cmd="xsel -i -b"
		elif [ "$DISPLAY" ] && have xclip; then
			cmd="xclip -in -selection clipboard"
		else
			vmsg "no clipboard tools available" >&2
			exit 1
		fi;;

	pclip|*)
		if [ "$WAYLAND_DISPLAY" ] && have wl-paste; then
			cmd="wl-paste"
		elif [ "$DISPLAY" ] && have xsel; then
			cmd="xsel -o -b"
		elif [ "$DISPLAY" ] && have xclip; then
			cmd="xclip -out -selection clipboard"
		else
			vmsg "no clipboard tools available" >&2
			exit 1
		fi;;
esac

if [ "$1" = -q ]; then
	echo "$cmd"
else
	$cmd
fi
