#!/usr/bin/env python
import sys
import lxml.etree

buf = sys.stdin.read()
tree = lxml.etree.XML(buf)

ifnames = {}
for iface in tree.xpath("/pfsense/interfaces/*"):
    desc = iface.xpath("string(descr)")
    ifnames[iface.tag] = desc

for iface in tree.xpath("/pfsense/dhcpd/*"):
    print("=== %s ===" % ifnames.get(iface.tag, iface.tag))
    for entry in iface.xpath("staticmap"):
        mac = entry.xpath("string(mac)")
        ip = entry.xpath("string(ipaddr)")
        desc = entry.xpath("string(descr)")
        print("%s │ %-15s │ %s" % (mac, ip or "--", desc))
