#!/usr/bin/env perl
use warnings;
use strict;
use Data::Dumper;
use XML::Simple qw(:strict);

my $conf = XMLin("-", KeyAttr => [], ForceArray => []);

#print Dumper($conf);

for my $iface (keys %{$conf->{dhcpd}}) {
	my $ifdata = $conf->{dhcpd}->{$iface};
	print "=== $iface ===\n";
	if (ref($ifdata->{staticmap}) eq "ARRAY") {
		for my $entry (@{$ifdata->{staticmap}}) {
			printf "%s │ %-15s │ %s\n",
				$entry->{mac},
				ref($entry->{ipaddr})
					? "--"
					: $entry->{ipaddr},
				$entry->{descr};
		}
	}
}
