#!/usr/bin/env python3
import os, sys
import bs4
import requests
from nullroute.core import Core
from nullroute.sec import get_netrc
from pprint import pprint

class PildykApi(object):
    BASE = "https://mano.pildyk.lt/api"

    def __init__(self, creds):
        self.creds = creds
        self.ua = requests.Session()
        self.ua.headers["user-agent"] += " (~/bin/pildyk-balance; nullroute.eu.org)"

    def login(self):
        r = self.ua.post(self.BASE + "/authentication/login",
                         data={"Msisdn": self.creds["login"],
                               "Password": self.creds["password"]})
        r.raise_for_status()
        return True

    def get_balance(self):
        # seems to be case-insensitive, JS mixes both variants
        r = self.ua.get(self.BASE + "/AccountInformation/get-user-balance")
        r.raise_for_status()
        return r.json()["result"]

    def get_plan_and_balance(self):
        r = self.ua.get(self.BASE + "/accountinformation/get-price-plan-and-account-balance")
        r.raise_for_status()
        return r.json()["result"]

Login = "60396811"

creds = get_netrc("http@mano.pildyk.lt", Login)
api = PildykApi(creds)
api.login()

data = api.get_plan_and_balance()
print("Account: +370.%(msisdn)s" % data)
print("Balance: %(balance)s €" % data)
print("Data:    %(addonData)s %(addonDataUnit)s" % data)
