#!/usr/bin/env python3
import os, sys
import requests
from nullroute.core import Core
from nullroute.sec import get_netrc
from pprint import pprint

class PildykApi(object):
    BASE = "https://mano.pildyk.lt/api"

    def __init__(self, creds):
        self.creds = creds
        self.ua = requests.Session()
        self.ua.headers["user-agent"] += " (~/bin/pildyk-balance at github/grawity/bin)"

    def get(self, path, **kwargs):
        Core.debug("GET %r %r", path, kwargs, skip=1)
        resp = self.ua.get(self.BASE + path, **kwargs)
        resp.raise_for_status()
        Core.trace("response: %r", resp.json(), skip=1)
        return resp.json().get("result")

    def post(self, path, **kwargs):
        Core.debug("POST %r %r", path, kwargs, skip=1)
        resp = self.ua.post(self.BASE + path, **kwargs)
        resp.raise_for_status()
        Core.trace("response: %r", resp.json(), skip=1)
        return resp.json().get("result")

    def login(self):
        self.post("/authentication/login",
                  data={"Msisdn": self.creds["login"],
                        "Password": self.creds["password"]})

    def get_balance(self):
        # JS appends /<msisdn>, seems optional
        # seems to be case-insensitive, JS mixes both variants
        return self.get("/AccountInformation/get-user-balance")

    def get_plan_and_balance(self):
        # JS appends /<msisdn>, seems optional
        return self.get("/accountinformation/get-price-plan-and-account-balance")

Login = "60396811"

creds = get_netrc("http@mano.pildyk.lt", Login)
api = PildykApi(creds)
api.login()

data = api.get_plan_and_balance()
print("Account: +370.%(msisdn)s" % data)
print("Balance: %(balance)s €" % data)
print("Data:    %(addonData)s %(addonDataUnit)s" % data)
