#!/usr/bin/env bash

. lib.bash || exit

for srcfile; do
	log "converting $srcfile"

	dir=$(dirname "$srcfile")
	name=$(basename "$srcfile")
	name=${name%.*}
	tmpfile=$dir/.temp-$$.$name.png
	outfile=$dir/$name.png

	debug "temp: $tmpfile"
	debug "output: $outfile"

	convert "$srcfile" "$tmpfile" &&
	pngcrush "$tmpfile" "$outfile" &&
	rm -f "$tmpfile" &&
	: trash "$srcfile"
done
