#!/bin/bash
# ~/.local/bin/pomf <file [file [...]]>

# Generate the form arguments for curl
for f in "$@"; do
    if [[ -e "$f" ]]; then
        curl_args+=(-F "files[]=@$f")
    else
        printf >&2 '%s: File does not exist\n' "$f"
    fi
done

# Make sure we have something to upload
if [[ -z "$curl_args" ]]; then
    printf >&2 'Nothing found to upload\n'
    exit 1
fi

if [[ -t 2 ]]; then
    curl_args+=(-#)
fi

upload=$(curl -S "${curl_args[@]}" http://pomf.se/upload.php)
geturls=$(jshon -e files -a -e name -upe url -u <<< "$upload")
clip=()

while {
    read -r name
    read -r url
} do
    url="http://a.pomf.se/$url"
    printf '%s: %s\n' "$name" "$url"
    clip+=("$url")
done <<< "$geturls"

if [[ "$DISPLAY" ]] && (( ${#clip[@]} )); then
	echo "${clip[*]}" | xsel -i -b
fi
