#!/usr/bin/env bash
# vim: ts=4:sw=4:et

. lib.bash || exit

have curl  || err "missing 'curl'"
have jshon || err "missing 'jshon'"

(( !errors )) || exit

curl_args=()
for f in "$@"; do
    if [[ -e "$f" ]]; then
        curl_args+=(-F "files[]=@$f")
    else
        err "file '$f' not found"
    fi
done

(( !errors )) || exit

(( ${#curl_args[@]} )) || die "nothing to upload"

if [[ -t 2 ]] && larger_than "$f" "1 << 18"; then
    curl_args+=(-#)
else
    curl_args+=(-s)
fi

upload=$(curl -S "${curl_args[@]}" https://pomf.se/upload.php)
urls=$(jshon -e files -a -e name -upe url -u <<< "$upload") || {
    trace "output: $upload"
    die "could not parse response"
}
clip=()
while { read -r name; read -r url; } do
    url=https://a.pomf.se/$url
    echo "$name → $url"
    echo "$(date --rfc-3339=seconds) $url $name" >> "$XDG_CACHE_HOME/pomf.log"
    clip+=("$url")
done <<< "$urls"

if [[ "$DISPLAY" ]] && (( ${#clip[@]} )); then
    if have xsel; then
        echo -n "${clip[*]}" | xsel -i -b
    fi
fi

(( !errors ))
