#!/usr/bin/env bash
# vim: ts=4:sw=4:et

. lib.bash || exit

curl_args=()

for f in "$@"; do
    if [[ -e "$f" ]]; then
        curl_args+=(-F "files[]=@$f")
    else
        warn "file '$f' does not exist"
    fi
done

if (( ! ${#curl_args[@]} )); then
    die "nothing to upload"
fi

if [[ -t 2 ]]; then
    curl_args+=(-#)
fi

upload=$(curl -S "${curl_args[@]}" http://pomf.se/upload.php)
geturls=$(jshon -e files -a -e name -upe url -u <<< "$upload")
clip=()

while {
    read -r name
    read -r url
} do
    url="http://a.pomf.se/$url"
    printf '%s: %s\n' "$name" "$url"
    clip+=("$url")
done <<< "$geturls"

if [[ "$DISPLAY" ]] && (( ${#clip[@]} )); then
    echo -n "${clip[*]}" | xsel -i -b
fi
