#!/usr/bin/env bash

set -x

case $1 in
on)
	sudo swapoff -a
	mkdir -p -m 0700 /tmp/thumbs.$UID
	sudo mount --bind /tmp/thumbs.$UID ~/.thumbnails
	;;
off)
	sudo umount ~/.thumbnails
	sudo swapon -a
	;;
esac
