#!/usr/bin/env bash

. lib.bash || exit

case $1 in
on)
	(set -x
	sudo swapoff -a
	mkdir -p -m 0700 /tmp/thumbs.$UID
	sudo mount --bind /tmp/thumbs.$UID ~/.thumbnails)
	;;

off)
	(set -x
	sudo umount ~/.thumbnails
	sudo swapon -a)
	;;
*)
	die "unknown command '$1'"
	;;
esac
