#!/usr/bin/env bash

https://ptpb.pw/
# vim: ts=4:sw=4:et

. lib.bash || exit
. libkitchensink.bash || exit

usage() {
    echo "Usage: $progname [-p site] <file>..."
    echo ""
    echo "  -p site       select hosting site"
    echo ""
    #echo "Sites:"
    #local _s; for _s in ${!site_bases[@]}; do
    #    printf "  %s (%s)\n" "$_s" "${site_bases[$_s]}"
    #done | sort
}

have curl  || err "missing 'curl'"
have jshon || err "missing 'jshon'"

# parse command line

while getopts ":" OPT; do
    case $OPT in
    *) lib::die_getopts;;
    esac
done; shift $((OPTIND-1))

(( $# )) || die "nothing to upload"
