#!/usr/bin/env bash
# wrapper for 'qemu-system-*' choosing the apropriate architecture and KVM flag

: ${arch:=`uname -m`}

case $arch in
    i?86|x86_64)
	kvm='-enable-kvm';;
    *)
	kvm='';;
esac

xargs=()

for arg; do
	case $arg in
	    -no-kvm)
		kvm='';;
	    *)
		xargs+=("$arg");;
	esac
done

args=(
	qemu-system-$arch
	$kvm
	-monitor "stdio"
	-ctrl-grab
	-net "nic,model=pcnet"
	-net "vde"
	"${xargs[@]}"
)

exec "${args[@]}"
