#!/usr/bin/env bash
# rcons -- attach to a host's local console over network

host=${1?hostname missing}

case $host in
	ember|wind|dune)
		echo "${0##*/}: using IPMI Serial-over-LAN"
		rconsole $host;;
	wolke)
		echo "${0##*/}: using Linode Lish"
		wolke-console;;
	sky)
		echo "Go to: https://cloud.hosthatch.com/servers/25904/console"
		exit 1;;
	star)
		echo "Go to: https://klientams.iv.lt/server.php?id=658792"
		exit 1;;
	cisco-*)
		# TODO: Expand to individual cases and make -C call rcons,
		# instead of the other way around.
		echo "${0##*/}: using whatever"
		cisco ${host#cisco-} -C;;
	gw-core|uk-gw)
		echo "${0##*/}: using IPMI Serial-over-LAN"
		gw-core-console;;
	*)
		echo "${0##*/}: unknown host: $host" >&2
		exit 1;;
esac
