#!/usr/bin/env bash
# rcons -- attach to a host's local console over network

do:() { (PS4="+ "; set -x; "$@"); }

case ${0##*/} in
	*-console)
		host=${0##*/}; host=${host%-console};;
	*)
		host=${1?missing hostname}; shift;;
esac

case $host in
	ember|wind|dune)
		rconsole $host;;
	wolke)
		do: ssh -t lish-london.linode.com $host;;
	sky)
		echo "Go to: https://cloud.hosthatch.com/servers/25904/console";;
	star)
		echo "Go to: https://klientams.iv.lt/server.php?id=658792";;
	land)
		echo "Go to: https://web7.php-friends.de/";;
	vm-ampere)
		test -e ~/.oci/config && ! test -e ~/.oci/sessions/DEFAULT/token ||
		do: oci session refresh ||
		do: oci session authenticate --region eu-frankfurt-1 --profile-name DEFAULT &&
		do: oci-console fra-ampere-1;;
	cisco-top)
		echo "Use &# to break, &. to detach."
		ssh -t alter "doas cu -E '&' -l /dev/ttyU0";;
	cisco-mid)
		echo "Use Ctrl-] 'send brk' to break."
		telnet cisco-top 2005;;
	cisco-btm)
		echo "Use Ctrl-] 'send brk' to break."
		telnet cisco-mid 2005;;
	uk-gw|gw-core)
		gw-core-console;;
	uk-lnx1)
		echo "Using serial console via AP-M7-14."
		do: ssh cons@10.34.1.14;;
	uk-lnx2)
		do: rconsole ${host/#uk-/bmc-}.utenos-kolegija.lt;;
	*)
		echo "${0##*/}: unknown host: $host" >&2
		exit 1;;
esac
