#!/usr/bin/env bash
# rconsole -- attach to a server's remote console via IPMI SOL

. lib.bash || exit

case ${0##*/} in
	*-console)
		host=${0##*/}; host=${host%-console};;
	*)
		host=${1?missing hostname}; shift;;
esac

bhost="bmc.$host.nullroute.lt"

creds=$(getnetrc -sdf %a:%u:%p "ipmi/$bhost" ||
        getnetrc -sdf %a:%u:%p "ipmi/*")
priv=${creds%%:*}; creds=${creds#*:}
user=${creds%%:*}; creds=${creds#*:}
pass=$creds
if [[ ! $user || ! $pass ]]; then
	die "Credentials for 'ipmi/$bhost' not found in ~/.netrc"
fi
if [[ ! $priv ]]; then
	# Guess privilege level from username (e.g. Operator => priv OPERATOR)
	priv=${user^^}
fi

# New ipmitool defaults to ciphersuite 17 (AES-CBC-128 with HMAC-SHA256), which
# iLO4 does not support. Fall back to the HMAC-SHA1 variant.
cipher=3

# iLO4 does not support setting a custom key, but keep it around
k_g=$(getnetrc -sdf %p "rmcp/$bhost" ||
      getnetrc -sdf %p "rmcp/*")

if have ipmipower && have ipmiconsole; then
	# FreeIPMI
	args=(-h "$bhost" -u "$user" -p "$pass" -l "$priv" -I "$cipher" -k "$k_g")

	bmc_console() { ipmiconsole "${args[@]}"; }
	bmc_get_power() { ipmipower -D LAN_2_0 "${args[@]}" --stat; }
	bmc_set_power() { ipmipower -D LAN_2_0 "${args[@]}" --${1?}; }
elif have ipmitool; then
	# ipmitool
	args=(-H "$bhost" -U "$user" -P "$pass" -L "$priv" -C "$cipher" -k "$k_g")
	# TODO: use -E -K for ipmitool
	#IPMI_PASSWORD=$pass
	#IPMI_KGKEY=$k_g

	bmc_console() { ipmitool -I lanplus "${args[@]}" sol activate; }
	bmc_get_power() { ipmitool -I lanplus "${args[@]}" power status; }
	bmc_set_power() { ipmitool -I lanplus "${args[@]}" power ${1?}; }
else
	die "no IPMI client tools installed"
fi

if [[ $1 == --@(power|power-status) || $1 == -p ]]; then
	echo "Getting power status from '$bhost'"
	bmc_get_power
elif [[ $1 == --power-@(on|off|cycle|reset) ]]; then
	cmd=${1#--power-}
	confirm "Send 'power $cmd' command to '$bhost'?" || exit
	info "Sending 'power $cmd' command to '$bhost'"
	bmc_set_power "$cmd"
elif [[ ! $1 ]]; then
	info "Connecting to serial console at '$bhost'"
	bmc_console
else
	die "Unrecognized arguments: '$*'"
fi
