#!/usr/bin/env bash

dirs=(.)
opts=()
today=1

if (( today )); then
	opts+=(-daystart)
	opts+=(-mtime -1)
fi

# -mtime x
#   match if mtime is between {x*24 hours ago} and {(x+1)*24 hours ago}
# e.g. -mtime 0
#   match if mtime is between {0 hours ago} and {24 hours ago}
# -mtime -x
#   match if mtime is newer than {(x+1)*24 hours ago}
# e.g. -mtime -1
#   match if mtime is newer than {24 hours ago}

find "${dirs[@]}" -type f "${opts[@]}" | treeify
