#!/usr/bin/env bash

quality=98
infiles=(*.png)
outfiles=()

if [[ $1 =~ ^[0-9]+% ]]; then
	quality=${1%'%'}
	shift
fi

if (( $# )); then
	infiles=("$@")
fi

echo "Recompressing ${#infiles[@]} files at $quality%"

njobs=0
nproc=$(nproc)
ndone=0

for iname in "${infiles[@]}"; do
	printf '[%s/%s done]\r' "$ndone" "${#infiles[@]}"
	while (( njobs >= nproc )); do
		wait -n; (( --njobs )); (( ++ndone ))
		printf '[%s/%s done]\r' "$ndone" "${#infiles[@]}"
	done
	oname=${iname/%.png/.jpg}
	magick convert "$iname" -quality "$quality" "$oname" & (( ++njobs ))
	outfiles+=("$oname")
	printf '[%s/%s done]\r' "$ndone" "${#infiles[@]}"
done
while (( njobs )); do
	wait -n; (( --njobs )); (( ++ndone ))
	printf '[%s/%s done]\r' "$ndone" "${#infiles[@]}"
done
printf '\n'

echo PNG: $(du -hsc "${infiles[@]}" | tail -1)
echo JPEG: $(du -hsc "${outfiles[@]}" | tail -1)
