#!/usr/bin/env bash

. lib.bash || exit

files=(
	/usr/bin/{arping,nmap,paris-traceroute,ping,traceroute}{,6}
	$PREFIX/bin/mtr
)

for file in "${files[@]}"; do
	if test -f "$file" && ! test -L "$file"; then
		do: chown :wheel "$file"
		do: chmod o-x "$file"
		do: setcap 'cap_net_raw=ep' "$file"
	fi
done
