#!/usr/bin/env bash
# rfc -- open an IETF RFC

. lib.bash || exit

if (( ! $# )); then
	vdie "no document specified"
fi

dir=/usr/share/doc/rfc/txt
args=()
for arg; do
	args+=($dir/rfc$arg.txt)
done

vim -p "${args[@]}"
