#!/usr/bin/env bash

. lib.bash || exit

usage() {
	echo "Usage: $progname [-H hosts] [-w] <keyword>..."
	echo
	echo_opt "-H hosts"	"list of hosts to search"
	echo_opt "-w"		"match against entire path"
}

hosts="+myth"
args=""

while getopts ":H:w" OPT; do
	case $OPT in
	H) hosts=${OPTARG//,/ };;
	w) args+=" -$OPT";;
	*) lib:die_getopts;;
	esac
done; shift $((OPTIND-1))

hosts=`rlisthosts "$hosts"` || exit

if (( ! $# )); then
	vdie "query not specified"
fi

for arg; do
	args+=" ${arg@Q}"
done

rdo -q -H "$hosts" "bin/loc $args | sed \"s,^,/net/\$(hostname),\""
