#!/usr/bin/env bash

. lib.bash || exit

usage() {
	echo "Usage: $progname [-H hosts] <keyword>..."
	echo
	echo_opt "-H hosts"	"list of hosts to search"
}

args=""
hosts="+myth"
opt_whole=0

while getopts ":H:w" OPT; do
	case $OPT in
	H) hosts=${OPTARG//,/ };;
	w) opt_whole=1;;
	*) lib:die_getopts;;
	esac
done; shift $((OPTIND-1))

hosts=`rlisthosts "$hosts"` || exit

if (( ! $# )); then
	vdie "query not specified"
fi

if (( opt_whole )); then
	args+=" -w"
fi
for arg; do
	args+=" ${arg@Q}"
done

rdo -q -H "$hosts" "bin/loc $args | sed \"s,^,/net/\$(hostname),\""
