#!/usr/bin/env bash
# romaji -- transliterate Japanese
if [ ! "$*" ]; then
	echo "romaji: no text" >&2
	exit 1
fi

uvx --quiet --from pykakasi kakasi -Ja -Ha -Ka <<< "$*"
# Roughly equivalent to pykakasi.kakasi().convert(arg)
