#!/bin/sh

for id in `wmctrl -lx | awk '$3 ~ /\.jagexappletviewer$/ {print $1}'`; do
	xprop -f _GTK_THEME_VARIANT 8u \
	    -set _GTK_THEME_VARIANT dark \
	    -id "$id"
	xprop -f _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED 8c \
	    -set _GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED 1 \
	    -id "$id"
done
