#!/bin/sh
user=admin
pass=mxfpq
ip=192.168.57.1
{ 
    echo $user;
    echo $pass;
    sleep .2;
    echo sh;
    sleep .2;
    echo $*;
    sleep .6;
} | telnet $ip 2> /dev/null | sed -n '/^#/,${/^# $/,$d;p}'
