#!/usr/bin/env bash
# rup -- collect uptime information from multiple hosts
#
# Inspired by the RPC-based 'rup' from SunOS 4 manual.

. lib.bash || exit

usage() {
	echo "Usage: $progname [-H HOSTS] [-S] [-d|-m]"
	echo
	echo_opt "-H HOSTS"	"list of hosts to query"
	echo_opt "-S"		"connect as superuser (root)"
	echo_opt "-d"		"query disk space on '/'"
	echo_opt "-m"		"query memory usage"
}

hosts=
user=
what=

while getopts ":H:Sdm" OPT; do
	case $OPT in
	H) hosts=${OPTARG//,/ };;
	S) user=root@;;
	d) what=disk;;
	m) what=mem;;
	*) lib:die_getopts;;
	esac
done; shift $((OPTIND-1))

if (( $# )); then
	die "Unrecognized arguments '$*'"
fi

hosts=$(rlisthosts "$hosts") || exit

columns='HOST,KERNEL,UPTIME,BUILD,LOADAVG,MEMUSE,MFREE,MTOTAL,DUSE,DFREE,DTOTAL'

show='HOST,'
case $what in
"disk") show+='DUSE,DFREE,DTOTAL,';;
"mem") show+='MEMUSE,MFREE,MTOTAL,';;
"") show+='KERNEL,UPTIME,LOADAVG,MFREE,DFREE,';;
esac

hide=",$columns,"
while [[ ${show%,} ]]; do
	hide=${hide/,${show%%,*},/,}
	show=${show#*,}
done
hide=${hide#,}
hide=${hide%,}

(for host in $hosts; do
	ssh $user$host 'printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
			"$(hostname)" \
			"$(uname -r)" \
			"$(uptime -p | sed "s/^up //; s/,.*//")" \
			"$(uname -v | sed "s/.*/[&]/")" \
			"$(uptime | sed "s/.*load average: //")" \
			"$(free -b | awk "/^Mem:/{printf \"%.0f%%\", \$3*100/\$2}")" \
			"$(free -b | awk "/^Mem:/{print \$7}" | numfmt --to=iec)" \
			"$(free -b | awk "/^Mem:/{print \$2}" | numfmt --to=iec)" \
			"$(df -h / | awk "NR==2{print \$5}")" \
			"$(df -h / | awk "NR==2{print \$4}")" \
			"$(df -h / | awk "NR==2{print \$2}")" \
			' &
done
wait) |
sort -V -k 2,1 |
column -s $'\t' \
	--table \
	--table-columns "$columns" \
	--table-hide "$hide" \
	--table-right "MEMUSE,MFREE,MTOTAL,DUSE,DFREE,DTOTAL"
