#!/usr/bin/env bash

RTMIN=$(kill -l SIGRTMIN)

: ${PID:=1}

signal() {
	local sig=$1
	echo "send signal $sig ($(kill -l $sig)) to pid $PID"
	kill -$sig $PID
}

case $1 in
ctrl-alt-del)			signal INT;;
daemon-reexec)			signal TERM;;
daemon-reload)			signal HUP;;
reconnect-dbus)			signal USR1;;
sak)				signal WINCH;;
default)			signal $((RTMIN+0));;
rescue)				signal $((RTMIN+1));;
emergency)			signal $((RTMIN+2));;
halt)				signal $((RTMIN+3));;
poweroff)			signal $((RTMIN+4));;
reboot)				signal $((RTMIN+5));;
kexec)				signal $((RTMIN+6));;
force-halt)			signal $((RTMIN+13));;
force-poweroff)			signal $((RTMIN+14));;
force-reboot)			signal $((RTMIN+15));;
force-kexec)			signal $((RTMIN+16));;
show_status=1)			signal $((RTMIN+20));;
show_status=0)			signal $((RTMIN+21));;
log_level=debug)		signal $((RTMIN+22));;
log_level=info)			signal $((RTMIN+23));;
log_target=journal-or-kmsg)	signal $((RTMIN+26));;
log_target=console)		signal $((RTMIN+27));;
log_target=kmsg)		signal $((RTMIN+28));;
log_target=syslog-or-kmsg)	signal $((RTMIN+29));;
*)				sed -rn 's/^([^)]+)\)\s+signal.*;;$/\1/p' "$0";;
esac
