#!/usr/bin/env bash

. lib.bash || exit

only_uri=0

while getopts ":n" OPT; do
	case $OPT in
	n) only_uri=1;;
	*) lib::die_getopts;;
	esac
done; shift $((OPTIND-1))

project=$1
type=${2:-cvs}

[[ $project ]] || die "missing project name"

mode=rsync
case $type in
	# https://sourceforge.net/p/forge/documentation/File%20Management/
	files|frs)
		url="frs.sourceforge.net:/home/frs/project/$project/" ;;
	userweb)
		url="frs.sourceforge.net:/home/user-web/$project/" ;;
	projectweb)
		url="frs.sourceforge.net:/home/project-web/$project/" ;;
	cvs)
		url="rsync://$project.cvs.sourceforge.net/cvsroot/$project/" ;;
	oldsvn)
		url="rsync://$project.svn.sourceforge.net/svn/$project/" ;;
	svn|git|hg)
		url="rsync://$type.code.sf.net/p/$project/" ;;
	*)
		die "unknown type '$type'" ;;
esac

if (( only_uri )); then
	echo "$url"
else
	dir="$project.$type/"
	info "syncing '$url' to '$dir'"
	rsync -vshzaHAX "$url" "$dir"
	echo "$url" > "$dir/_source"
fi
