#!/usr/bin/env bash

. lib.bash || exit

host=$1; shift

if ! ssh "$host" -O check; then
	ssh "$host" -fNM
fi

for port; do
	rhost=localhost
	case $port in
	    *:*) lport=${port%:*} rport=${port#*:};;
	    *)   lport=$port rport=$port;;
	esac
	log "forwarding :$lport via ssh to $rhost:$rport"
	ssh "$host" -O forward -L "$lport:$rhost:$rport"
done
