#!/usr/bin/env bash
# shoreplug -- remotely power-cycle Shore's smart power socket
export TAPO_USER=$(ad gp =Tapo :email)
export TAPO_PASS=$(ad gp =Tapo !pass)
~/src/projects/perl-tapo/tapo ${0##*/}.sym "$@"
