#!/usr/bin/env python3
# show-fm - Reveal specified items in a file manager window
import dbus
import os
import sys

urls = ["file://%s" % os.path.abspath(p) for p in sys.argv[1:]]
if not urls:
    print("Usage: %s PATH..." % sys.argv[0], file=sys.stderr)
    exit(2)

bus = dbus.SessionBus()
fm = dbus.Interface(bus.get_object("org.freedesktop.FileManager1",
                                   "/org/freedesktop/FileManager1"),
                    "org.freedesktop.FileManager1")
fm.ShowItems(urls, "")
