#!/usr/bin/env bash

. lib.bash || exit

if ! which signtool > /devnull 2>&1; then
	die "You need the 'signtool' command from the NSS library."
fi

if ! which zip > /dev/null 2>&1; then
	die "You need the 'zip' command."
fi

if ! [ -f install.rdf ]; then
	die "This directory does not contain a valid XPI extension."
fi

nssdb="sql:$HOME/.pki/nssdb"
nsscert='grawity - code signing'

outfile="${1:-${PWD##*/}}.xpi"

(shopt -s nullglob; rm -f *.xpi)

signtool -d "$nssdb" -k "$cert" -Z "outfile" .

log "Created $outfile"
