#!/usr/bin/env bash
# convenience wrapper for signing Linux kernel modules

. lib.bash || exit

src=~/src/linux

cert=$src/signing_key.x509
key=$src/signing_key.priv

hash=$(cd "$src" && . ./.config && echo ${CONFIG_MODULE_SIG_HASH:-sha1})

[[ -e "$cert" ]] || die "certificate not found: $cert"
[[ -e "$key" ]]  || die "private key not found: $key"

for file; do
	echo -n "${file##*/}: "
	if grep -qs "~Module signature appended~" "$file"; then
		echo "already signed"
	else
		if (( UID == 0 )); then
			need_root=
		elif ! [[ -w "$file" && -w "${file%/*}" ]]; then
			need_root=y
		fi

		echo "signing"
		${need_root:+sudo} "$src/scripts/sign-file" "$hash" "$key" "$cert" "$file"
	fi
done
