#!/usr/bin/env bash
# convenience wrapper for signing Linux kernel modules

. lib.bash || exit

src=~/src/linux

cert=$(cd "$src" && readlink -f "signing_key.x509")
key=$(cd "$src" && . ./.config && echo ${CONFIG_MODULE_SIG_KEY})
hash=$(cd "$src" && . ./.config && echo ${CONFIG_MODULE_SIG_HASH:-sha1})

if ! [[ -s "$cert" ]]; then
	die "certificate '$cert' not found"
fi
if ! [[ -s "$key" || "$key" == pkcs11:* ]]; then
	die "private key '$key' not found"
fi

for file; do
	echo -n "${file##*/}: "
	if grep -Fqs "~Module signature appended~" "$file"; then
		echo "already signed"
	else
		if (( UID == 0 )); then
			need_root=
		elif ! [[ -w "$file" && -w "${file%/*}" ]]; then
			need_root=y
		fi

		echo "signing"
		${need_root:+sudo} "$src/scripts/sign-file" "$hash" "$key" "$cert" "$file"
	fi
done
