#!/usr/bin/env bash

. lib.bash || exit

have signtool  || err "missing 'signtool' tool from NSS"
have zip       || err "missing 'zip' tool"
(( ! errors )) || exit

nssdb="sql:$HOME/.pki/nssdb"
cert='grawity - code signing'

while getopts ":c:d:" OPT; do
	case $OPT in
	c) cert=$OPTARG;;
	d) nssdb=$OPTARG;;
	*) die_getopts;;
	esac
done; shift $((OPTIND-1))

if ! [[ -f install.rdf ]]; then
	die "directory does not contain a valid Mozilla extension"
fi

outfile="${1:-${PWD##*/}}.xpi"

(shopt -s nullglob; rm -f *.xpi)

log "signing current directory with \"$cert\""

signtool -d "$nssdb" -k "$cert" -Z "outfile" .

log "created \"$outfile\""
