#!/bin/sh

C=~/.wine/drive_c

#wine "$C/Program Files (x86)/Electronic Arts/The Sims 3/Game/Bin/TS3.exe"

EPs=(
	[TS3]='The Sims 3'
	[TS3EP01]='The Sims 3 World Adventures'
)

EP='TS3EP01'

wine "$C/Program Files (x86)/Electronic Arts/${EPs[$EP]}/Game/Bin/${EP}.exe"
