#!/usr/bin/env perl
use warnings;
use strict;
use Data::Dumper;
use File::stat;
use List::Util qw(pairs);
use List::MoreUtils qw(zip);

my @a;
my @b;
my $cur;

for (@ARGV) {
	if (!$cur) {
		$cur = \@a;
	}
	if (/^--vs$/) {
		$cur = \@b;
	}
	else {
		push @$cur, $_;
	}
}

for (pairs zip @a, @b) {
	my ($a, $b) = @$_;
	next if !$a || !$b;
	#print "-- $a\n";
	#print "++ $b\n";
	my $sa = stat($a)->size;
	my $sb = stat($b)->size;
	my $pa = 100 - $sa / $sb * 100;
	my $pb = 100 - $sb / $sa * 100;
	my $side;
	if ($sa < $sb) {
		printf "first file is smaller by %.0f%%\n", $pa;
	}
	elsif ($sa > $sb) {
		printf "second file is smaller by %.0f%%\n", $pb;
	}
	else {
		printf "both files are equal\n";
	}
}
