#!/usr/bin/env bash
# sl-fake-vram -- fix Xorg.log to make SecondLife find the right amount of VRAM

if [[ $DISPLAY == :* ]]; then
	disp=${DISPLAY#:}
	disp=${disp%%.*}
else
	disp=0
fi

MB=$1
if [[ ! $MB ]]; then
	MB=$(glxinfo | awk '/Video memory:/ {print $3}' | sed 's/MB//')
	echo "detected ${MB} MB of VRAM"
fi
KB=$(( MB * 1024 ))
echo "pretending we have ${KB} kB of VRAM"
echo "fake: Memory: ${KB} kB" \
  | sudo sh -c "dd of='/var/log/Xorg.$disp.log' conv=notrunc &> /dev/null"
