#!/bin/bash
in=$1
comment=$2

if grep -qs "BEGIN OPENSSH PRIVATE KEY" "$in"; then
	puttygen "$in" -C "$comment" -O private-openssh-new
else
	cp -a "$in" "$in.tmp"
	puttygen "$in.tmp" -C "$comment" -o "$in" -O private-openssh-new
fi
