#!/usr/bin/env bash
# convert a ssh:// URI to `ssh` args

. lib.bash || exit

case $1 in
    ssh:*)
	uri=$1
	uri=${uri#'ssh:'}
	uri=${uri#'//'}
	uri=${uri%'/'}
	settitle "ssh – $uri"
	exec ssh "$uri"
	;;
    *)
	die "not a 'ssh:' URI"
	exit 1
	;;
esac
