#!/usr/bin/env bash

. lib.bash || exit

prefix="$HOME/.ssh/S.$HOSTNAME."

do_list() {
	printf '%-40s%s\n' "SERVER NAME" "STATUS"

	for socket in "$prefix"*; do
		if ! test -e "$socket"; then
			continue
		fi
		addr="${socket#$prefix}"
		user="${addr%@*}"
		host="${addr##@*}"
		port="${host##*:}"
		host="${host%:*}"
		if ! status=$(ssh "$host" -l "$user" -p "$port" -O check 2>&1); then
			status="${status/#Control socket connect(*): /Control socket: }"
		fi
		printf '%-40s%s\n' "$addr" "$status"
	done
}

do_kill() {
	for socket in "$prefix"*; do
		test -S "$socket" || continue
		echo "${socket##*/}"
		ssh -S "$socket" fakehost -O stop || rm -v "$socket"
	done
}

case $1 in
-k) do_kill;;
'') do_list;;
*)  die "unknown option '$1'";;
esac
