#!/usr/bin/env bash

. lib.bash || exit

app=$1
[[ $app ]] || die "usage: $progname <app> ..."

case $app in
mpop|msmtp)
	host=$2 user=$3
	[[ $host && $user ]] || die "usage: $progname $app <host> <user>"

	case $app in
		msmtp) proto=smtp;;
		mpop) proto=pop3;;
	esac
	label="$app: $host"
	schema="de.marlam.$app.password"
	attrs=(
		host "$host"
		service "$proto"
		user "$user"
	)

	secret-tool store --label="$label" xdg:schema "$schema" "${attrs[@]}"
	;;
*)
	die "unknown app '$app'"
	;;
esac
