#!/usr/bin/env bash
# symgit -- manage self-hosted Git repositories

. lib.bash || exit

host=star
fsroot='/srv/git'
urlprefix=':'

argtorepo() {
	local arg=$1
	if [[ $arg == . ]]; then
		arg=$(git config remote.origin.url)
	fi
	case $arg in *://*|?*:*)
		vdie "not a symgit repo: $arg"
	esac
	arg=${arg#$urlprefix}
	case $arg in [!a-z]*|"")
		vdie "bad repository name: $arg"
	esac
	arg=${arg%.git}
	echo "$arg"
}

repodir() {
	local repo=$1
	case $repo in [!a-z]*|*.git)
		lib:crash "repo should have been canonicalized: $repo"
	esac
	echo "$fsroot/$repo.git"
}

repourl() {
	local repo=$1
	case $repo in [!a-z]*|*.git)
		lib:crash "repo should have been canonicalized: $repo"
	esac
	echo "$urlprefix$repo"
}

flushconf() {
	vmsg "flushing cgit config"
	ssh $host "sudo find /var/cache/cgit -name 'rc-*' -delete"
}

flushall() {
	vmsg "flushing cgit cache"
	ssh $host "sudo find /var/cache/cgit -type f -delete"
}

vusage() {
	local argc=$1 min=$2 max=$3 text=$4
	if (( max >= 0 && argc > max )); then
		vdie "excess arguments"
	elif (( argc < min )); then
		vdie "usage: $progname $text" >&2
	fi
}

klist -s || kinit || die "no Kerberos credentials"

cmd=$1; shift

set -u
set -e

case ${cmd:-help} in
	help)
		vusage $# 0 0 "$cmd"
		echo "Commands:"
		echo "  ls|list"
		echo "  new <repo>..."
		echo "  mv|rename <old_repo> <new_repo>"
		echo "  desc|describe <repo> [<description>]"
		echo "  exp|export <repo>..."
		echo "  unexp|unexport <repo>..."
		echo "  mirror <repo> <upstream>"
		echo "  unmirror <repo>"
		echo "  web <repo>..."
		echo "  cgit-flush"
		;;
	ls|list)
		vusage $# 0 0 "$cmd"
		ssh $host "find '$fsroot/' -type d -name '*.git' -printf '%P\n' -prune" \
			| sort \
			| sed "s|^|$urlprefix|; s|\\.git\$||"
		;;
	new)
		vusage $# 1 1 "$cmd <repo> [<description>]"
		arg=$1 newdesc=${2-}
		repo=$(argtorepo "$arg")
		dir=$(repodir "$repo")
		url=$(repourl "$repo")
		if ssh $host "test -d ${dir@Q}"; then
			vdie "repository already exists: $dir"
		fi
		vmsg "creating repository $dir"
		ssh $host "git init --bare ${dir@Q}"
		ssh $host "chmod go-rx ${dir@Q}"
		if [[ $newdesc ]]; then
			ssh $host "echo ${newdesc@Q} > ${dir@Q}/description"
		fi
		flushconf
		if git rev-parse --git-dir &> /dev/null; then
			if [[ "$(git remote)" == "" ]]; then
				vmsg "adding repository as git remote"
				git remote add origin "$url"
			fi
		fi
		;;
	mv|move|rename)
		vusage $# 2 2 "$cmd <old> <new>"
		old=$1
		new=$2
		oldrepo=$(argtorepo "$old")
		newrepo=$(argtorepo "$new")
		olddir=$(repodir "$oldrepo")
		newdir=$(repodir "$newrepo")
		oldurl=$urlprefix$oldrepo
		newurl=$urlprefix$newrepo
		if ! ssh $host "test -d ${olddir@Q}"; then
			err "Source repository '$oldurl' does not exist"
		elif ssh $host "test -d ${newdir@Q}"; then
			err "Target repository '$newurl' already exists"
		else
			info "Renaming repository '$oldurl' => '$newurl'"
			ssh $host "mv -Tvn ${olddir@Q} ${newdir@Q}"
		fi
		flushconf
		;;
	head)
		vusage $# 1 2 "$cmd <repo> [<head>]"
		arg=$1 newhead=${2-}
		repo=$(argtorepo "$arg")
		dir=$(repodir "$repo")
		if [[ $newhead ]]; then
			newhead=refs/heads/${newhead#refs/heads/}
			info "Setting default branch for '$repo' to '$newhead'"
			ssh $host "git -C ${dir@Q} symbolic-ref HEAD ${newhead@Q}"
		else
			ssh $host "git -C ${dir@Q} symbolic-ref HEAD"
		fi
		;;
	desc|describe)
		vusage $# 1 2 "$cmd <repo> [<description>]"
		if (( $# == 1 )) && [[ $1 == *\ * ]]; then
			arg=. newdesc=$1
		else
			arg=$1 newdesc=${2-}
		fi
		repo=$(argtorepo "$arg")
		dir=$(repodir "$repo")
		if [[ $newdesc ]]; then
			info "Setting description for '$repo' to \"$newdesc\""
			ssh $host "echo ${newdesc@Q} > ${dir@Q}/description"
		else
			if ! ssh $host "test -s ${dir@Q}/description"; then
				info "Repository '$repo' has no description"
			else
				ssh $host "cat ${dir@Q}/description"
			fi
		fi
		;;
	mirror)
		vusage $# 2 2 "$cmd <repo> <upstream>"
		arg=$1 upstream=$2
		repo=$(argtorepo "$arg")
		dir=$(repodir "$repo")
		# Set up parameters for the hourly re-fetch cronjob, which looks for
		# repositories with a remote that have [Mirror] in their description.
		ssh $host "git -C ${dir@Q} remote remove origin &>/dev/null || true"
		ssh $host "git -C ${dir@Q} remote add --mirror=fetch origin ${upstream@Q}"
		ssh $host "git -C ${dir@Q} fetch origin"
		info "Added remote 'origin' from '$upstream'"
		if ssh $host "test -s ${dir@Q}/description"; then
			desc=$(ssh $host "cat ${dir@Q}/description")
			desc=$(echo "$desc" | sed 's/^Mirror of [^ ]*$//')
			desc=$(echo "$desc" | sed 's/^\[Mirror of [^ ]*\] //')
			desc="[Mirror of $upstream] $desc"
		else
			desc="Mirror of $upstream"
		fi
		ssh $host "echo ${desc@Q} > ${dir@Q}/description"
		;;
	unmirror)
		vusage $# 1 1 "$cmd <repo>"
		arg=$1
		repo=$(argtorepo "$arg")
		dir=$(repodir "$repo")
		ssh $host "git -C ${dir@Q} remote remove origin &>/dev/null || true"
		info "Removed remote 'origin'"
		if ssh $host "test -s ${dir@Q}/description"; then
			desc=$(ssh $host "cat ${dir@Q}/description")
			desc=$(echo "$desc" | sed 's/^Mirror of [^ ]*$//')
			desc=$(echo "$desc" | sed 's/^\[Mirror of [^ ]*\] //')
		else
			desc=""
		fi
		ssh $host "echo ${desc@Q} > ${dir@Q}/description"
		;;
	pub|publish|exp|export)
		vusage $# 1 -1 "$cmd <repo>..."
		for arg; do
			repo=$(argtorepo "$arg")
			dir=$(repodir "$repo")
			url=$(repourl "$repo")
			# Make world-readable and create the 'export-ok' flag
			# that both Cgit and git-daemon look for.
			if ! ssh $host "test -d ${dir@Q}"; then
				err "Repository '$url' does not exist"
				continue
			elif ssh $host "test -f ${dir@Q}/git-daemon-export-ok"; then
				info "Repository '$url' already public"
				continue
			fi
			if ! ssh $host "test -s ${dir@Q}/description"; then
				warn "Repository '$url' has no description, use '$progname desc'"
			fi
			info "Publishing repository '$url'"
			ssh $host "touch ${dir@Q}/git-daemon-export-ok"
			ssh $host "chmod a+rx ${dir@Q}"
		done
		;;
	unpub|unpublish|unexp|unexport)
		vusage $# 1 -1 "$cmd <repo>..."
		for arg; do
			repo=$(argtorepo "$arg")
			dir=$(repodir "$repo")
			url=$(repourl "$repo")
			if ! ssh $host "test -d ${dir@Q}"; then
				err "Repository '$url' does not exist"
				continue
			fi
			info "Unpublishing repository '$url'"
			ssh $host "rm -f ${dir@Q}/git-daemon-export-ok"
			ssh $host "chmod go-rx ${dir@Q}"
		done
		;;
	web)
		vusage $# 1 -1 "$cmd <repo>..."
		for arg; do
			repo=$(argtorepo "$arg")
			url="https://git.nullroute.lt/cgit/$repo.git/"
			echo "$repo => $url"
		done
		;;
	flush)
		vusage $# 0 0 "$cmd"
		flushall
		;;
	*)
		vdie "bad command: $cmd"
		;;
esac

((!errors))
