#!/usr/bin/env bash
# wrap the relevant service control commands

have() { command -v "$1" >& /dev/null; }

if [ -d /run/systemd/system ]; then
	init=systemd
else
	die "unknown init system '$init'"
fi

cmd=$1; shift

case $init in
    systemd)
	case $cmd in
	    enable|disable|start|stop|status)
		systemctl $cmd "$@";;
	esac;;
    debian)
	case $cmd in
	    start|stop)
		for sv; { service "$sv" $cmd; };;
	    enable|disable)
		for sv; { update-rc.d "$sv" $cmd; };;
	esac;;
    upstart)
	case $cmd in
	    start|stop)
		for sv; { $cmd "$sv"; };;
	esac;;
    *)
	die "unknown init system '$init'";;
esac
