#!/bin/sh

exec >&2

if [ ! "$MAINPID" ]; then
	echo "error: script must be run by systemd"
	exit 2
fi

if [ ! "$HOME" ] || [ ! "$XDG_RUNTIME_DIR" ]; then
	echo "error: missing required environment variables"
	exit 1
fi

envfile="$HOME/.ssh/agent-rain"
newsock="$XDG_RUNTIME_DIR/ssh-agent"
newpid="$MAINPID"

if [ -s "$envfile" ]; then
	unset SSH_AUTH_SOCK SSH_AGENT_PID

	. "$envfile" > /dev/null

	if [ -S "$SSH_AUTH_SOCK" ] && [ -e "/proc/$SSH_AGENT_PID" ]; then
		echo "another agent running at $SSH_AUTH_SOCK ($SSH_AGENT_PID)"
		exit 0
	fi
fi

rm -f "$envfile"-*

{
echo "SSH_AUTH_SOCK=$newsock; export SSH_AUTH_SOCK;"
echo "SSH_AGENT_PID=$newpid; export SSH_AGENT_PID;"
echo "echo Agent pid $newpid;"
} > "$envfile"-systemd

chmod a-w "$envfile"-systemd

ln -f "$envfile"-systemd "$envfile"
