#!/usr/bin/env bash
# sysup -- upgrade all installed packages

. lib.bash || exit

~/bin/settitle -w "$(hostname)"

tool=$(osguess package-mgr) || exit

case $tool in
	dpkg)
		if [[ -x /usr/bin/apt ]]; then
			sudo: nice apt update &&
			sudo: nice apt full-upgrade -V "$@"
		else
			sudo: nice apt-get update &&
			sudo: nice apt-get dist-upgrade -V "$@"
		fi
		;;
	pacman)
		sudo: nice pacman -Syu "$@" &&
		if pkgs=$(pacman -Qqdt | grep ^haskell-); then
			sudo: nice pacman -Rns --noconfirm $pkgs
		fi
		;;
	rpm)
		sudo: nice yum update "$@"
		;;
	*)
		echo "${0##*/}: unknown distribution" >&2
		exit 1
		;;
esac
