#!/usr/bin/env bash

. lib.bash || exit

while (( $# )); do
	url="$1"; shift
	debug "url: $url"

	if [[ $1 && $1 != */* ]]; then
		basename="$1"; shift
		debug "basename overridden: $basename"
	else
		basename="${url##*/}"
		debug "basename copied: $basename"
	fi

	prefix="${basename%.*} – "
	if [[ $basename == *.* ]]; then
		suffix="${basename##*.}"
	else
		suffix="foo"
	fi
	date=$(date +"%Y-%m-%d")
	
	for (( count=0; count < 999; count++ )); do
		printf -v name "%s%s.%03d.%s" "$prefix" "$date" "$count" "$suffix"
		debug "trying name: '$name'"
		if ! [[ -e $name || -e .$name.tmp ]]; then
			wget --no-check-certificate "$url" -O "$name"
			fattr "$name" "origin=$url"
			continue 2
		fi
	done

	err "could not find a free filename for '$name'"
done

(( ! errors ))
