#!/usr/bin/env bash

while (( $# )); do
	url="$1"; shift
	if [[ $1 && $1 != */* ]]; then
		basename="$1"; shift
	else
		basename="${url##*/}"
	fi
	prefix="${basename%.*} – "
	suffix="${url##*.}"
	date=$(date +"%Y-%m-%d")
	
	for (( count=0; count < 999; count++ )); do
		printf -v name "%s%s.%03d.%s" "$prefix" "$date" "$count" "$suffix"
		if ! [[ -e $name || -e .$name.tmp ]]; then
			wget "$url" -O "$name"
			fattr "$name" "origin=$url"
			break
		fi
	done
done
