#!/usr/bin/env bash
# tarball - archive away a directory

. lib.bash || exit

case ${0##*/} in
    tarball) ext=tgz;;
    zipball) ext=zip;;
esac

do_archive() {
	local dir=$1 out=$2 attr=$1/_attributes

	log "dumping extended attributes"
	getfattr -R --dump "$dir" > "$attr"
	test -s "$attr" || rm -f "$attr"

	log "archiving files"
	case $out in
	    *.tgz) tar --xattrs -cvzf "$out" "$dir";;
	    *.zip) zip -r "$out" "$dir";;
	esac
}

dir=${1%/}

if [[ $2 == --now ]]; then
	out=$dir-$(date +%F).$ext
elif [[ $2 == --date ]]; then
	out=$dir-$(find "$dir" -printf '%TF\n' | sort -u | tail -1).$ext
else
	out=${2:-$dir}.$ext
fi

for file in "${1%/}".{{t,tar.}{gz,bz2,xz},zip}; do
	if [[ -e "$file" ]]; then
		die "archive already exists: $file"
	fi
done

log2 "creating archive \"$out\""

if do_archive "$dir" "$out"; then
	chmod a-w "$out"
	log "archived to \"$out\""
	ls -lh "$out"
	log "removing original"
	rm -rf "$dir/"
	log "original directory removed"
else
	die "archiving failed"
fi
