#!/usr/bin/env bash
# toggle-synaptics - Enable or disable the Synaptics touchpad

set -e

oldmode=$(synclient | awk '$1 == "TouchpadOff" {print $3}')

if [[ $oldmode == 1 ]]; then
	newmode=0
	msg="Touchpad on"
	icon='input-touchpad-symbolic'
else
	newmode=1
	msg="Touchpad off"
	icon='touchpad-disabled-symbolic'
fi

synclient "TouchpadOff=$newmode"

echo "$msg"

if dbus-name -eq org.gnome.Shell; then
	gdbus call -e \
		-d org.gnome.Shell \
		-o /org/gnome/Shell \
		-m org.gnome.Shell.ShowOSD \
		"{'icon': <'$icon'>,
		  'label': <'$msg'>}" > /dev/null
else
	notify -i "$icon"	\
		-a "Touchpad"	\
		-s +synaptics	\
		-t 3		\
		-h transient	\
		-- "$msg"	;
		# -h synchronous=touchpad	\
		# not used because notify-osd won't update the title
fi
