#!/usr/bin/env bash
# tweak - change various non-exposed settings

. lib.bash || exit

require() {
	if [[ $font && $font != '-' ]]; then
		case $1 in
		gtk)
			re=' [[:digit:]]+$'
			eg='Cantarell 11'
			[[ $font =~ $re ]];;
		esac || die "bad font spec '$font' (example: '$eg')"
	fi
}

do_gsettings() {
	local schema=$1 key=$2 value=$3 type=${4:-raw}
	if [[ $value == '-' || $value == 'reset' ]]; then
		gsettings reset "$schema" "$key"
	elif [[ $value ]]; then
		case ${type#--} in
		    uri)
			[[ $value == *://* ]] ||
				value="file://$(urlencode -p $(readlink -f "$value"))"
			[[ $value != \'*\' ]] ||
				value="'$value'"
			;;
		    bool)
			case ${value,,} in
			    t*|y*|1|on)  value="true";;
			    f*|n*|0|off) value="false";;
			esac
			;;
		    string)
			[[ $value != \'*\' ]] ||
				value="'$value'"
			;;
		esac
		gsettings set "$schema" "$key" "$value"
	else
		gsettings get "$schema" "$key"
	fi
}

do_dconf() {
	local path=$1 value=$2
	if [[ $value == '-' || $value == 'reset' ]]; then
		dconf reset "$path"
	elif [[ $value ]]; then
		dconf write "$path" "'$value'"
	else
		dconf read "$path"
	fi
}

tweak=$1 value=$2

case $tweak in
attach-dialogs)
	do_gsettings org.gnome.shell.overrides attach-modal-dialogs "$value" --bool
	;;
wallpaper)
	do_gsettings org.gnome.desktop.background picture-uri "$value" --uri
	;;
*)
	die "unknown setting '$tweak'"
	;;
esac
