#!/usr/bin/env bash
# vim: ts=4:sw=4:et

. lib.bash || exit
. libkitchensink.bash || exit

(( $# )) || die "nothing to upload"

clip=()

for f in "$@"; do
    if [[ -e "$f" ]]; then
        curl_args=(-F "file=@$f")
    else
        err "file '$f' not found"
        continue
    fi

    if [[ $DEBUG ]]; then
        curl_args+=(-v)
    fi

    if [[ -t 2 ]] && ks:larger_than "$f" "1 << 18"; then
        curl_args+=(-#)
    else
        curl_args+=(-s)
    fi

    if expire=$(ks:getattr "$f" "uguu.expire"); then
        if (( expire > `now` )); then
            url=$(ks:getattr "$f" "uguu.url")
        fi
    fi

    if [[ ! $url ]]; then
        url=$(curl -S "${curl_args[@]}" "http://uguu.se/api.php?d=upload")
    fi

    echo "$f → $url"
    clip+=("$url")

    ks:setattr "$f" "uguu.expire" "$(( `now` + 3600 ))"
    ks:setattr "$f" "uguu.url" "$url"
done

if [[ "$DISPLAY" ]] && (( ${#clip[@]} )); then
    echo -n "${clip[*]}" | xsel -i -b
fi

(( !errors ))
