#!/usr/bin/env bash

for input; do
	base=${input%.*}
	convert -crop "25%x25%" "$input" +repage "$base".tile%02d.png
	mogrify +repage "$base".tile*.png
	convert -loop 1 -delay 10 "$base".tile*.png "$base".gif
	rm "$base".tile*.png
done
