#!/usr/bin/env perl

sub shquote {
	my ($str) = @_;
	$str =~ s/["\\`\$]/\\$&/g;
	return qq{"$str"};
}

while (<>) {
	if (m{^(.+)/(.+?) => (.+)$}) {
		my $new = shquote("$1/$3");
		my $old = shquote("$1/$2");
		print qq{mv -vn $new $old\n};
	}
	elsif (m{^info: renaming '(.+)' to '(.+)'$}) {
		my $new = shquote($2);
		my $old = shquote($1);
		print qq{mv -vn $new $old\n};
	}
}
