#!/usr/bin/env bash

. lib.bash || exit

fsbase="virgule:up"
urlbase="https://nullroute.eu.org/tmp/$(date +%Y)"

clip+=()

while getopts "d:" OPT; do
	case $OPT in
	'd') subdir=$OPTARG;;
	esac
done; shift $((OPTIND-1))

if [[ $subdir ]]; then
	fsbase+="/$subdir"
	urlbase+="/$subdir"
	ssh "${fsbase%%:*}" "mkdir -p '${fsbase#*:}'"
fi

for arg; do
	if [[ ! -f $arg ]]; then
		err "'$arg' is not a file"
	elif [[ ! -s $arg ]]; then
		warn "'$arg' is empty, skipping"
	else
		name=${arg##*/}
		scp "$arg" "$fsbase/$name"
		echo "$name → $urlbase/$name"
		clip+=("$urlbase/$name")
	fi
done

if [[ "$DISPLAY" ]] && (( ${#clip[@]} )); then
    echo -n "${clip[*]}" | xsel -i -b
fi

(( !errors ))
