#!/usr/bin/env bash

run-term() {
	spawn gnome-terminal -x "$@"
	#spawn xterm -e "$@"
}

die() {
	spawn zenity --error --title "" --text "$*"
	echo "$*" >&2
	exit 1
}

split_authority() {
	if [[ $1 == *:* ]]; then
		domain=${1%:*}
		port=${1##*:}
	else
		domain=$1
		port=
	fi
}

url=$1

scheme=${url%%:*}
hier=${url#*:}

case $scheme in
telnet)
	hier=${hier#//}
	authr=${hier%%/*}
	split_authority "$authr"
	: ${port:=telnet}
	run-term telnet "$domain" "$port"
	;;
esac
