#!/usr/bin/env bash
# vers -- show summary of package versions

. lib.bash || exit

tool=$(osguess package-mgr) || exit

case $tool in
	pacman)
		have expac || vdie "expac is not installed"
		{ expac -Q '%r/%n %v' "$@" || true;
		  expac -S '%r/%n %v' "$@" || true; } | column -t
		;;
	*)
		vdie "unknown distribution"
		;;
esac
