#!/bin/bash

. lib.bash || exit

preview=0
acodec=copy
vcodec=copy

while (( $# )); do
	case ${1#--} in
	end)	end=$2; shift;;
	from)	from=$2; shift;;
	start)	start=$2; shift;;
	to)	to=$2; shift;;
	recode)	vcodec="libx264";;
	acodec)	acodec=$2; shift;;
	vcodec)	vcodec=$2; shift;;
	play)	preview=1;;
	*)	die "unrecognized argument '$1'";;
	esac; shift
done

[[ $from ]]  || die "missing 'from' file"
[[ $to ]]    || die "missing 'to' file"
[[ $start ]] || die "missing 'start' time"
[[ $end ]]   || die "missing 'end' time"

if (( preview )); then
	ffplay -ss "$start" "$from"
	exit
fi

ffmpeg -i "$from" -ss "$start" -to "$end" -codec:a "$acodec" -codec:v "$vcodec" "$to"
