#!/usr/bin/env bash
# web-keyword - keyword searches from the shell

open() {
	local keyword=${1##*/} arg=${*:2}

	case $keyword in
		web-keyword) open "${@:2}"; return;;

		bgo)	url='https://bugzilla.gnome.org/show_bug.cgi?id=%s';;
		fdo)	url='https://bugs.freedesktop.org/show_bug.cgi?id=%s';;
		g|gg)	url='http://www.google.com/search?q=%s';;
		kb)	url='http://support.microsoft.com/kb/%s/';;
		msgid)	url='http://groups.google.com/groups?selm=%s';;
		rfc)	url='https://tools.ietf.org/html/rfc%s';;
		tpb)	url='http://thepiratebay.org/search/%s';;
		w|wp)	url='http://en.wikipedia.org/w/index.php?search=%s';;
		y|yt)	url='http://www.youtube.com/results?search_query=%s';;
	esac

	exec web-browser "$(printf "$url" "$(urlencode "$arg")")"
}

if [[ ! $1 ]]; then
	set -- "$(xclip -o)"
fi

open "$0" "$@"
