#!/usr/bin/env python3
# whatip -- Look up an IP address in the "IP addresses.txt" database
import argparse
import ipaddress
import os
import re
import subprocess

def ipmatch(ip, net):
    if ".x" in net:
        # Transform 10.147.0.x into a regex
        net = net.split("/")[0]
        net = re.escape(net).replace("x", r"[0-9]+")
        if re.fullmatch(net, str(ip)):
            return True
        return False
    if "/" not in net:
        net = ipaddress.ip_address(net)
        if ip == net:
            return True
        return False
    else:
        net = ipaddress.ip_network(net)
        if ip in net:
            return True
        return False

parser = argparse.ArgumentParser()
parser.add_argument("-e", "--edit", action="store_true")
parser.add_argument("address", nargs="*", type=ipaddress.ip_address)
args = parser.parse_args()

path = os.path.expanduser("~/Dropbox/Notes/Nullroute/IP assignments.txt")
if not os.path.exists(path):
    path = "/net/ember/" + path

lineno = 0
with open(path, "r") as fh:
    within = False
    for i, line in enumerate(fh, start=1):
        if line.startswith("Main IPv4 private range"):
            lineno = i
            within = True
        elif line.startswith("Main IPv6 private range"):
            within = False
        elif not within:
            continue
        elif re.match(r"^10\.147\.|^2a06:e881:108:", line.strip()):
            net = line.split()[0]
            desc = line.rstrip()
            if any(ipmatch(a, net) for a in args.address):
                print(desc)
                lineno = i

if args.edit:
    cmd = [os.environ.get("EDITOR", "vi"), path, f"+{lineno}"]
    subprocess.run(cmd)
