#!/usr/bin/env bash
pacman -Si "$@" | while read -r k _ v; do
	case $k in
	'Repository')
		unset ${!k_*}
		k_repo=$v
		;;
	'Name')
		k_name=$v
		;;
	'Version')
		k_version=$v
		echo "$k_repo/$k_name $k_version"
		;;
	esac
done
