#!/usr/bin/env bash

. lib.bash || exit

ssid=$1
psk=$2

[[ $ssid ]] || die "missing Wi-Fi SSID"

[[ $psk ]] || psk=$(getnetrc -dsf %p "wpa/$ssid")
[[ $psk ]] || die "missing WPA PSK"

qrencode -o- -tUTF8 "WIFI:T:WPA;S:$ssid;P:$psk;;"
