#!/usr/bin/env bash

upload() { uguu -q "$1" 2>/dev/null; }

img="$1" &&
echo "Uploading '$img'..." &&
url=$(upload "$img") &&
url="https://saucenao.com/search.php?db=999&url=$(urlencode "$url")" &&
echo "$url" &&
xdg-open "$url" &>/dev/null
