#!/usr/bin/env bash

dev="ETPS/2 Elantech Touchpad"

if (( $# )); then
	prop=

	case $1 in
		AccelSpeed) prop="libinput Accel Speed";;
	esac

	if [[ $prop ]]; then
		set -- "$prop" "${@:2}"
	fi

	exec xinput set-prop "$dev" "$@"
else
	exec xinput list-props "$dev"
fi
