#!/usr/bin/env bash

path=${1:-.}
base=$HOME
rpath=$(realpath --relative-base="$base" "$path")
if [[ $rpath == /* ]]; then
	echo "error: path '$path' is not under '$base'" >&2
	exit 1
fi
echo "$base/.old/latest/$rpath"
