#!/usr/bin/env php
<?php
namespace RWho;
require __DIR__."/config.inc";

function cleanup() {
	$max_age = 3600;

	$db = new \PDO(DB_PATH, DB_USER, DB_PASS)
		or die("error: could not open rwho database\n");
	$rows = $db->exec("DELETE FROM utmp WHERE updated < ".(time()-$max_age));
	if ($rows === false) {
		$err = $db->errorInfo();
		fwrite(STDERR, "error: ".implode("; ", $err)."\n");
	}
	return $rows;
}

if (cleanup() === false)
	exit(1);
