#!/usr/bin/env perl
use IO::Socket::INET;
use MIME::Base64;
use Authen::SASL "XS";

my $host = "localhost";
my $port = 24001;
my $sasl_host = $host;

my $sock = IO::Socket::INET->new(PeerAddr => $host, PeerPort => $port);

sub put {
	my $str = shift;
	print "\e[1;36m-->\e[;36m $str\e[m\n";
	$sock->print("$str\r\n");
}

my $mech = "SCRAM-SHA-1";

put($_) for (
	"CAP REQ :sasl",
	"NICK test",
	"USER a a a a",
	"AUTHENTICATE $mech",
);

my $authzid = shift(@ARGV) // "grawity";

my $sasl = Authen::SASL->new(
			mechanism => "$mech",
			callback => {
				username => sub {$authzid // ""},
				password => sub {$ENV{pass} // "jilles"},
			});
my $conn = $sasl->client_new("irc", $sasl_host);
my $started = 0;

while (<$sock>) {
	s/\r\n$//;
	print "\e[1;35m<--\e[;35m $_\e[m\n";
	if (/^AUTHENTICATE (.+)$/) {
		my $in = $1 eq '+' ? '' : decode_base64($1);
		print "<-- $in\n";
		my $out;
		if (!$started++) {
			if ($in) {
				$out = $conn->client_start();
				$out = $conn->client_step($in);
			} else {
				$out = $conn->client_start();
			}
		} else {
			$out = $conn->client_step($in);
		}
		print "--> $out\n";
		$out = ($out // '') eq '' ? '+' : encode_base64($out, '');

		while (length $out >= 400) {
			my $sub = substr($out, 0, 400, '');
			put("AUTHENTICATE $sub");
		}
		if (length $out) {
			put("AUTHENTICATE $out");
		} else {
			put("AUTHENTICATE +");
		}
	}
	elsif (/ 90\d /) {
		put("QUIT");
	}
}
