#!/usr/bin/env bash
# cap - capture a screenshot to a PNG and upload to imgur.

dir=~/Pictures/Screenshots
date=$(date +"%Y-%m-%d")

for (( count=0; count < 999; count++ )); do
	printf -v name "Unnamed %s.%03d.png" "$date" "$count"
	[[ ! -e $dir/$name && ! -e $dir/.$name.tmp ]] && break
done

tmp="$dir/.tmp.$name"
img="$dir/$name"
mode=screen
imgur=1

while getopts fwaN opt; do
	case $opt in
		f) mode=screen;;
		w) mode=window;;
		a) mode=area;;
		N) imgur=0;;
	esac
done

if dbus-name -q org.gnome.Shell; then
	case $mode in
		area)	gnome-screenshot-import -a "$tmp";;
		window)	gnome-screenshot-import -w "$tmp";;
		screen)	gnome-screenshot-import -f "$tmp";;
	esac
else
	case $mode in
		area|window)	scrot -b -s "$tmp";;
		screen)		scrot "$tmp";;
	esac
fi

if [[ ! -f "$tmp" ]]; then
	notify \
		--app-name "Screenshot" \
		--icon "error" \
		--hint "category=transfer.error" \
		--hint "transient" \
		"Screenshot failed."
	exit 1
fi

mv -f "$tmp" "$img"

if (( imgur )); then
	echo "Captured to $dir/$name, uploading"

	id=$(notify \
		--app-name "Screenshot" \
		--icon "document-send" \
		--hint "category=transfer" \
		"Screenshot captured" \
		"Uploading to imgur...")

	(trap exit TERM
	while sleep 1; do
		notify \
			--app-name "Screenshot" \
			--icon "document-send" \
			--hint "category=transfer" \
			--replace "$id" \
			"Screenshot captured" \
			"Uploading to imgur..." >/dev/null
	done) &

	if output=$(imgur "$img" 2>&1); then
		kill $!
		notify \
			--app-name "Screenshot" \
			--icon "document-send" \
			--hint "category=transfer.complete" \
			--replace "$id" \
			"Screenshot uploaded" \
			"$output" >/dev/null
	else
		kill $!
		output="It is still stored at: file://$(urlencode -rp "$img")"
		notify \
			--app-name "Screenshot" \
			--icon "document-send" \
			--hint "category=transfer.error" \
			--replace "$id" \
			"Screenshot upload failed" \
			"$output" >/dev/null
	fi

	wait
else
	echo "Captured to $dir/$name"
	nautilus --select "file://$dir/$name" &
fi
