#!/usr/bin/env bash

. lib.bash || exit

if dbus-name -eq org.gnome.ScreenSaver; then
	gnome-screensaver-command --lock
elif dbus-name -eq org.cinnamon.ScreenSaver; then
	cinnamon-screensaver-command --lock
else
	die "unknown or no screensaver found"
fi
