#!/usr/bin/env bash

. lib.bash || exit

session=${DESKTOP_SESSION:-default}

if [[ $session == default ]]; then
	session=${XDG_SESSION_DESKTOP:-default}
fi

if [[ $session == default ]]; then
	debug "desktop session is 'default', trying to guess"
	if [[ $GNOME_DESKTOP_SESSION_ID ]]; then
		debug "found GNOME session ID"
		session=gnome
	elif [[ $DBUS_SESSION_BUS_ADDRESS ]]; then
		debug "found DBus session bus, guessing by bus names"
		if dbus-name -q org.gnome.SessionManager; then
			debug "found GNOME session manager"
			session=gnome
		elif dbus-name -q org.xfce.SessionManager; then
			debug "found Xfce4 session manager"
			session=xfce
		fi
	fi
else
	debug "desktop session is '$session'"
fi

case $session in
    enlightenment)
	name=Enlightenment
	cmd='enlightenment_remote -exit'
	;;
    gnome|gnome-*)
	name=GNOME
	if have gnome-session-quit; then
		cmd='gnome-session-quit --logout --force --no-prompt'
	else
		cmd='gnome-session-save --force-logout --silent'
	fi
	;;
    herbstluftwm)
	name=Herbstluftwm
	cmd='herbstclient quit'
	;;
    kde-plasma|kde-plasma-safe)
	name=KDE
	cmd='qdbus org.kde.ksmserver /KSMServer logout 0 -1 -1'
	;;
    [Oo]penbox)
	name=Openbox
	cmd='openbox --exit'
	;;
    ubuntu)
	name=Unity
	cmd='gnome-session-quit --logout --force --no-prompt'
	;;
    Windows_NT)
	name=Windows
	cmd='logoff.exe'
	;;
    wmii)
	name=Wmii
	cmd='wmiir xwrite /ctl quit'
	;;
    xfce)
	name=Xfce4
	cmd='xfce4-session-logout --logout'
	;;
    *)
	die "unknown desktop environment"
esac

debug "detected: $name"
debug "will use: $cmd"

if [[ $DEBUG ]]; then
	echo "Doing nothing in debug mode."
else
	echo "Logging out of ${name}..."
	eval "$cmd"
fi
