#!/usr/bin/env bash

case $DESKTOP_SESSION in
gnome|ubuntu)
	gnome-session-quit --logout --force --no-prompt &&
		echo Logging out of GNOME...
	;;
kde-plasma)
	qdbus org.kde.ksmserver /KSMServer logout 0 -1 -1 &&
		echo Logging out of KDE...
	;;
openbox)
	openbox --exit &&
		echo Logging out of Openbox...
	;;
Windows_NT)
	logoff.exe &&
		echo Logging out of Windows...
*)
	echo Unknown desktop environment!
esac

