#!/usr/bin/env bash
# nolid - disable suspend and lid-close handling while a command runs

. lib.bash || exit

lock="$XDG_RUNTIME_DIR/nolid.lock"
hold="$XDG_RUNTIME_DIR/nolid.hold"

if [[ $_NOLID ]]; then
	warn "ignoring nested lock"
	exec "$@" || exit
else
	export _NOLID=1
fi

notify=0
name="nolid"

if [[ -t 0 ]]; then
	tty=$(tty)
	name="$name on ${tty#/dev/}"
fi

case $1 in
	-h|--hold)
		touch "$hold"
		spawn -dc nolid inotifywait -qqe delete_self "$hold" &
		echo "Held."
		exit;;
	-r|--unhold|--release)
		rm -f "$hold"
		echo "Released."
		exit;;
	-n|--notify)
		notify=1
		shift;;
esac

if [[ -t 0 ]]; then
	settitle "nolid${1:+: $1}"
fi

t_start=$(date +%s)

touch "$lock"

trap 'flock -xn "$lock" rm -f "$lock"' EXIT

flock -s "$lock" \
	systemd-inhibit --who="$name" \
	--what="sleep:handle-lid-switch" \
	--why="Manually inhibited" \
	gnome-inhibit --always \
	--who="$name" \
	--what="suspend" \
	--why="Manually inhibited" \
	"${@:-pause}"

r=$?

t_end=$(date +%s)

if (( notify )); then
	seconds=$((t_end - t_start))
	duration=$(interval $seconds)
	if (( r == 0 )); then
		msg="exited successfully"
	else
		msg="failed (exit status $r)"
	fi
	notify-send \
		-h byte:transient:1 \
		"Lid inhibit removed" \
		"'$1' $msg after $duration" &
fi

exit $r
