#!/bin/sh

cd ~

vt="vt$(fgconsole)" || {
	echo "Unable to determine current VT"
	exit 1
}

export DISPLAY=$(next-display)
export XAUTHORITY=~/.Xauthority
export DESKTOP_SESSION

echo "Starting Xorg on display $DISPLAY"

xauth remove "${HOSTNAME}:${DISPLAY#:}"
xauth remove "$DISPLAY"

xauth add "$DISPLAY" "MIT-MAGIC-COOKIE-1" "$(mcookie)"

ln -sf "/tmp/.X11-unix/X${DISPLAY#:}" "$XDG_RUNTIME_DIR/X11-display"

xinit ~/.xinitrc "$@" -- "$DISPLAY" "$vt" \
	-noreset -auth "$XAUTHORITY" -quiet -background none \
	< /dev/null > "$XDG_CACHE_HOME/xsession.log" 2>&1

xauth remove "$DISPLAY"
