#!/usr/bin/env bash
# toggle-synaptics - Enable or disable the Synaptics touchpad

set -e

oldmode=$(synclient | awk '$1 == "TouchpadOff" {print $3}')

if [[ $oldmode == 1 ]]; then
	newmode=0
	msg="Touchpad enabled"
	icon='input-touchpad-symbolic'
else
	newmode=1
	msg="Touchpad disabled"
	icon='touchpad-disabled-symbolic'
fi

synclient "TouchpadOff=$newmode"

echo "$msg"

gdbus call -e \
	-d org.gnome.Shell \
	-o /org/gnome/Shell \
	-m org.gnome.Shell.ShowOSD \
	"{'icon': <'$icon'>,
	  'label': <'$msg'>}" > /dev/null
