#!/bin/bash
# ACPI event handler for acpieventd
. ~/bin/event/functions

# Keys:
# hotkey,*,0000006b	touchpad toggle
# hotkey,*,00000082	camera key
# hotkey,*,0000008a	(aka button/prog1,PROG1,00000080,00000000,K) "S" key
# hotkey,*,000000b5	calculator key

HOTKEY_CALC=000000b5

log "acpi: $*"

join args , "$@" ""

case $args in
	ac_adapter,*,*,00000000,*)
		#~/bin/event/power ac-unplug
		;;
	ac_adapter,*,*,00000001,*)
		#~/bin/event/power ac-plug
		;;
	button/lid,LID,close,*)
		~/bin/event/power lid-close
		;;
	button/lid,LID,open,*)
		~/bin/event/power lid-open
		;;
	cd/prev,CDPREV,*)
		;;
	cd/next,CDNEXT,*)
		;;
	cd/play,CDPLAY,*)
		;;
	cd/stop,CDSTOP,*)
		;;
	hotkey,*,000000b5,*)
		#spawn sonata
		;;
	hotkey,*,00000082,*)
		#spawn cheese
		;;
	hotkey,*,0000006b,*)
		#spawn toggle-synaptics
		;;
esac
