#!/bin/bash
. ~/bin/event/functions
appname='Transmission status'
icon='transmission'
#icon='folder-download'

[[ $TR_APP_VERSION ]] ||
	die "This script should be run by Transmission."

# TR_APP_VERSION <string>
# TR_TIME_LOCALTIME <datetime>
# TR_TORRENT_DIR <path> /home/grawity/Downloads
# TR_TORRENT_HASH <hex>
# TR_TORRENT_ID <int>
# TR_TORRENT_NAME <string>

rm -f "/tmp/transmission-$TR_TORRENT_HASH"

notify \
	-h "category=transfer.complete" \
	-h "transient" \
	"Download complete" \
	"${TR_TORRENT_NAME}"
