#!/usr/bin/env bash

. lib.bash

status() {
	if [[ -t 1 ]]
		then printf '\e[1;36m--\e[m \e[36m%s\e[m\n' "$*"
		else printf '%s\n' "-- $*"
	fi
	settitle "$progname: $*"
}

umask 077

if [[ ! $_inhibited ]]; then
	export _inhibited=$$
	exec gnome-inhibit \
		--who "backup" \
		--what "suspend" \
		--why "Performing a backup" \
		--always -- "$0" "$@"
fi

log_backup() { log "backing up ${@/#$HOME/~}"; }

obnam_default=()

obnam_rain=(
	--repository ~/Backup/obnam-repository
	--encrypt-with D24F6CB2C1B52632
)

do_obnam() {
	local profile=default
	if [[ $1 == @* ]]; then
		profile=${1#@}
		shift
	fi
	profile="obnam_${profile}[@]"
	log_backup "$@"
	schedtool -B -e obnam backup "${!profile}" "$@"
}

do_rsync() {
	rsync -avzHAX --del "$@"
}

do_unison() {
	log "running Unison profile '$1'"
	unison "$@" -auto -terse
}

# Run arguments after acquiring a TGT via keytab.
do_kstart() {
	princ=${princ:-'grawity/backup@CLUENET.ORG'}
	k5start -L -q -f "$b/backup.keytab" -u "$princ" -- "$@"
}

recurse_git() {
	find "$1" -name "*.git" -type d -prune \
		-exec git --git-dir {} "${@:2}" \;
}

set -e

b="/mnt/backup"

job=${1%/}; shift

mkdir -p ~/Backup/.log
exec {fd}>~/Backup/.log/$job.log
flock -x -n $fd || die "job $job is already running"

status "running job '$job'"

case $job in
	remote)
		$0 twitter
		$0 servers
		#$0 nullroute-git
		;;
	sync-snow)
		do_unison Backup-snow -batch
		do_unison Attic-snow -batch
		;;
	push-hd)
		log "Repacking repositories..."
		git all-repack ~/projects
		#dirs=(	~/{bin,projects,code,lib/dotfiles}
		#	~/{.ecryptfs,Private}
		#	~/{Music,Pictures,Videos}
		#	~/{Attic,Backup,Dropbox,public_html}
		#	~/Downloads
		#	~/src/irc
		#)
		dirs=( ~ ) 
		do_obnam "${dirs[@]}"
		;;
	# jobs
	irc)
		do_rsync decay:irclogs/ ~/Attic/Chatlogs/current/
		;;
	servers)
		for host in $(< ~/Backup/hosts.txt); do
			$0 @$host
		done
		$0 irc
		;;
	@*)
		host=${job#@}
		do_rsync $host: ~/Backup/Homes/$host/ \
			-f "merge $HOME/Backup/global-rsync-filter" \
			-F
		;;
	gale)
		do_rsync \
			ofb.net:'~jtr/glog/' \
			~/Attic/Chatlogs/ofb.net/jtr-glog/ \
			--exclude "/:glog.out" ;
		do_rsync \
			ofb.net:'~egnor/etc/gale/auth/' \
			~/Attic/Chatlogs/ofb.net/cached-keys/ \
			--exclude "tmp.*" ;
		;;
	cluenet)
		log "Downloading accounts.git from virgule..."
		(cd "$b/virgule.cluenet.org/accounts/"
		do_kstart git pull origin)

		log "Downloading all backups from radian..."
		(cd "$b/radian.cluenet.org/accounts/"
		do_kstart git pull origin)
		do_kstart rsync -aHAXvz --delete \
			--exclude "/accounts/.git" \
			"root@radian.cluenet.org:/backup/" \
			"$b/radian.cluenet.org/backup/"
		do_kstart rsync -aHAXvz --delete \
			"root@radian.cluenet.org:/var/www/" \
			"$b/radian.cluenet.org/www/"
		;;
	grawpqi)
		dir=/run/media/grawity/grawpqi/
		mountpoint -q "$dir" || die "'grawpqi' not mounted"
		do_obnam @rain "$dir"
		;;
	linux)
		do_rsync --exclude='config' \
			--exclude='index' \
			~/src/linux/.git/ \
			/mnt/backup/git-repos/linux.git/
		;;
	music)
		unison-x11 Music
		;;
	nullroute-git)
		host=virgule
		path=pub/git
		dst=~/Backup/nullroute-git/
		log "Repacking remote repositories..."
		ssh $host "git all-repack ~/$path"
		log "Updating local backup..."
		do_rsync --copy-links "$host:$path/" "$dst"
		;;
	twitter)
		~/code/backup/twitter-backup
		;;
	lsjobs)
		sed -rn '/^case \$job in$/,/^esac$/ { s/^\t(\S+)\)$/\1/p }' "$0"
		;;
	*)
		die "unknown job '$job'"
		;;
esac

echo "$(date -Isecond)" >&$fd
