#!/bin/sh

str="Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag.
# For information about cache directory tags, see:
#	http://www.brynosaurus.com/cachedir/"

if [ $# -eq 0 ]; then
	echo "Usage: cachedir-tag <dir>..."
	exit 2
fi

for dir; do
	echo "$str" > "$dir/CACHEDIR.TAG"
	echo "Tagged $dir"
done
