#!/bin/sh

u=${USER:-${LOGNAME:-$(whoami)}}
h=${HOSTNAME:-$(hostname)}

str="Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag created by $u@$h.
# For information about cache directory tags, see:
#	http://www.brynosaurus.com/cachedir/"

if [ $# -eq 0 ]; then
	echo "Usage: cachedir-tag <dir>..."
	exit 2
fi

err=0

for dir; do
	if echo "$str" > "$dir/CACHEDIR.TAG"; then
		echo "Tagged $dir"
	else
		err=1
	fi
done

exit $err
