#!/usr/bin/env bash
set -e
umask 077

keyid="grawity@gmail.com"

die() {
	echo "$*" >&2
	exit 1
}

encrypt() {
	gpg --encrypt --recipient "$keyid" --batch | gpg --store -z 1
}

if [[ $SSH_ORIGINAL_COMMAND ]]; then
	set -- $SSH_ORIGINAL_COMMAND
	if [[ $1 == serve || $1 == */serve ]]; then
		shift
	else
		die "error: incorrect arguments ('$1' != 'serve')"
	fi
fi

setname=$1

if ! [[ $setname ]]; then
	die "Usage: serve <setname>"
fi

if [[ -t 1 ]]; then
	die "error: will not write to a tty"
fi

script="$HOME/code/misc/backup/serve.$setname" "${@:2}"

if [[ -x $script ]]; then
	"$script" | encrypt
else
	die "error: unknown set name $setname"
fi
