#!/usr/bin/env perl
use JSON;
use feature qw(say);

open(my $f, "<", "$ENV{HOME}/Backup/tweets.json");
my $tweets = decode_json(eval {local $/; <$f>});
close($f);

binmode STDOUT, ":utf8";

for my $tweet (@$tweets) {
	printf "[%s] %s\n",
		$tweet->{id},
		$tweet->{text};
}
