#!/bin/sh
p=""
p="$p application.name='Catznip'"
p="$p application.icon_name='catznip'"
p="$p media.role='game'"
export LIBGL_DRIVERS_PATH="/usr/lib64/xorg/modules/dri:/usr/lib32/xorg/modules/dri"
export PULSE_PROP_OVERRIDE="$p"
export SDL_VIDEO_X11_WMCLASS='catznip-viewer'
exec run-secondlife ~/.local/pkg/catznip/catznip "$@"
