#!/bin/bash
# wrapper for 'crawl' (Stone Soup) adding immortality via Git

. lib.bash || exit

: ${CRAWL_DIR:-~/.crawl}

case $1 in
'save')
	cd "$CRAWL_DIR"
	git add --all
	git commit -m "Snapshot"
	;;
'restore')
	cd "$CRAWL_DIR"
	confirm "discard game?" && {
		git reset --hard HEAD$2
		git clean -fd
	}
	;;
*)
	exec /usr/bin/crawl "$@"
	;;
esac
