#!/bin/sh
p=""
p="$p application.name='Firestorm Viewer'"
p="$p application.icon_name='firestorm-viewer'"
p="$p media.role='game'"
export PULSE_PROP_OVERRIDE="$p"
export SDL_VIDEO_X11_WMCLASS='firestorm-viewer'
exec run-secondlife ~/.local/pkg/firestorm/firestorm "$@"
