#!/bin/bash

. lib.bash || exit

while {
	start=$(date +%s)
	/usr/bin/gnome-shell "$@"; r=$?
	end=$(date +%s)

	if (( end-start < 3 )); then
		warn "gnome-shell exited with $r after $(( end-start ))s"
		msg="Looks like it's fucked. Restart anyway?"
	elif (( $? )); then
		warn "gnome-shell exited with status $r" >&2
		msg="GNOME Shell crashed. Restart"
	else
		break
	fi

	zenity --question "Failwhale" --text="$msg"
}; do true; done

exit $r
