#!/usr/bin/env bash
# wrapper to avoid the `gio` bug which doesn't wait for the application to activate
# (which for some reason causes it to exit again)

if [[ -d "${1#file://}" ]]; then
	echo "$0: redirecting to 'gapplication launch'" >&2
	exec gapplication launch org.gnome.Nautilus "$1"
fi

# note: gvfs-open itself redirects to `gio open`, so this is not very useful

exec /usr/bin/gvfs-open "$@"
