#!/usr/bin/env bash
cmd=${0##*/}
settitle "$HOSTNAME ${_NOLID:+*}[$cmd]"
if [ "$(dbus-uuidgen --get)" = 067d8bfe341b445487660bf2c983c2ec ]; then
	exec ~/.local/bin/$cmd "$@"
else
	exec "/usr/bin/$cmd" "$@"
fi
