#!/bin/sh
p=""
p="$p application.name='Kokua'"
p="$p application.icon_name='kokua'"
p="$p media.role='game'"
export PULSE_PROP_OVERRIDE="$p"
export SDL_VIDEO_X11_WMCLASS='kokua-viewer'
exec run-secondlife ~/.local/pkg/kokua/kokua "$@"
