#!/usr/bin/env bash
# wrapper for 'pacman' to add flock-based locking

if (( UID == 0 )) && [[ ! $PACMAN_LOCK ]] && [[ ! $FAKEROOTKEY ]]; then
	lock=/run/lock/pacman
	exec {fd}>"$lock" &&
	/usr/bin/flock -xn $fd || {
		echo -n "waiting for other instances to exit..."
		/usr/bin/flock -x $fd && echo "done"
	} >&2
	dblock=/var/lib/pacman/db.lck
	[[ ! -e "$dblock" ]] || {
		rm -fi "$dblock"
	}
	export PACMAN_LOCK=$fd
fi

exec /usr/bin/pacman "$@"
