#!/usr/bin/env bash
# wrapper for 'pacman' to add flock-based locking

self=$(which pacman)
PATH=${PATH//:${self%/*}:/:}
(( UID || PACMAN_LOCK )) || {
	lock=/run/lock/pacman
	exec {fd}>"$lock" &&
	/usr/bin/flock -xn $fd || {
		echo -n "waiting for other instances to exit..."
		/usr/bin/flock -x $fd && echo "done"
	} >&2
	dblock=/var/lib/pacman/db.lck
	[[ ! -e "$dblock" ]] || {
		rm -fi "$dblock"
	}
} && PACMAN_LOCK=$fd exec /usr/bin/pacman "$@"
