#!/bin/sh
p=""
p="$p application.name='RestrainedLove'"
p="$p application.icon_name='restrainedlove'"
p="$p media.role='game'"
export PULSE_PROP_OVERRIDE="$p"
export SDL_VIDEO_X11_WMCLASS='restrainedlove'
exec run-secondlife ~/.local/pkg/restrainedlove/secondlife "$@"
