#!/bin/sh
# Environment wrapper

export PULSE_PROP="application.icon_name='runescape'"
export PULSE_PROP_OVERRIDE="application.name='RuneScape'"

dir=$HOME/.local/rsu-client/runescape

case $1 in
    "--launcher")
	exec "$dir/runescape"; exit;;
    "--updater"|"--update")
	wget "https://www.runescape.com/downloads/jagexappletviewer.jar" \
		-O "$dir/bin/jagexappletviewer.jar"; exit;;
#/home/grawity/.local/rsu-client/runescape/rsu/rsu-query rsu.download.client bin jar
	#exec "$dir/updater"; exit;;
    "--settings"|"--configure"|"--config")
	exec "$dir/rsu-settings"; exit;;
    "--beta")
	shift; set -- "--prmfile=runescape-beta.prm" "$@";;
    "--classic")
	shift; set -- "--prmfile=runescape_classic2.prm" "$@";;
    "--darkscape")
	shift; set -- "--prmfile=rsdarkscape.prm" "$@";;
    "--custom")
	shift; set -- "--prmfile=custom.prm" "$@";;
    "--oldschool")
	shift; set -- "--prmfile=oldschool.prm" "$@";;
    "@"*)
	f=${1#'@'}; f=${f%'.prm'}
	shift; set -- "--prmfile=$f.prm" "$@";;
esac

(sleep 10; rs-fix-dark) &

exec "$dir/runescape" --unixquery "$@"
