#!/bin/sh
# Environment wrapper

client=java
java_prm=

export PULSE_PROP="application.icon_name='runescape'"
export PULSE_PROP_OVERRIDE="application.name='RuneScape'"

java_dir=$HOME/.local/rsu-client/runescape

case $1 in
    "--java")
	client=java;;
    "--launcher")
	client=java-launcher;;
    "--updater"|"--update")
	client=java-updater;;
    "--settings"|"--configure"|"--config")
	client=java-settings;;
    "--beta")
	java_prm="runescape-beta.prm";;
    "--classic")
	client=java; java_prm="runescape_classic2.prm";;
    "--darkscape")
	java_prm="rsdarkscape.prm";;
    "--custom")
	client-java; java_prm="custom.prm";;
    "--oldschool")
	client=java; java_prm="oldschool.prm";;
esac

case $client in
    java)
	if [[ $java_prm ]]; then
		set -- --prmfile="$java_prm" "$@"
	fi
	exec "$java_dir/runescape" --unixquery "$@"
	;;
    java-launcher)
	exec "$java_dir/runescape" "$@"
	;;
    java-settings)
	exec "$java_dir/rsu-settings"
	;;
    java-updater)
	wget "https://www.runescape.com/downloads/jagexappletviewer.jar" \
		-O "$java_dir/bin/jagexappletviewer.jar"
	;;
esca
