#!/bin/sh
# Environment wrapper

client=nxt
java_dir=$HOME/.local/rsu-client/runescape
java_prm=

while [ "$1" ]; do
	case $1 in
	    --java)
		shift; client=java;;
	    --launcher)
		shift; client=java-launcher;;
	    --updater|--update)
		shift; client=java-updater;;
	    --settings|--configure|--config)
		shift; client=java-settings;;
	    --darkscape)
		shift; java_prm="rsdarkscape.prm";;
	    --beta)
		shift;
		nxt_conf="rs-launchs://www.runescape.com/jav_config_beta.ws";
		java_prm="runescape-beta.prm";;
	    --oldschool)
		shift; client=java; java_prm="oldschool.prm";;
	    --dgpu)
		shift; export DRI_PRIME="1";;
	    -*)
		echo "$0: unknown option '$1'" >&2; exit 2;;
	    *)
		break;
	esac
done

case $client in
    nxt)
	export HOME=${XDG_CACHE_HOME:-$HOME/.cache}
	if [[ $nxt_conf ]]; then
		set -- "$nxt_conf" "$@"
	fi
	exec /usr/bin/runescape-launcher "$@"
	;;
    java)
	export PULSE_PROP="application.icon_name='runescape'"
	export PULSE_PROP_OVERRIDE="application.name='RuneScape'"
	if [[ $java_prm ]]; then
		set -- --prmfile="$java_prm" "$@"
	fi
	exec "$java_dir/runescape" --unixquery "$@"
	;;
    java-launcher)
	exec "$java_dir/runescape" "$@"
	;;
    java-settings)
	exec "$java_dir/rsu-settings"
	;;
    java-updater)
	wget "https://www.runescape.com/downloads/jagexappletviewer.jar" \
		-O "$java_dir/bin/jagexappletviewer.jar"
	;;
esac
