#!/bin/sh
p=""
p="$p application.name='Second Life'"
p="$p application.icon_name='secondlife'"
p="$p media.role='game'"
export PULSE_PROP_OVERRIDE="$p"
export SDL_VIDEO_X11_WMCLASS='secondlife-viewer'
exec run-secondlife /opt/secondlife/secondlife "$@"
