#!/usr/bin/env perl
# wrapper for 'svn' translating arguments like foo{} to file:// URLs

use Cwd;
use File::Spec qw(rel2abs);

sub path2uri {
	my $path = shift;
	$path =~ s/\{\}$//
		? "file://".File::Spec->rel2abs($path)
		: $path;
}

my $cwd = "file://".getcwd();

exec {"/usr/bin/svn"} "svn",
			map {path2uri($_)}
			map {$_ eq "{}" ? $cwd : $_}
			@ARGV;
