#!/usr/bin/env bash
# wrapper for 'ttytter'
export PATH="$HOME/bin/compat/ttytter:$PATH"
export PERL_RL="TTYtter"
export PERL_SIGNALS="unsafe"
exec -a "$0" /usr/bin/ttytter \
	-rc="$XDG_CONFIG_HOME/ttytter/rc" \
	-keyf="$XDG_CONFIG_HOME/ttytter/key" \
	"$@"
