#!/usr/bin/env bash
# wrapper for 'unison' adding gnome-inhibit

if [[ $1 == "-server" ]]; then
	exec /usr/bin/unison "$@"
elif (( $# )) && [[ -t 0 ]]; then
	exec gnome-inhibit \
		--always \
		--who "Unison" \
		--what "suspend" \
		--why "Synchronizing" \
		/usr/bin/unison "$@"
else
	exec spawn -c \
		gnome-inhibit \
		--always \
		--who "Unison" \
		--what "suspend" \
		--why "Synchronizing" \
		/usr/bin/unison-x11 "$@"
fi
