#!/bin/sh
exec dex "${XDG_DATA_HOME:-~/.local/share}/applications/wine/Programs/World of Warcraft/World of Warcraft.desktop"
#export WINEPREFIX=~/.wine
#exec wine 'C:\windows\command\start.exe' /Unix "$WINEPREFIX/dosdevices/c:/users/Public/Start Menu/Programs/World of Warcraft/World of Warcraft.lnk"
