#!/usr/bin/env bash
umask 077

realm=$1
if ! [[ $realm ]]; then
	echo "error: usage: krb5db-push <realm>" >&2
	exit 1
fi

if [[ -t 1 ]]; then
	echo "error: will not write to a tty"
	exit 1
fi

keyid="grawity@gmail.com"
sudo kdb5_util -r "$realm" dump |
	gpg --encrypt -r "$keyid" --batch |
	gpg --store
	# very simple check against truncation
