#!/usr/bin/env bash

usage() {
	echo "Usage: ${0##*/} [-ersw] <title>"
}

ESC='\e' ST='\e\\' BEL='\007' EOL='' MODE='title' SAVE=0 RESTORE=0

while getopts "ersw" OPT; do
	case $OPT in
	e) ESC='\\e' ST='\\e\\\\' BEL='\\007' EOL='\n';;
	r) RESTORE=0;;
	s) SAVE=1;;
	w) MODE='wname';;
	*) usage; exit 2;;
	esac
done

case $MODE in
'title')
	case $TERM in
	[xkE]term*|rxvt*|cygwin|dtterm|termite)
		fmt="${ESC}]0;%s${BEL}";;
	screen*)
		fmt="${ESC}k%s${ST}";;
	vt300*)
		fmt="${ESC}]21;%s${ST}";;
	*)
		fmt="";;
	esac;;
'wname')
	case $TERM in
	screen*)
		fmt="${ESC}k%s${ST}";;
	*)
		fmt="";;
	esac;;
esac

title=${!OPTIND}

if [[ $fmt ]]; then
	if (( SAVE )); then
		fmt="${ESC}[22;2t${fmt}"
	elif (( RESTORE )); then
		fmt="${ESC}[23;2t"
	fi
fi

printf "${fmt}${EOL}" "$title" >&2
