#!/usr/bin/env bash
usage() {
	echo "usage: ${0##*/} [-e] [-w] <title>" >&2
	exit 2
}

titlestring() {
	case ${TERM:-dumb} in
	[xkE]term*|rxvt*|cygwin|dtterm|termite)
		printf %s "${ESC}]0;%s${BEL}";;
	screen*)
		printf %s "${ESC}k%s${ST}";;
	vt300*)
		printf %s "${ESC}]21;%s${ST}";;
	esac;
}

wnamestring() {
	case ${TERM:-dumb} in
	screen*)
		printf %s "${ESC}k%s${ST}";;
	esac
}

ESC='\e' ST='\e\\' BEL='\007' EOL='' FUNC='titlestring'

if getopts "ew" OPT "$@"; then
	case $OPT in
	'e')	ESC='\\e' ST='\\e\\\\' BEL='\\007' EOL='\n';;
	'w')	FUNC='wnamestring';;
	'?')	usage;;
	esac
fi

title=${!OPTIND}

if [[ $title ]]; then
	printf "$($FUNC)${EOL}" "$title"
else
	usage
fi
