.\" vim: ft=nroff
.TH AFINGERD "8"
.SH NAME
afingerd \- a finger daemon
.SH SYNOPSIS
.B afingerd
.SH DESCRIPTION
A simple finger daemon written in PHP.
.SH DIFFERENCES FROM BSD FINGER
.IP - 2
Does not crash when queried over IPv6
.IP -
Information can be partially hidden
.IP -
Different hiding levels for each user (~/.afingerd)
.IP -
No full name matching (too lazy, also security)
.IP -
No userlist, no last login times (too lazy to fuck with utmp)
.IP -
No phone number formatting
.IP -
No command line options, /etc/afingerd.conf is used instead
.SH FILES
.TP
/etc/afingerd.conf
Global configuration.
.TP
~/.afingerd, ~/.config/afingerd.conf
User configuration.
.TP
~/.nofinger
If this file exists, the user will be "invisible" - essentially nonexistent.
.SH CONFORMS TO
RFC 1288
.SH SEE ALSO
\fBin.fingerd\fP(8),
\fBinetd\fP(8)
