#!/bin/bash
: ${PAGER=less}
: ${BROWSER=w3m}
PAGER=$BROWSER

case $1 in
irssi)
	dir=/usr/share/doc/irssi
	$PAGER "$dir/${2:-manual}.txt"
	;;
mutt)
	dir=/usr/share/doc/mutt
	$BROWSER "$dir/manual.html"
	;;
*)
	echo "doc: no documentation" >&2
	exit 1
esac
