#!/bin/bash
pid=$1
fd=$2

fdi=/proc/$pid/fdinfo/$fd

read -r _ pos < "$fdi"
#printf 'pos: %14d (%3d%%)' $pos $[pos*100/size]

while sleep 1; do
	prev=$pos
	read -r _ pos < "$fdi"
	printf 'pos: %14d (%3d%%) at %6d kB/s (%' $pos $[pos*100/size]
