#!/usr/bin/env perl
use strict;

$, = "\t";
$\ = "\n";

my %aliases = ();

print "# vim: ft=muttrc";
for my $entry (do "$ENV{HOME}/bin/parse-addressbook.pl") {
	next unless $entry->{nick} and $entry->{email};
	if (defined $aliases{$entry->{nick}}) {
		warn "duplicate alias '$entry->{nick}' <$entry->{email}>\n";
	}
	$aliases{$entry->{nick}} = $entry->{email};
	print "alias", $entry->{nick}, $entry->{name}, "<$entry->{email}>";
}
