#!/bin/bash
db="sql:$HOME/.pki/nssdb"
case $1 in
	-dtb)
		db="$HOME/.thunderbird/1xrzgg5b.default"; shift;;
	-dfx)
		db="$HOME/.mozilla/firefox/tqgkb7pw.default"; shift;;
esac

exec certutil -d "$db" "$@"
