#!/bin/bash
(exec -a "$0" args "$@")>/dev/tty
if ! ssh "$1" -O check 2>/dev/null; then
	# establish tunnel
	echo "sshtunnel: connecting to $1" >/dev/tty
	ssh "$1" -fNM
else
	# check tunnel
	if ! timeout 5 ssh "$1" true &>/dev/null; then
		ssh "$1" -O exit >&/dev/null
		while ssh "$1" -O check 2>/dev/null; do
			sleep 0.3
		done
		echo "sshtunnel: re-connecting to $1" >/dev/tty
		ssh "$1" -fNM
	fi
fi
exec ssh "$@"
