#!/bin/sh

exe_name="${0##*/}"
exe_symlink="$HOME/bin/compat/py2.$exe_name"
exe_path=$(readlink -f "$exe_symlink")

compat_dir="$HOME/bin/compat/python2"
interp_path=$(which python 2>/dev/null || echo python)
if [ "$interp_path" != "$compat_dir/python" ]; then
	export PATH="$compat_dir:$PATH"
	interp_path="$compat_dir/python"
fi

exec "$interp_path" "$exe_path" "$@"
