#!/usr/bin/env bash
# symlinkable wrapper (v4l2convert.so)

EXE=$(which -a "${0##*/}" | uniq | sed -n 2p)

LD_PRELOAD="${LD_PRELOAD+$LD_PRELOAD:}/usr/\$LIB/libv4l/v4l2convert.so"
LD_PRELOAD="${LD_PRELOAD+$LD_PRELOAD:}/usr/\$LIB/libv4l/v4l1compat.so"
export LD_PRELOAD

javalib=$(ldd $(which java) | perl -ne 'm|^\s*libjli\.so\s+=>\s+(.+)/jli/libjli\.so\s+| and print $1')
LD_LIBRARY_PATH="${LD_LIBRARY_PATH+$LD_LIBRARY_PATH:}$javalib"
export LD_LIBRARY_PATH

#_JAVA_OPTIONS="$_JAVA_OPTIONS -Duser.home=\"$HOME/lib/runescape/share/cache\""
#export _JAVA_OPTIONS
unset _JAVA_OPTIONS

exec "$EXE" "$@"
