#!/usr/bin/env bash

. lib.bash || exit

suffix="-dummy"

while getopts ":F" OPT; do
	case $OPT in
	F) suffix="";;
	*) lib::die_getopts;;
	esac
done; shift $((OPTIND-1))

(( $# )) || die "no package names specified"

set -e
workdir=$(mktemp -d /tmp/fakepkg.XXXXXXXXXX)
cd "$workdir"
for pkgname in "$@"; do
	pkgname=${pkgname@Q}
	cat > PKGBUILD <<-!
	pkgname=$pkgname$suffix
	pkgdesc="Dummy package providing "$pkgname
	pkgver=0
	pkgrel=0
	arch=(any)
	provides=($pkgname)
	replaces=($pkgname)
	conflicts=($pkgname)
	!
	${EDITOR:-vim} PKGBUILD
	makepkg --force --nosign --install --asdeps || true
done
cd /
rm -rvf "$workdir"
