#!/usr/bin/env bash
# paccat - cat a file from a pacman package

. lib.bash || exit

package=$1
file=$2

if [[ $file != /* ]]; then
	file=$(readlink -m "$file")
fi

if [[ $package != */* ]]; then
	# Ensure that expac finds the same package that pacman does
	package=$(expac -S1 %r/%n "$package")
fi

url=$(pacman -Sddp "$package")
pkg=$(expac -S1 %f "$package")
pkg=/var/cache/pacman/pkg/$pkg

if [[ ! -s $pkg ]]; then
	sudo pacman -Sddw --noconfirm --quiet "$package" >&2
fi

if [[ ! -s $pkg ]]; then
	die "could not download '${pkg##*/}'"
fi

bsdtar xfO "$pkg" "${file#/}"
