#!/usr/bin/env python3
# Jetty Deobfuscation Tool
# https://stackoverflow.com/a/18861386/49849
import sys

def deobfuscate_jetty(ciphertext):
    plaintext = ""
    for i in range(0, len(ciphertext), 4):
        t = ciphertext[i:i+4]
        i0 = int(t, 36)
        i1, i2 = divmod(i0, 256)
        x = (i1 + i2 - 254) >> 1
        plaintext += chr(x)
    return plaintext

args = sys.argv[1:]

if not args:
    print("Jetty Deobfuscation Tool v1.0")
    print("%s <string>" % sys.argv[0])
    exit(1)

for arg in args:
    print(deobfuscate_jetty(arg))
