#!/usr/bin/env bash

. lib.bash

if have gpg-agent && gpg-agent 2>/dev/null; then
	echo -n "gpg-agent..."
	echo "reloadagent" | gpg-connect-agent
fi

if have kdestroy; then
	echo -n "Kerberos..."
	if have pklist; then
		pklist -lN | xargs -r -n 1 kdestroy -c
	else
		kdestroy
	fi
fi

if have sudo; then
	echo -n "sudo..."
	sudo -K
fi

if [[ $SSH_AUTH_SOCK ]] && ssh-add -l > /dev/null; then
	echo -n "ssh-agent..."
	ssh-add -D
fi

if [[ -S ~/.git-credential-cache/socket ]]; then
	echo -n "Git..."
	git credential-cache exit
fi

while mountpoint -q ~/Private; do
	echo -n "~/Private..."
	ecryptfs-umount-private
	if mountpoint -q ~/Private; then
		sleep 0.3
	fi
done

echo "done"
