#!/usr/bin/env bash

have() {
	command -v "$1" >&/dev/null
}

if have gpg-agent && gpg-agent 2>/dev/null; then
	echo -n "gpg-agent..."
	gpg-connect-agent <<< "reloadagent"
fi

if have kdestroy; then
	echo -n "Kerberos..."
	if have pklist; then
		pklist -lN | xargs -n 1 -r kdestroy -c
	else
		kdestroy
	fi
fi

if [[ $SSH_AUTH_SOCK ]] && ssh-add -l >/dev/null; then
	echo -n "ssh-agent..."
	ssh-add -D
fi

if [[ -S ~/.git-credential-cache/socket ]]; then
	echo -n "Git..."
	git credential-cache exit
fi

while mountpoint -q ~/Private; do
	echo -n "~/Private..."
	ecryptfs-umount-private
	if mountpoint -q ~/Private; then
		sleep 0.3
	fi
done
