#!/usr/bin/env perl
no if $] >= 5.017011, warnings => qw(experimental::smartmatch);
use feature qw(switch);

my $helper = shift @ARGV;
my @args = @ARGV;
my $action = pop @ARGV;

sub runhelper { exec {"git"} "git", "credential-$helper", @args }

for ($action) {
	when ("get") {
		runhelper;
	}
	when ("store") {
		warn "Will not store to credential-$helper.\n";
	}
	when ("erase") {
		warn "Will not erase from credential-$helper.\n";
		#runhelper;
	}
	default {
		exit 0;
	}
}
