#!/usr/bin/env python3
# mksshfp - convert OpenSSH public keys to DNS SSHFP records

from __future__ import print_function
import sys
import hashlib
import nullroute as lib
import nullroute.authorized_keys as authorized_keys

keytypes = {
    "ssh-rsa":              1,
    "ssh-dss":              2,
    "ecdsa-sha2-nistp256":  3,
    "ecdsa-sha2-nistp384":  3,
    "ecdsa-sha2-nistp521":  3,
}

hashtypes = [
    (1, hashlib.sha1),
    (2, hashlib.sha256),
]

def parse(path):
    for line in open(path):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            key = authorized_keys.PublicKey(line)
        except ValueError:
            lib.err("parse error at: %r" % line)
            continue
        if key.algo not in keytypes:
            lib.err("no SSHFP type for '%s' keys" % key.algo)
            continue
        for hash_id, hash_func in hashtypes:
            keyhash = hash_func(key.blob)
            hexhash = keyhash.hexdigest()
            yield {
                "key": key,
                "hash_id": hash_id,
                "hash": keyhash.digest(),
                "rrdata": "%d %d %s" % (keytypes[key.algo],
                                        hash_id,
                                        keyhash.hexdigest())
            }

try:
    host = sys.argv[1]
    infile = sys.argv[2]
except IndexError:
    lib.die("missing host and pubkey-file parameters")

for entry in parse(infile):
    print(repr(entry["key"]))
    print("%s\t%s\t%s" % (host, "SSHFP", entry["rrdata"]))

lib.exit()
