#!/usr/bin/env python
# ssh-duphosts v1.1
# Checks for duplicate entries in ~/.ssh/known_hosts
from __future__ import print_function
import os
import sys
import getopt

knownhosts_path = os.path.expanduser("~/.ssh/known_hosts")
do_filter = False

opts, args = getopt.getopt(sys.argv[1:], 'f')
for opt, optarg in opts:
	if opt in ('f', '-f'):
		do_filter = True
if args:
	knownhosts_path = args.pop(0)

keys = {}
fh = open(knownhosts_path, "r")

# check for duplicates
for line in fh:
	line = line.strip()
	if line == "" or line.startswith("#"):
		continue
	
	host, ktype, key = line.split(" ", 2)

	try:
		int(ktype)
	except ValueError:
		pass
	else:
		key = ktype + " " + key
		ktype = "(sshv1-rsa)"

	if (ktype, key) in keys:
		keys[ktype, key].append(host)
	else:
		keys[ktype, key] = [host]

# print results
if do_filter:
	for entry in keys:
		ktype, key = entry
		hosts = ",".join(keys[entry])
		if ktype == "(sshv1-rsa)":
			print(hosts, key)
		else:
			print(hosts, ktype, key)
else:
	for entry in keys:
		hosts = keys[entry]
		ktype, key = entry
		if len(hosts) > 1:
			print("Key [%(shortkey)s] has %(count)d entries:" % {
				"shortkey": ktype + " ..." + key[-15:],
				"count": len(hosts)
			})
			print("\t%s" % "\n\t".join(hosts))
