#!/usr/bin/env bash
host=wolke.nullroute.eu.org
keys='~/.ssh/id_global_20111101 ~/.ssh/id_global_20150515'
if [[ $1 == @(work|uk|-w) ]]; then
	host=ember.nullroute.eu.org
	keys='~/.ssh/work/id_ukolegija'
fi
echo "Connecting to $host"
ssh -A -t "$host" "ssh-add $keys"
sleep 0.5
ssh-add -l
