#!/usr/bin/env bash

dir="$1"

cmd=()

case $DESKTOP_SESSION in
	gnome*|ubuntu*)
		cmd+=(gnome-inhibit -f suspend -a "Disk wipe"
			-r "Performing free space wipe");;
esac

cmd+=(sudo)

"${cmd[@]}" scrub --freespace --no-signature --pattern random "$dir/scrub"
