#!/usr/bin/env bash

. lib.bash || exit

dir="$1"

[[ "$dir" ]] || die "missing filesystem parameter"

[[ -d "$dir" ]] || die "given path is not a directory"

cmd=(
	gnome-inhibit
		--who "${0##*/}"
		--what "suspend"
		--why "Cleaning free disk space"
		--always
	sudo
	scrub
		--freespace
		--no-signature
		--pattern random
		"$dir/scrub"
)

"${cmd[@]}"
