#!/usr/bin/env bash
# x509 - dump information on an X.509 certificate

. lib.bash || exit

if (( ! $# )); then
	set -- /dev/stdin
fi

unset temp

for file; do
	debug "processing '$file'"
	if [[ "$file" == "-" || "$file" == "/dev/stdin" ]]; then
		if [[ ! "$temp" ]]; then
			temp=$(mktemp "/tmp/x509_XXXXXXXX")
		fi
		debug "- copying stdin to temporary file"
		cat > "$temp"
		file="$temp"
	fi

	der=0
	if [[ "$(head -c 2 "$file")" == $'\x30\x82' ]]; then
		debug "- is probably in DER format"
		der=1
	fi

	unset arg
	if have certtool; then
		if (( der )); then
			arg="--inder"
		fi
		debug "- calling 'certtool${arg:+ }$arg'"
		certtool $arg -i < "$file" |
			sed -r '/^-----BEGIN/,/^-----END/d;
			/^\t*([0-9a-f][0-9a-f]:)+[0-9a-f][0-9a-f]$/d;
			/^\t.*random art:$/,/^\t\t\+-+\+$/d'
	else
		if (( der )); then
			arg="-inform DER"
		fi
		debug "- calling 'openssl x509${arg:+ }$arg'"
		openssl x509 -noout -text -certopt no_pubkey,no_sigdump $arg < "$file"
	fi
done

if [[ "$temp" ]]; then
	debug "removing temp file '$temp'"
	rm -f "$temp"
fi
