#!/usr/bin/env python3
# id3-sync-rg - copy ReplayGain tags from RVA2 to foobar2000
import argparse
import mutagen.mp3
import sys
from nullroute.mp3tags import GainValue

parser = argparse.ArgumentParser()
parser.add_argument("file", nargs="+")
args = parser.parse_args()

for file in args.file:
	print("updating %s" % file)
	ftag = mutagen.mp3.MP3(file)

	trackgain = GainValue.import_tag(ftag, 'track')
	if trackgain:
		#print trackgain
		trackgain.export_id3(ftag)

	albumgain = GainValue.import_tag(ftag, 'album')
	if albumgain:
		#print albumgain
		albumgain.export_id3(ftag)

	if trackgain or albumgain:
		ftag.save()
