#!/usr/bin/env python3

# Apparently the ReplayGain ID3 fields are supposed in upper-case, even though Ex Falso has been writing them in lower-case the whole time. TODO: Check what foobar2k does?
#
# https://github.com/quodlibet/quodlibet/issues/3228
# https://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification#ID3v2
#
# (Note: Spec says that players *should* accept alternate capitalization, as
# well as other formatting quirks.)

import mutagen.mp3
import sys

replaygain_keys = [
    "REPLAYGAIN_TRACK_GAIN",
    "REPLAYGAIN_TRACK_PEAK",
    "REPLAYGAIN_ALBUM_GAIN",
    "REPLAYGAIN_ALBUM_PEAK",
]

dry_run = False
n_good = 0
n_bad = 0

for path in sys.argv[1:]:
    if path in {"-n", "--dry-run"}:
        dry_run = True
        continue

    if not path.lower().endswith(".mp3"):
        print("ignoring", path, "(not an MP3 file)")
        continue

    print("processing", path)
    tag = mutagen.mp3.MP3(path)
    dirty = False

    for k in replaygain_keys:
        old = "TXXX:%s" % k.lower()
        new = "TXXX:%s" % k.upper()
        if old in tag:
            if dry_run:
                print("  found %r" % tag[old])
            elif new in tag:
                print("  deleting %r (duplicate)" % tag[old])
                del tag[old]
                dirty = True
            else:
                print("  fixing %r" % tag[old])
                value = tag[old]
                del tag[old]
                value.desc = k.upper()
                tag[new] = value
                dirty = True

    if dirty:
        tag.save()
        n_bad += 1
    else:
        n_good += 1

print("done (%d good files, %d bad)" % (n_good, n_bad))
