#!/usr/bin/env perl
use warnings;
use strict;
use open qw(:std :utf8);
use utf8;
use Net::Netrc;
use LWP::Simple;
use JSON;
use Data::Dumper;

my $api_key;
my $user;
my $client;

sub _get_netrc {
	my ($host) = @_;
	my $en = Net::Netrc->lookup($host);
	if ($en && $en->{machine}) {
		return $en;
	}
}

sub get_api_key {
	my $host = "api.last.fm";
	my $en = _get_netrc($host);
	if ($en && $en->{password}) {
		return $en->{password};
	} else {
		die "could not find API key for '$host'\n";
	}
}

sub getRecentTracks {
	my ($user) = @_;

	my $raw = get('http://ws.audioscrobbler.com/2.0/'.
			'?method=user.getrecenttracks'.
			'&limit=1'.
			'&user='.$user.
			'&format=json'.
			'&api_key='.$api_key);

	return from_json($raw);
}

$api_key = get_api_key();

for my $user (@ARGV) {
	my $data = getRecentTracks($user);
	my $track = $data->{recenttracks}->{track};
	print Dumper($track);
	my $artist = $track->{artist}->{"#text"};
	my $song = $track->{name};
	print "$user now playing: $artist – $song\n";
}
