#!/usr/bin/env python
# A barebones parser for OBML files used by Opera Mini
#
# (c) 2014–2016 Mantas Mikulėnas <grawity@gmail.com>
# Released under the MIT Expat License
#
# Originally intended to extract original URLs from saved pages, after Opera dropped
# binary compatibilty between minor releases and left me with a bunch of unreadable
# saved pages in v15 — and it does that.
#
# An attempt to document the file format is at:
#   https://gist.github.com/grawity/702b31cddcc5a6622724

import base64
import os
import struct
import sys
import urllib.parse

from pprint import pprint

class Parser():
    def __init__(self, path):
        self.path = path
        self.fh = open(path, 'rb')
        self.url_base = "\0"
        self.last_x = 0
        self.last_y = 0

    def debug(self, typ, data):
        if os.environ.get("DEBUG"):
            c_on = "\033[33m" if sys.stdout.isatty() else ""
            c_off = "\033[m" if sys.stdout.isatty() else ""
            print(c_on, "#", typ, repr(data), c_off)
        return data

    # primitives

    def read(self, length):
        buf = self.fh.read(length)
        if len(buf) < length:
            raise IOError("Hit EOF after %d/%d bytes" % (len(buf), length))
        return self.debug("raw[%d]" % length, buf)

    def read_byte(self):
        length = 1
        buf = self.fh.read(length)
        if len(buf) < length:
            raise IOError("Hit EOF after %d/%d bytes" % (len(buf), length))

        data, = struct.unpack('>B', buf)
        return self.debug("byte", data)

    def read_short(self):
        length = 2
        buf = self.fh.read(length)
        if len(buf) < length:
            raise IOError("Hit EOF after %d/%d bytes" % (len(buf), length))

        data, = struct.unpack('>H', buf)
        return self.debug("short", data)

    def read_medium(self):
        length = 3
        buf = self.fh.read(length)
        if len(buf) < length:
            raise IOError("Hit EOF after %d/%d bytes" % (len(buf), length))

        data_hi, data_lo = struct.unpack('>BH', buf)
        return self.debug("medium", (data_hi << 16) | data_lo)

    def read_blob(self):
        length = self.read_short()
        buf = self.fh.read(length)
        if len(buf) < length:
            raise IOError("Hit EOF after %d/%d bytes" % (len(buf), length))

        return self.debug("chunk[%d]" % length, buf)

    # other data types

    def read_string(self):
        buf = self.read_blob()
        buf = buf.decode('utf-8')
        return self.debug("-> str[%d]" % len(buf), buf)

    def read_url(self, base=None):
        buf = self.read_string()
        if buf and buf[0] == "\0":
            if not base:
                base = self.url_base
            buf = base + buf[1:]
        return self.debug("-> url[%d]" % len(buf), buf)

    def read_color(self):
        a = self.read_byte()
        r = self.read_byte()
        g = self.read_byte()
        b = self.read_byte()
        return self.debug("-> color[argb]", (a, r, g, b))

    def read_coords(self, rel_to_abs=False):
        x = self.read_short()
        y = self.read_medium()
        if rel_to_abs:
            self.last_x = x = (self.last_x + x) & 0xFFFF
            self.last_y = y = (self.last_y + y) & 0xFFFFFF
        else:
            # in v15+, all positions are relative and never depend on
            # earlier absolute coordinates (which are only used for sizes)
            pass
        return self.debug("-> coords[%s]" % ("rel" if rel_to_abs else "abs"), (x, y))

def infinity(start=0):
    i = start
    while True:
        yield i
        i += 1

def strhex(buf):
    return " ".join(["%02X" % x for x in buf])

def rgba(argb_tuple):
    a, r, g, b = argb_tuple
    if a == 0 or a == 255:
        return "rgb(%d, %d, %d)" % (r, g, b)
    else:
        return "rgba(%d, %d, %d, %.3f)" % (r, g, b, a/255)

def data_url(buf):
    if buf.startswith(b"\x89PNG\r\n"):
        img_type = "image/png"
    elif buf.startswith(b"\xff\xd8"):
        img_type = "image/jpeg"
    else:
        img_type = "application/octet-stream"
    encoded = base64.b64encode(buf)
    encoded = urllib.parse.quote(encoded)
    return "data:%s;base64,%s" % (img_type, encoded)

def css_imgdata(buf):
    return "url('%s')" % data_url(buf)

def parse_file(arg):
    print("file =", arg)

    f = Parser(arg)

    expected_size = f.read_medium()
    version = f.read_byte()
    print("version =", version)

    if version == 16:
        assert(expected_size == 0x02d355)
        expected_size = f.read_medium()
        version = f.read_byte()
        exp_total_bytes = expected_size + 7
    elif version == 15:
        raise ValueError("bad header for version %r" % version)
    else:
        exp_total_bytes = expected_size + 3

    exp_links_bytes = 0

    if version not in {12, 13, 15, 16}:
        raise ValueError("unknown version %r" % version)

    page_size = f.read_coords()
    if version == 16:
        assert(f.read(2) in {b'\x00\x00', b'\xff\xff'})
    else:
        assert(f.read(5) == b'S\x00\x00\xff\xff')
    page_title = f.read_string()
    f.read_blob() # 'C\x10\x10...' on v15, nil elsewhere
    f.url_base = f.read_string()
    page_url = f.read_url()
    yield {"_type": "head",
           "title": page_title,
           "url": page_url,
           "dimensions": page_size}

    if version >= 15:
        f.read(6)
    else:
        f.read_short()
        f.read_medium()

    # metadata section

    while True:
        print("--- metadata [%d] ---" % f.fh.tell())
        type = f.read(1)
        if None:
            pass
        elif type == b"C":
            if version >= 15:
                f.read(23)
            else:
                raise ValueError("unhandled metadata chunk %r/v%r" % (type, version))
        elif type == b"M":
            f.read(2)
            f.read_blob()
        elif type == b"S":
            exp_links_bytes = f.read_medium()
            break
        else:
            raise ValueError("unknown metadata chunk %r" % type)

    print("section 1 ends at %d" % f.fh.tell())

    # link sub-section

    links_start = f.fh.tell()
    links_end = f.fh.tell() + exp_links_bytes

    while f.fh.tell() < links_end:
        print("--- links [%d] ---" % f.fh.tell())
        type = f.read(1)
        if None:
            pass
        elif type == b"\x00":
            # <option> selections
            f.read(1)
            n = f.read_byte()
            options = []
            for j in range(n):
                opt_val = f.read_string()
                opt_text = f.read_string()
                options.append((opt_val, opt_text))
            yield {"_type": "option_list",
                   "data": options}
        elif type in {b"i", b"L", b"P", b"w", b"W"}:
            # shared 'region' format
            n = f.read_byte()
            boxes = []
            for j in range(n):
                pos = f.read_coords()
                size = f.read_coords()
                boxes.append((pos, size))
            if version >= 15:
                link_url = f.read_url()
                assert(f.read(2) == b"\x01t")
                link_type = f.read_string()
            elif version == 13:
                link_url = f.read_url()
                f.read(2)
                link_type = f.read_string()
            elif version == 12:
                link_type = f.read_string()
                link_url = f.read_url()
            if type == b"i":
                for pos, size in boxes:
                    if size[0] > 16 and size[1] > 16:
                        yield {"_type": "link",
                               "kind": "image",
                               "href": link_url,
                               "type": link_type,
                               "pos": pos,
                               "size": size}
            else:
                if not link_url.startswith("b:"):
                    for pos, size in boxes:
                        yield {"_type": "link",
                               "href": link_url,
                               "type": link_type,
                               "pos": pos,
                               "size": size}
        elif type in {b"C", b"I", b"N", b"S"} and version >= 15:
            # shared 'region' format
            n = f.read_byte()
            for j in range(n):
                pos = f.read_coords()
                size = f.read_coords()
            f.read_blob()
            assert(f.read(2) == b"\x01t")
            f.read_blob()
        elif type in {b"S"} and version == 13:
            # shared 'region' format
            n = f.read_byte()
            for j in range(n):
                pos = f.read_coords()
                size = f.read_coords()
            f.read_blob()
            f.read(2)
            f.read_blob()
        elif type == b"C" and version == 12:
            f.read(24)
        elif type in {b"I", b"S"} and version == 12:
            # shared 'region' format
            n = f.read_byte()
            for j in range(n):
                pos = f.read_coords()
                size = f.read_coords()
            f.read_blob()
            f.read_blob()
        else:
            raise ValueError("unknown link chunk %r/v%r" % (type, version))

    print("section 2 ends at %d" % f.fh.tell())
    if f.fh.tell() != links_end:
        raise ValueError("link section ended at %d, expected %d" % (f.fh.tell(), links_end))

    # content section

    content_start = f.fh.tell()
    content_end = exp_total_bytes

    while f.fh.tell() < content_end:
        print("--- content [%d] ---" % f.fh.tell())
        type = f.read(1)
        if None:
            pass
        elif type == b"o":
            if version >= 15:
                # TODO: not sure if actual type or just part of preceding "I"-block
                f.read_blob()
            else:
                raise ValueError("unhandled content chunk %r/v%r" % (type, version))
        elif type == b"B":
            if version >= 15:
                pos = f.read_coords(rel_to_abs=True)
                size = f.read_coords()
                color = f.read_color()
            else:
                pos = f.read_coords()
                size = f.read_coords()
                color = f.read_color()
            yield {"_type": "box",
                   "pos": pos,
                   "size": size,
                   "fill": color}
        elif type == b"F":
            if version >= 15:
                pos = f.read_coords(rel_to_abs=True)
                size = f.read_coords()
                color = f.read_color()
            else:
                pos = f.read_coords()
                size = f.read_coords()
                color = f.read_color()
            field_type = f.read(1)
            f.read(1)
            field_id = f.read_string()
            field_value = f.read_string()
            if version >= 15:
                f.read(5)
            else:
                f.read(3)
            if field_type in {b"c", b"r"}:
                # hack
                pos = (pos[0] - 8, pos[1] - 8)
                size = (size[0] + 8, size[1] + 8)
            yield {"_type": "input",
                   "kind": {
                       b"a": "textarea",
                       b"c": "checkbox",
                       b"r": "radio",
                       b"s": "select",
                       b"x": "text",
                   }.get(field_type),
                   "value": field_value,
                   "pos": pos,
                   "size": size,
                   "color": color}
        elif type == b"I":
            addr = 0
            if version == 16:
                pos = f.read_coords(rel_to_abs=True)
                size = f.read_coords()
                color = f.read_color()
                addr = f.read_medium()
                assert(f.read(2) == b"\x01c")
                assert(len(f.read_blob()) == 4)
            elif version == 15:
                pos = f.read_coords(rel_to_abs=True)
                size = f.read_coords()
                color = f.read_color()
                f.read(14)
            else:
                pos = f.read_coords()
                size = f.read_coords()
                color = f.read_color()
                f.read(3)
                addr = f.read_medium()
            yield {"_type": "box",
                   "kind": "image",
                   "pos": pos,
                   "size": size,
                   "fill": color,
                   "blob": addr}
        elif type == b"L":
            f.read(9)
        elif type == b"M":
            f.read(2)
            f.read_blob()
        elif type == b"S":
            exp_files_bytes = f.read_medium()
            files_start = f.fh.tell()
            files_end = f.fh.tell() + exp_files_bytes
            while f.fh.tell() < files_end:
                addr = f.fh.tell() - files_start
                buf = f.read_blob()
                yield {"_type": "file",
                       "addr": addr,
                       "data": buf}
            print("files started at %d, ends at %d" % (files_start, f.fh.tell()))
            if f.fh.tell() != files_end:
                raise ValueError("content.files section ended at %d, expected %d" % (f.fh.tell(), files_end))
        elif type == b"T":
            if version == 16:
                pos = f.read_coords(rel_to_abs=True)
                size = f.read_coords()
                color = f.read_color()
                f.read(1)
                font = 4 | (f.read_byte() & 1)
                n = f.read_byte()
                for j in range(n):
                    print("text link", f.read(1), f.read_blob())
                text = f.read_string()
            elif version == 15:
                pos = f.read_coords(rel_to_abs=True)
                size = f.read_coords()
                color = f.read_color()
                font = f.read_byte()
                text = f.read_string()
            else:
                pos = f.read_coords()
                size = f.read_coords()
                color = f.read_color()
                font = f.read_byte()
                text = f.read_string()
            yield {"_type": "text",
                   "text": text,
                   "font": font,
                   "color": color,
                   "pos": pos,
                   "size": size}
        else:
            raise ValueError("unknown content chunk %r/v%r" % (type, version))

    print("section 3 started at %d, ends at %d" % (content_start, f.fh.tell()))
    if f.fh.tell() != content_end:
        raise ValueError("content section ended at %d, expected %d" % (f.fh.tell(), content_end))

font_sizes = {
    0: "11px", # medium
    2: "12px", # large
    4: "13px", # extra large
    6: "10px", # small
}

for arg in sys.argv[1:]:
    with open("%s.html" % arg, "w") as fout:
        id_alloc = iter(infinity())
        imgboxes = {}
        option_lists = {}
        n_option_lists = iter(infinity())
        n_select_fields = iter(infinity())

        fout.write('<!DOCTYPE html>\n')
        fout.write('<meta charset="utf-8">\n')
        fout.write('<style>\n'
                   'html {\n'
                   '  background: #ddd;\n'
                   '}\n'
                   '.item {\n'
                   '  position: absolute;\n'
                   '}\n'
                   '.body {\n'
                   '  background: white;\n'
                   '  z-index: -200;\n'
                   '}\n'
                   '.box {\n'
                   '  z-index: -100;\n'
                   '}\n'
                   '.img {\n'
                   '  z-index: -50;\n'
                   '}\n'
                   '.link {\n'
                   '  display: block;\n'
                   '  text-decoration: none;\n'
                   '  z-index: 100;\n'
                   '}\n'
                   '.link:hover {\n'
                   '  outline: 1px solid blue;\n'
                   '}\n'
                   '.imglink {\n'
                   '  color: gray;\n'
                   '  z-index: 150;\n'
                   '}\n'
                   '.text, .field {\n'
                   '  font-family: sans-serif;\n'
                   '  font-size: 11px;\n'
                   '  line-height: 1.1;\n'
                   '  white-space: pre;\n'
                   '}\n'
                   '.form {\n'
                   '  border: none;\n'
                   '  padding: none;\n'
                   '}\n'
                   '</style>\n')
        for item in parse_file(arg):
            type = item["_type"]
            pprint(item)
            if type == "head":
                fout.write('<!-- origin: %s -->\n' % item["url"])
                fout.write('<title>%s</title>\n' % item["title"])
                page_w, page_h = item["dimensions"]
                style = [
                    "left: %dpx" % 0,
                    "top: %dpx" % 0,
                    "width: %dpx" % page_w,
                    "height: %dpx" % page_h,
                ]
                style = "; ".join(style)
                fout.write('<div class="item body" style="%s"></div>' % style)
            elif type == "text":
                item_x, item_y = item["pos"]
                item_w, item_h = item["size"]
                font_size = item["font"] & ~1
                font_weight = item["font"] & 1
                style = [
                    "font-size: %s" % font_sizes[font_size],
                    "font-weight: %s" % ("bold" if font_weight else "normal"),
                    "color: %s" % rgba(item["color"]),
                    "left: %dpx" % item_x,
                    "top: %dpx" % item_y,
                    "width: %dpx" % item_w,
                    "height: %dpx" % item_h,
                ]
                style = "; ".join(style)
                fout.write('<div class="item text" style="%s">' % style)
                fout.write(item["text"])
                fout.write('</div>\n')
            elif type == "box":
                item_x, item_y = item["pos"]
                item_w, item_h = item["size"]
                style = [
                    "background-color: %s" % rgba(item["fill"]),
                    "left: %dpx" % item_x,
                    "top: %dpx" % item_y,
                    "width: %dpx" % item_w,
                    "height: %dpx" % item_h,
                ]
                style = "; ".join(style)
                if item.get("kind") == "image":
                    box_id = "imgbox_%d" % next(id_alloc)
                    fout.write('<div class="item img" style="%s" id="%s"></div>\n' % (style, box_id))
                    imgboxes.setdefault(item["blob"], []).append(box_id)
                else:
                    fout.write('<div class="item box" style="%s"></div>\n' % style)
            elif type == "option_list":
                list_id = next(n_option_lists)
                option_lists[list_id] = item["data"]
            elif type == "input":
                item_x, item_y = item["pos"]
                item_w, item_h = item["size"]
                style = [
                    "color: %s" % rgba(item["color"]),
                    "left: %dpx" % item_x,
                    "top: %dpx" % item_y,
                    "width: %dpx" % item_w,
                    "height: %dpx" % item_h,
                ]
                style = "; ".join(style)
                if item["kind"] == "textarea":
                    fout.write('<textarea class="item form field" style="%s">%s</textarea>\n' % (style, item["value"]))
                elif item["kind"] == "text":
                    fout.write('<input class="item form field" style="%s" type="text" value="%s">\n' % (style, item["value"]))
                elif item["kind"] in {"checkbox", "radio"}:
                    fout.write('<input class="item form" style="%s" type="%s" value="%s">\n' % (style, item["kind"], item["value"]))
                elif item["kind"] == "select":
                    list_id = next(n_select_fields)
                    fout.write('<select class="item field" style="%s">\n' % style)
                    for opt_id, opt_text in option_lists[list_id]:
                        fout.write('<option>%s</option>\n' % opt_text)
                    fout.write('</select>\n')
            elif type == "link":
                item_x, item_y = item["pos"]
                item_w, item_h = item["size"]
                if item.get("kind") == "image":
                    klass = "link imglink"
                    style = [
                        "left: %dpx" % item_x,
                        "top: %dpx" % item_y,
                    ]
                    text = "↖"
                else:
                    klass = "link"
                    style = [
                        "left: %dpx" % item_x,
                        "top: %dpx" % item_y,
                        "width: %dpx" % item_w,
                        "height: %dpx" % item_h,
                    ]
                    text = ""
                style = "; ".join(style)
                fout.write('<a class="item %s" href="%s" style="%s">%s</a>\n' % (klass, item["href"], style, text))
            elif type == "file":
                fout.write('<script>\n')
                box_ids = imgboxes.get(item["addr"])
                if box_ids:
                    fout.write('var bg = "%s";\n' % css_imgdata(item["data"]))
                    for box_id in box_ids:
                        fout.write('var div = document.getElementById("%s");\n' % box_id)
                        fout.write('div.style.backgroundImage = bg;\n')
                        fout.write('div.style.backgroundColor = "";\n')
                fout.write('</script>\n')
