#!/usr/bin/env perl
use warnings;
use strict;
use feature 'switch';
use feature 'say';
use Net::DBus;
use Data::Dumper;

my $bus;

my %commands = (
	status => sub {
		my ($svc, @ARGV) = @_;

	},

	next => sub {
		my ($svc, @ARGV) = @_;
		my $player = 
);

$bus = Net::DBus->session;

my $player_name = shift(@ARGV) // usage();
my $player_bus_name = "org.mpris.MediaPlayer2.$player_name";

my $mp_svc = $bus->get_service($player_bus_name);
my $mp_obj = $mp_svc->get_object("/org/mpris/MediaPlayer2");
my $player_obj = $mp_svc->get_object("/org/mpris/MediaPlayer2/Player");

$commands{shift(@ARGV)}->($player_svc, @ARGV);
