#!/usr/bin/env bash
# url-file-handler - Windows "Internet Shortcut" file handler

parse() {
	local file=$1
	local line=
	local url=

	[[ -f $file ]] || return 1

	while read -r line; do
		line=${line%$'\n'}
		line=${line%$'\r'}
		case $line in
			# also handle Sony-Ericsson vCard syntax
			URL[:=]*)
				url=${line#URL?}
				break
				;;
		esac
	done <"$file"

	[[ $url ]] && xdg-open "$url"
}

msg=$(parse "$1" 2>&1) || {
	[[ $msg ]] || msg="Invalid Internet shortcut."
	zenity --error --title "$file" --text "$msg"
	echo "$file: $msg" >&2
	exit 1
}
