#!/usr/bin/env bash
# Update mpc database, adding all songs to the playlist, sorted by title
#. ~/lib/util.sh
current=$(mpc current -f '%file%')
mpc -q --wait update && {
	BASH_XTRACEFD=42
	mpc -q crop || mpc -q clear
	mpc add /
# sort playlist by title and artist
	sorted=$(mktemp)
	mpc playlist -f '%title%[ - %artist%]\b%file%' \
		| sed 1d | sort -t $'\b' -k 1 | cut -d $'\b' -f 2- > "$sorted"
	mpc -q crop || mpc -q clear
	mpc add < "$sorted"
	rm -f "$sorted"
# remove duplicate of currently played song
	[[ $current ]] && mpc playlist -f '%file%' \
		| grep -Fxn "$current" | sed '1d; s/:.*//' | mpc del
	true
} 42>&2 >/dev/null 2>&1
