#!/usr/bin/env bash
# /etc/initramfs/post-update.d/copy-kernel

ESP=/boot/efi

if ! mountpoint -q "$ESP"; then
	echo "ESP not mounted at $ESP!" >&2
	exit 1
fi

if [[ -e /etc/os-release ]]; then
	os_release=/etc/os-release
elif [[ -e /usr/lib/os-release ]]; then
	os_release=/usr/lib/os-release
else
	echo "/usr/lib/os-release not found or invalid; see os-release(5)"
fi

version=$1
initrd_path=$2
kernel_path=/boot/vmlinuz-$version

osname=$(. "$os_release" && echo "${PRETTY_NAME:-$NAME}" | sed 's/ (.*//')
machineid=$(dbus-uuidgen --get 2>/dev/null || echo unknown)
options=$(cat /etc/kernel/cmdline | grep "^[^#]" | tr -s "\n" " ")

echo "Copying kernel $version to EFI system partition"

cp -v "$initrd_path" "$ESP/EFI/ubuntu/initrd.img"
cp -v "$kernel_path" "$ESP/EFI/ubuntu/vmlinuz.efi"

echo "Generating boot loader entry for $osname ($version)"

cat > "$ESP/loader/entries/ubuntu.conf" <<!
title		$osname
version		$version
machine-id	$machineid
linux		\\EFI\\ubuntu\\vmlinuz.efi
initrd		\\EFI\\ubuntu\\initrd.img
options		$options
!
