#!/usr/bin/env bash

do_host=0
do_mach=0
do_os=0

while getopts 'hmo' OPT; do
	case $OPT in
		'h')	do_host=1;;
		'm')	do_mach=1;;
		'o')	do_os=1;;
	esac
done

do_mach+=$(( ! (do_host+do_mach+do_os) ))

if (( do_host )); then
	echo "$HOSTTYPE"
fi
if (( do_mach )); then
	echo "$MACHTYPE"
fi
if (( do_os )); then
	echo "$OSTYPE"
fi
