#!/usr/bin/env bash
service='host'
fqdn=$(hostname -f)
principal=''
keytab='/etc/krb5.keytab'
owner=''
ccname=''
command=()
runcommand=false

while getopts 'c:k:s:u:' OPT; do
	case $OPT in
	c) ccname=$OPTARG;;
	k) keytab=$OPTARG;;
	s) service=$OPTARG;;
	u) owner=$OPTARG;;
	*) exit 2;;
	esac
done

command=("${@:$OPTIND}")

(( ${#command[@]} )) &&
	runcommand=true

[[ ! $principal ]] &&
	principal="$service/$fqdn"

if [[ ! $ccname ]]; then
	ccname='/tmp/krb5cc_host'

	[[ $service != "host" ]] &&
		ccname+="_$service"

	$runcommand &&
		ccname=$(mktemp "${ccname}_XXXXXXXX")
fi

export KRB5CCNAME=$ccname

if [[ -d /run/lock ]]; then
	lockdir=/run/lock
else
	lockdir=/var/lock
fi

lockfile=${ccname#FILE:}
lockfile=${lockfile//'/'/'-'}
lockfile=$lockdir/host-kinit.${lockfile#'-'}

args=(
	-k "$KRB5CCNAME"	# explicit ccache for `ps`
	-L -b -K 30		# syslog, daemon, check every 30m
	-f "$keytab"		# credentials
	-u "$principal"		# principal
	-F -P			# not forwardable, not proxiable
)

if [[ $owner ]]; then
	args+=( -o "$owner" )
fi

if ! { exec {lockfd}>"$lockfile" && flock -x -n $lockfd; }; then
	echo "Failed to obtain lock on $lockfile, exiting"
	exit 1
fi

if $runcommand; then
	args+=( -q )		# quiet
	args+=( -- "${command[@]}" )
	k5start "${args[@]}"
	kdestroy
else
	exec k5start "${args[@]}"
fi
