#!/usr/bin/env bash
service='host'
fqdn=$(fqdn || hostname -f)
principal=$service/$fqdn
keytab=/etc/krb5.keytab

if [ $service == "host" ]; then
	ccname="host"
else
	ccname="host_$service"
fi
export KRB5CCNAME="/tmp/krb5cc_$ccname"

args=(	-k "$KRB5CCNAME"	# explicit ccache for `ps`
	-b -L -K 30		# daemonize, syslog, check every 30m
	-f "$keytab"		# credentials
	-u "$principal"		# principal
	-F -P			# not forwardable, not proxiable
	)

exec k5start "${args[@]}"
