#!/usr/bin/env bash
# kadm - run kadmin with current identity

. lib.bash || exit

client=$(pklist -P)
realm=${client##*@}
ccname=${KRB5CCNAME:-$(pklist -N)}

while getopts ":r:" OPT; do
	case $OPT in
	r) realm=$OPTARG;;
	*) lib::die_getopts;;
	esac
done; shift $((OPTIND-1))

service="kadmin/admin@$realm"

if kvno -q "$service"; then
	debug "using existing ccache '$ccname'"
	kadmin -r "$realm" -p "$client" -c "$ccname" "$@"
else
	notice "could not obtain ticket for '$service'"
	kadmin -r "$realm" -p "$client" "$@"
fi
