#!/usr/bin/env bash
# kadm - run kadmin with current identity

princ=$(pklist -P)
realm=${princ##*@}

if kvno -q "kadmin/admin@$realm"; then
	kadmin -r "$realm" -p "$princ" -c "${KRB5CCNAME:-$(pklist -N)}" "$@"
else
	kadmin -r "$realm" -p "$princ" "$@"
fi
