#!/usr/bin/env bash

if [[ $1 == -f ]]; then
	# Running from PAM
	(su -l -c "'$0'" "$PAM_USER" |& logger -p user.debug -t pkinit) &
	exit
fi

err() { echo "error: $*" >&2; false; }
die() { err "$@"; exit; }

opt_identity=
opt_principal=

while getopts "I:P:" OPT; do
	case $OPT in
	I) opt_identity=$OPTARG;;
	P) opt_principal=$OPTARG;;
	esac
done; shift $((OPTIND-1))

if [[ ! $opt_principal ]]; then
	opt_principal="$(whoami)@$(pklist -R)"
	if [[ $opt_principal == *@ ]]; then
		die "could not determine default realm"
	fi
fi

if [[ -f $opt_identity ]]; then
	opt_identity="FILE:$(realpath -s "$opt_identity")"
fi

kinit -X "X509_user_identity=$opt_identity" "$@" "$opt_principal"
