#!/usr/bin/env bash

shopt -s nullglob

n=${1:-1}			# number of blinks
t_on=${2:-0.1}			# on duration
t_off=${3:-0.1}			# off duration
restore=1			# whether to return back to original state

if [[ $n == *+ ]]; then
	n=${n%+}
	restore=0
fi

declare -a paths=(/sys/class/leds/*::capslock/brightness)
declare -A saved=()

do_restore() {
	for led in "${paths[@]}"; do
		echo ${saved[$led]-0} > $led
	done
}

do_save() {
	for led in "${paths[@]}"; do
		saved[$led]=$(< $led)
	done
}

if (( ! ${#paths[@]} )); then
	exit
fi

do_save
trap 'do_restore; exit' INT QUIT
for (( i=1; i < n*2+restore; i++ )); do
	for led in "${paths[@]}"; do
		echo $(( (i + saved[$led]) % 2 )) > $led
	done
	if (( i == n*2 )); then
		true
	elif (( i % 2 )); then
		sleep $t_on
	else
		sleep $t_off
	fi
done
if (( restore )); then
	do_restore
fi
