#!/usr/bin/env python
# encoding: utf-8
from __future__ import division, print_function
import os
import sys
import subprocess

thresholds = [
    ( 10, ( 76, 10)),
    (  5, (226, 11)),
    (  0, (196,  9)),
    ( -1, (255,  7)),
]

def homely(path):
    path = path.rstrip("/")
    home = os.environ.get("HOME", "").rstrip("/")
    media = "/run/media/%s" % os.environ.get("LOGNAME", "root")
    if path == home:
        return "~"
    elif (path + "/").startswith(home + "/"):
        return "~" + path[len(home):]
    elif (path + "/").startswith(media + "/"):
        return "…" + path[len(media):]
    else:
        return path or "/"

def human(n, d=1, u=1024):
    cs = "BkMGTEP"
    e = 0
    while n >= u:
        n /= u
        e += 1
    c = cs[e]
    return "%.*f%s" % (d, n, c)

def percent(n, digits):
    if round(n, digits) < 100:
        return "%*.*f%%" % (digits+2, digits, n)
    else:
        return "%*.*f%%" % (digits+1, digits-1, n)

def ansify(text, fmt):
    return "\033[%sm%s\033[m" % (fmt, text) if fmt else text

def gauge(width, level, full="▓", empty="░", color="", full_color="", empty_color=""):
    cells = int(width * level / 100)

    return ansify(full * cells, full_color or color) \
         + ansify(empty * (width - cells), empty_color or color)

def gauge2(width, level, color="37"):
    return gauge(width, level,
                 full="|", full_color="1;%s" % color,
                 empty="|", empty_color="2;%s" % color)

def gauge3(width, level,
           full_char="█", partial_char="▌", empty_char=" ",
           full_fmt="", partial_fmt="", empty_fmt=""):

    cells = width * level / 100
    n_full = int(cells)
    n_partial = int(round(cells % 1))
    n_empty = int(width - n_full - n_partial)

    return ansify(full_char    * n_full,    full_fmt) \
         + ansify(partial_char * n_partial, partial_fmt) \
         + ansify(empty_char   * n_empty,   empty_fmt)

def rgb_split(color):
    r = (color - 16) // 6 // 6 % 6
    g = (color - 16) // 6 % 6
    b = (color - 16) % 6
    return (r, g, b)

def rgb_merge(r, g, b):
    return (r * 6 * 6) + (g * 6) + b + 16

def darken(color, n):
    if 0 <= color <= 7:
        return color
    elif 8 <= color <= 15:
        return color - 8 if n > 0 else color
    elif 16 <= color <= 232:
        r, g, b = rgb_split(color)
        r = max(r - n, 0)
        g = max(g - n, 0)
        b = max(b - n, 0)
        return rgb_merge(r, g, b)
    elif 232 <= color <= 255:
        return max(color - 3*n, 232)

def gauge3x(width, level, color, bars=None):
    bright = color
    dark = darken(color, 1)

    if not bars:
        if os.getenv("TERM") == "linux":
            bars = "#=-"
        else:
            bars = u"\u275a", u"\u275a", u"\u2758"
    elif len(bars) != 3:
        bars = bars[0] * 3

    return gauge3(width, level, *bars,
                    full_fmt="38;5;%d" % bright,
                    partial_fmt="2;38;5;%d" % dark,
                    empty_fmt="2;38;5;%d" % dark)

def threshold(level):
    for tmin, tval in thresholds:
        if level >= tmin:
            return tval
    return tval

def unescape_mtab(val):
    out = ""
    state = 0
    num = 0
    acc = 0
    for char in val:
        if state == 0:
            if char == "\\":
                num = 0
                acc = 0
                state = 1
            else:
                out += char
        elif state == 1:
            num += 1
            acc = (acc << 3) | int(char)
            if num == 3:
                out += chr(acc)
                state = 0
    return out

def enum_mtab():
    skip_fstypes = {
        "afs", "cgroup", "devpts", "devtmpfs", "ecryptfs", "efivarfs", "rootfs", "tmpfs",
    }
    skip_mounts = {
        "/boot", "/boot/efi",
    }
    include_mounts = {
        "/run/user/%d" % os.getuid(),
        "/tmp",
    }
    with open("/etc/mtab") as fh:
        for line in fh:
            dev, mtpt, fstype, rest = line.strip().split(None, 3)
            mtpt = unescape_mtab(mtpt)
            if mtpt in skip_mounts:
                continue
            elif fstype in skip_fstypes and mtpt not in include_mounts:
                continue
            else:
                yield mtpt, fstype

dparts = sys.argv[1:]
mparts = []

if not dparts:
    for mtpt, fstype in enum_mtab():
        if fstype == "tmpfs":
            mparts.append(mtpt)
        else:
            dparts.append(mtpt)

mparts.sort()
dparts.sort()

quota = False

if quota:
    quota_gauge_width = 20
    disk_gauge_width = 10
    fmt = " %-16s %7s %7s %7s %-*s %5s %-*s %3s"
    header = (
        "PATH",
        "TOTAL",
        "FREE",
        "AVAIL",
        quota_gauge_width, "QUOTA USAGE",
        "",
        disk_gauge_width, "DISK USAGE",
        "",
    )
else:
    disk_gauge_width = 30
    fmt = " %-20s %7s %7s %7s %-*s %5s"
    header = (
        "PATH",
        "TOTAL",
        "USED",
        "FREE",
        disk_gauge_width, "",
        "",
    )

separator = ansify("-" * len(fmt % header), "2")

print(ansify(fmt, "1") % header)

def get_fs_devno(mtpt):
    proc = subprocess.Popen(["mountpoint", "-d", mtpt],
                            stdout=subprocess.PIPE)
    return proc.stdout.read().strip().decode("utf-8")

seen_devnos = set()

def dump_mtpt(mtpt):
    try:
        st = os.statvfs(mtpt)
    except PermissionError:
        return
    except OSError:
        return

    if st.f_blocks == 0:
        return

    devno = get_fs_devno(mtpt)
    if devno in seen_devnos:
        return
    seen_devnos.add(devno)

    total_bytes     = st.f_bsize * st.f_blocks
    free_bytes      = st.f_bsize * st.f_bfree
    avail_bytes     = st.f_bsize * st.f_bavail

    used_bytes      = total_bytes - free_bytes
    quota_bytes     = used_bytes + avail_bytes

    quota_part      = used_bytes / quota_bytes * 100
    disk_part       = used_bytes / total_bytes * 100

    quota_color     = threshold(100 - quota_part)[0]
    disk_color      = threshold(-1)[0]

    if quota:
        row = (
            homely(mtpt),

            human(total_bytes),
            human(free_bytes),
            human(avail_bytes),

            quota_gauge_width,
            gauge3x(quota_gauge_width, quota_part, quota_color),
            percent(quota_part, 1),

            disk_gauge_width,
            gauge3x(disk_gauge_width, disk_part, darken(disk_color, 2)),
            percent(disk_part, 0),
        )
    else:
        row = (
            homely(mtpt),

            human(total_bytes),
            human(used_bytes),
            human(free_bytes),

            disk_gauge_width,
            gauge3x(disk_gauge_width, quota_part, quota_color),
            percent(disk_part, 1),
        )

    print(fmt % row)

def dump_all():
    if dparts and mparts:
        pass
        #print(separator)

    for mtpt in dparts:
        dump_mtpt(mtpt)

    if dparts and mparts:
        print(separator)

    for mtpt in mparts:
        dump_mtpt(mtpt)

dump_all()
