#!/usr/bin/env python3
# encoding: utf-8
import json
import os
import sys
import subprocess
from argparse import ArgumentParser
from nullroute.core import Core, Env
from nullroute.misc import fmt_size_short
from socket import gethostname

level_colors = {
    "red":      (196,  9),
    "yellow":   (226, 11),
    "green":    ( 76, 10),
    "gray":     (240,  7),
}

levels_small = [
    ( 10, "green"),
    (  5, "yellow"),
    (  0, "red"),
    ( -1, "gray"),
]

levels_big = [
    ( 10, "green"),
    (  2, "yellow"),
    (  0, "red"),
    ( -1, "gray"),
]

KIND_NONE   = 0
KIND_ROOT   = 1
KIND_HOME   = 2
KIND_MEDIA  = 3
KIND_MEMORY = 4
KIND_NET    = 5
KIND_SYSTEM = 6
KIND_KERNEL = 7

fs_kind_names = {
    KIND_HOME:      "home",
    KIND_MEDIA:     "media",
    KIND_NONE:      "-",
    KIND_ROOT:      "root",
    KIND_SYSTEM:    "system",
    KIND_NET:       "net",
    KIND_MEMORY:    "memory",
    KIND_KERNEL:    "kernel",
}

fs_kind_priorities = {
    KIND_HOME:      100,
    KIND_MEDIA:     50,
    KIND_NONE:      1,
    KIND_ROOT:      0,
    KIND_SYSTEM:    -1,
    KIND_NET:       -10,
    KIND_MEMORY:    -100,
    KIND_KERNEL:    -1000,
}

fs_kind_groups = {
    KIND_HOME:      1,
    KIND_MEDIA:     4,
    KIND_NONE:      1,
    KIND_ROOT:      1,
    KIND_NET:       5,
    KIND_MEMORY:    2,
    KIND_KERNEL:    3,
}

fs_kind_prefixes = [
    ("//%s/" % gethostname(),
                    KIND_KERNEL),
    ("//",          KIND_NET),
    ("/boot/",      KIND_SYSTEM),
    ("/dev/",       KIND_KERNEL),
    ("/efi/",       KIND_SYSTEM),
    ("/media/",     KIND_MEDIA),
    ("/n/",         KIND_NET),
    ("/proc/",      KIND_KERNEL),
    ("/run/media/", KIND_MEDIA),
    ("/run/user/",  KIND_MEMORY),
    ("/sys/",       KIND_KERNEL),
    ("/tmp/",       KIND_MEMORY),
    ("/home",       KIND_HOME),
    ("/",           KIND_ROOT),
]

fs_kind_fstypes = {
    "afs":          KIND_NET,
    "fuse.sshfs":   KIND_NET,
    "cgroup":       KIND_KERNEL,
    "devpts":       KIND_KERNEL,
    "devtmpfs":     KIND_KERNEL,
    "ecryptfs":     KIND_KERNEL,
    "efivarfs":     KIND_KERNEL,
    "rootfs":       KIND_KERNEL,
    "tmpfs":        KIND_MEMORY,
}

# not skipped even if kind or type would say otherwise
fs_noskip_mounts = {
    "/run/user/%d" % os.getuid(),
    "/tmp",
}

# always skipped
fs_skip_mounts = {
    #"/boot",
    #"/efi",
}
fs_skip_kinds = {
    KIND_KERNEL,
}
fs_skip_fstypes = {
    "afs", "cgroup", "devpts", "devtmpfs",
    "ecryptfs", "efivarfs", "rootfs", "tmpfs",
}

# skipped unless in verbose mode
fs_verbose_kinds = { KIND_SYSTEM, KIND_MEMORY }

# cached and shown even if not present
fs_cache_kinds = {
    KIND_ROOT,
    KIND_HOME,
    KIND_MEDIA,
}

class PersistentDict(dict):
    def __init__(self, path):
        self.path = path
        self.load()

    def load(self):
        try:
            with open(self.path, "r") as fh:
                data = json.load(fh)
            self.update(data)
        except FileNotFoundError as e:
            Core.debug("cache load failed (%r)" % e)

    def flush(self):
        try:
            with open(self.path, "w") as fh:
                json.dump(self, fh)
        except Exception as e:
            Core.debug("cache save failed (%r)" % e)

class Partition(object):
    def __init__(self, mtpt, fstype, cached=None):
        self.mtpt   = mtpt
        self.fstype = fstype
        self.cached = cached
        self.kind   = fs_kind_from_path(mtpt, fstype)

    def __repr__(self):
        kind = fs_kind_names.get(self.kind, self.kind)
        return "Partition(mtpt=%r, fstype=%r, cached=%r, kind=%r)" \
               % (self.mtpt, self.fstype, self.cached, kind)

    def can_skip(self):
        if self.mtpt in fs_skip_mounts:     return True
        if self.mtpt in fs_noskip_mounts:   return False
        if self.kind in fs_skip_kinds:      return True
        if self.fstype in fs_skip_fstypes:  return True
        return False

    def can_cache(self):
        return (self.kind in fs_cache_kinds)

    def get_fstat(self, seen_devnos):
        try:
            st = os.statvfs(self.mtpt)
        except (PermissionError, OSError) as e:
            Core.debug("skipping %r: could not statvfs: %r", self.mtpt, e)
            return

        if st.f_blocks == 0:
            Core.debug("skipping %r: f_blocks == 0", self.mtpt)
            return

        devno = get_fs_devno(self.mtpt)
        if devno in seen_devnos:
            Core.debug("skipping %r: devno %r already seen", self.mtpt, devno)
            return

        seen_devnos.add(devno)

        return {"total": st.f_bsize * st.f_blocks,
                "free":  st.f_bsize * st.f_bfree,
                "avail": st.f_bsize * st.f_bavail}

class MtabReader(object):
    def _unescape(self, val):
        out = ""
        state = num = acc = 0
        for char in val:
            if state == 0:
                if char == "\\":
                    num = acc = 0
                    state = 1
                else:
                    out += char
            elif state == 1:
                num += 1
                acc = (acc << 3) | int(char)
                if num == 3:
                    out += chr(acc)
                    state = 0
        return out

    def __iter__(self):
        with open("/etc/mtab") as fh:
            for line in fh:
                dev, mtpt, fstype, rest = line.strip().split(None, 3)
                mtpt = self._unescape(mtpt)
                yield dev, mtpt, fstype

class Enumerator(object):
    def __init__(self):
        self.cache = PersistentDict(Env.find_cache_file("diskuse.json"))
        self.seen_devnos = set()

    def _enum_partitions(self, show_cached=False):
        for dev, mtpt, fstype in MtabReader():
            yield Partition(mtpt, fstype)
        if show_cached:
            for mtpt, rest in self.cache.items():
                yield Partition(mtpt, rest["type"], cached=rest)

    def enum_partitions_system(self, show_cached=False):
        for part in self._enum_partitions(show_cached):
            if part.can_skip():
                Core.debug("skipping %r", part)
                continue
            Core.debug("adding %r", part)
            yield part

    def enum_partitions_exact(self, paths):
        for mtpt in paths:
            yield Partition(mtpt, fstype=None)

    def _add_to_cache(self, part, data):
        data = {**data, "type": part.fstype}
        mtpt = part.mtpt
        if part.kind != KIND_MEDIA:
            mtpt = "//" + gethostname() + mtpt
        self.cache[mtpt] = data

    def get_partition_data(self, part):
        if part.cached:
            return part.cached
        else:
            data = part.get_fstat(self.seen_devnos)
            if data and part.can_cache():
                self._add_to_cache(part, data)
            return data

    def close(self):
        self.cache.flush()

class Table(object):
    def __init__(self):
        self.columns = []
        self.rows = []

    def _make_header(self):
        out = ""
        for i, (head, type, width) in enumerate(self.columns):
            out += " %*s" % (width, head)
        return fmt_ansi(out, "1")

    def _make_separator(self):
        cols = 0
        for (head, type, width) in self.columns:
            cols += 1 + abs(width)
        return fmt_ansi("-" * cols, "2")

    def _make_row(self, values):
        out = ""
        cols = 0
        for i, (head, type, width) in enumerate(self.columns):
            if type == "string":
                cell_s = "%*s" % (width, values[i])
                cell_w = len(values[i])
            elif type == "gauge":
                percent, color = values[i]
                cell_s = gauge3x(abs(width), percent, color)
                cell_w = abs(width)

            out += " " + cell_s
            if cell_w > abs(width):
                out += "\n" + " " * (cols + 1 + abs(width))
            cols += 1 + cell_w
        return out

    def print(self):
        sep = self._make_separator() + "\n"
        out = self._make_header() + "\n"
        for row in self.rows:
            if row is None:
                out += sep
            else:
                out += self._make_row(row) + "\n"
        print(out, end="")

def get_user_name():
    return os.environ.get("LOGNAME", "root")

def get_home_dir():
    return os.path.expanduser("~")

def get_media_dir():
    return "/run/media/%s" % get_user_name()

def _get_cmd_output(*argv):
    proc = subprocess.Popen(argv, stdout=subprocess.PIPE)
    (out, err) = proc.communicate()
    return out.decode("utf-8").strip()

def get_dir_fsid(path):
    return _get_cmd_output("stat", "-f", "-c", "%i", path)

def get_fs_devno(mtpt):
    return _get_cmd_output("mountpoint", "-d", mtpt)

def fs_kind_from_path(path, fstype):
    if not path.endswith("/"):
        path += "/"
    if path == "/":
        home = get_home_dir()
        path_fsid = get_dir_fsid(path)
        home_fsid = get_dir_fsid(home)
        Core.debug("comparing fsid of %r vs %r", path, home)
        if (path_fsid == home_fsid) and (path_fsid != "0"):
            return KIND_HOME
        else:
            return KIND_ROOT

    fallback = KIND_NONE
    for prefix, kind in fs_kind_prefixes:
        if prefix == "/":
            fallback = kind
        elif prefix.endswith("/"):
            if path.startswith(prefix):
                return kind
        else:
            if path == prefix + "/":
                return kind
        # XXX: use a separate flag

    if fstype in fs_kind_fstypes:
        return fs_kind_fstypes[fstype]

    return fallback

def path_shorten(path):
    path = path.rstrip("/") + "/"
    home = get_home_dir().rstrip("/") + "/"
    media = get_media_dir().rstrip("/") + "/"
    if path == home:
        return "~"
    elif path == "/":
        return "/ (rootfs)"
    elif path.startswith(home):
        return "~/" + path[len(home):-1]
    elif path.startswith(media):
        return path[len(media):-1]
    else:
        return path[:-1]

def fmt_percent(n, digits):
    if round(n, digits) < 100:
        return "%*.*f%%" % (digits+2, digits, n)
    else:
        return "%*.*f%%" % (digits+1, digits-1, n)

def fmt_ansi(text, fmt):
    return "\033[%sm%s\033[m" % (fmt, text) if fmt else text

def gauge3(width, level,
           full_char="█", partial_char="▌", empty_char=" ",
           full_fmt="", partial_fmt="", empty_fmt=""):

    cells = width * level / 100
    n_full = int(cells)
    n_partial = int(round(cells % 1))
    n_empty = int(width - n_full - n_partial)

    return fmt_ansi(full_char    * n_full,    full_fmt) \
         + fmt_ansi(partial_char * n_partial, partial_fmt) \
         + fmt_ansi(empty_char   * n_empty,   empty_fmt)

def rgb_split(color):
    r = (color - 16) // 6 // 6 % 6
    g = (color - 16) // 6 % 6
    b = (color - 16) % 6
    return (r, g, b)

def rgb_merge(r, g, b):
    return (r * 6 * 6) + (g * 6) + b + 16

def darken(color, n):
    if 0 <= color <= 7:
        return color
    elif 8 <= color <= 15:
        return color - 8 if n > 0 else color
    elif 16 <= color <= 232:
        r, g, b = rgb_split(color)
        r = max(r - n, 0)
        g = max(g - n, 0)
        b = max(b - n, 0)
        return rgb_merge(r, g, b)
    elif 232 <= color <= 255:
        return max(color - 3*n, 232)

def gauge3x(width, level, color, bars=None):
    bright = color
    dark = darken(color, 1)

    if not bars:
        if os.getenv("TERM") == "linux":
            bars = "##-"
        else:
            bars = u"\u275a", u"\u275a", u"\u2758"
    elif len(bars) != 3:
        bars = bars[0] * 3

    return gauge3(width, level, *bars,
                    full_fmt="38;5;%d" % bright,
                    partial_fmt="2;38;5;%d" % dark,
                    empty_fmt="38;5;238")

def threshold(total, val):
    if total > 100e9:
        levels = levels_big
    else:
        levels = levels_small

    for tmin, tval in levels:
        if val >= tmin:
            return tval
    return tval

def dump_mtpt(part, data, with_quota=False):
    Core.debug("got %r", part)
    Core.debug("  - %r", data)

    total_bytes     = data["total"]
    free_bytes      = data["free"]
    avail_bytes     = data["avail"]

    used_bytes      = total_bytes - free_bytes
    quota_bytes     = used_bytes + avail_bytes

    quota_part      = used_bytes / quota_bytes * 100
    disk_part       = used_bytes / total_bytes * 100

    if part.cached:
        disk_color      = "gray"
        quota_color     = "gray"
    else:
        disk_color      = threshold(total_bytes, -1)
        quota_color     = threshold(quota_bytes, 100 - quota_part)

    Core.debug(" - total bytes=%r, used=%.2f%%, free=%.2f%%, color=%r",
               total_bytes, disk_part, 100-disk_part, disk_color)
    Core.debug(" - quota bytes=%r, used=%.2f%%, free=%.2f%%, color=%r",
               quota_bytes, quota_part, 100-quota_part, quota_color)

    disk_color      = level_colors[disk_color][0]
    quota_color     = level_colors[quota_color][0]

    if with_quota:
        row = (
            path_shorten(part.mtpt),

            fmt_size_short(total_bytes, si=opts.si),
            fmt_size_short(free_bytes, si=opts.si),
            fmt_size_short(avail_bytes, si=opts.si),

            (quota_part, quota_color),
            fmt_percent(quota_part, 1),

            (disk_part, darken(disk_color, 1)),
            fmt_percent(disk_part, 0),
        )
    else:
        row = (
            path_shorten(part.mtpt),

            fmt_size_short(total_bytes, si=opts.si),
            fmt_size_short(used_bytes, si=opts.si),
            fmt_size_short(free_bytes, si=opts.si),

            (quota_part, quota_color),
            fmt_percent(disk_part, 1),
        )

    return row

ap = ArgumentParser()
ap.add_argument("-a", "--all",
                action="store_true",
                help="show unimportant filesystems")
ap.add_argument("-c", "--cached",
                action="store_true",
                help="include nonpresent cached filesystems")
ap.add_argument("--si",
                action="store_true",
                help="use SI decimal units, not IEC binary units")
ap.add_argument("--quota",
                action="store_true",
                help="display quota information")
ap.add_argument("path", nargs="*")
opts = ap.parse_args()

if not opts.all:
    fs_noskip_mounts.clear()
    fs_skip_kinds |= fs_verbose_kinds

en = Enumerator()
if opts.path:
    partitions = en.enum_partitions_exact(opts.path)
else:
    partitions = en.enum_partitions_system(show_cached=opts.cached)
partitions = [*partitions]
partitions.sort(key=lambda x: x.mtpt)
partitions.sort(key=lambda x: fs_kind_priorities[x.kind], reverse=True)

t = Table()

if opts.quota:
    t.columns = [
        ("PATH",        "string", -16),
        ("TOTAL",       "string", 7),
        ("FREE",        "string", 7),
        ("AVAIL",       "string", 7),
        ("QUOTA USAGE", "gauge", -20),
        ("",            "string", 5),
        ("DISK USAGE",  "gauge", -10),
        ("",            "string", 3),
    ]
else:
    t.columns = [
        ("PATH",    "string", -20),
        ("TOTAL",   "string", 7),
        ("USED",    "string", 7),
        ("FREE",    "string", 7),
        ("",        "gauge", -30),
        ("",        "string", 5),
    ]

this_group = 0
seen_mtpts = set()
for part in partitions:
    if part.mtpt in seen_mtpts:
        continue
    data = en.get_partition_data(part)
    group = fs_kind_groups.get(part.kind)
    Core.debug("got %r (priority %r, group %r)", part.mtpt,
               fs_kind_priorities.get(part.kind, 0), group)
    row = dump_mtpt(part, data, opts.quota)
    if row:
        if this_group and group != this_group:
            t.rows.append(None)
        t.rows.append(row)
        this_group = group
        seen_mtpts.add(part.mtpt)

t.print()

en.close()
