#!/usr/bin/env perl
use Getopt::Long;
use Sys::Utmp qw(:constants);

sub hup_line {
	my ($tty) = @_;
	system("pkill", "-HUP", "-t", $tty);
}

my $quiet;

GetOptions(
	"q|quiet!" => \$quiet,
);

my $utmp = Sys::Utmp->new;
while (my $ut = $utmp->getutent) {
	my $t = $ut->ut_line;
	if ($ut->ut_type == USER_PROCESS) {
		my $h = $ut->ut_host;
		if ($h =~ /^mosh \[(\d+)\]$/) {
			print "detaching $t ($h)\n" unless $quiet;
			hup_line($t);
		}
	}
}
