#!/usr/bin/env python3
# swapusage -- Get current swap usage for all running processes
#
# (A port of shell-based `swapusage` tool by Erik Ljungstrom, Mikko
# Rantalainen, and Marc Methot.)
import glob
import os

fmt = "%9s kB  %s"
usage = []
total = 0
for dir in glob.glob("/proc/[0-9]*/"):
    pid = os.path.basename(dir.rstrip("/"))
    with open(f"{dir}/comm", "r") as fh:
        name = fh.read().strip()
    swap = 0
    with open(f"{dir}/status", "r") as fh:
        for line in fh:
            if line.startswith("VmSwap"):
                swap += int(line.split()[1])
    if swap > 0:
        usage += [(swap, name, pid)]
        total += swap
usage.sort()
for swap, name, pid in usage:
    print(fmt % (swap, f"{name} ({pid})"))
print(fmt % (total, "TOTAL"))
