#!/usr/bin/env bash

. lib.bash || exit

if have pacman; then
	sudo: pacman -Syu
elif have apt-get; then
	sudo: apt-get update
	sudo: apt-get dist-upgrade -V
else
	die "no known package manager found"
fi
