#!/usr/bin/env bash
# usb-status -- display USB power management status on Linux

fmt="%-10s %-54s %-4s %-10s %-10s\n"

printf "$fmt" "ID" "DEVICE" "AUTO" "RUNTIME" "STATUS"

for dev in /sys/bus/usb/devices/*; do
	if ! test -e $dev/power/autosuspend; then
		continue
	fi

	{ manu=$(< $dev/manufacturer) || manu="(unknown)"
	  prod=$(< $dev/product) || prod="${dev#/sys/bus/usb/devices/}"
	} 2> /dev/null

	autosusp=$(< $dev/power/autosuspend)
	rstat=$(< $dev/power/runtime_status)
	renab=$(< $dev/power/runtime_enabled)

	manu=${manu//"$(uname -sr)"/"$(uname -s)"}

	printf "$fmt" "${dev##*/}" "$manu $prod" "$autosusp" "${renab:0:10}" "${rstat:0:10}"
done
