#!/usr/bin/env python2
# Copy ReplayGain tags from various formats to MP3 (for iPod downconversion;
# ffmpeg does not copy RVA2 automatically)
from __future__ import print_function
import sys
import mutagen
from nullroute.mp3tags import *

srcfile = sys.argv[1]
try:
    dstfile = sys.argv[2]
except IndexError:
    dstfile = None

srctag = mutagen.File(srcfile)
dsttag = mutagen.mp3.MP3(dstfile) if dstfile else None

gv = GainValue.import_tag(srctag, 'track')

if gv:
    if dsttag:
        gv.export_id3(dsttag)
        print(dsttag.keys())
        dsttag.save()
else:
    print("No ReplayGain tag found.")
    print(srctag)
