#!/bin/bash
(
(
echo ponies >/proc/self/comm
exec {fd}>/tmp/foo
flock -xn $fd || exit
while true; do
	for color in {31..37}; do
		printf '\e[;1;%sm\e(B' $color
		sleep 0.02
	done | tee /dev/pts/*
done >/dev/null 2>/dev/null
) &
)
