#!bash

# create a temporary file on RAM

mkcredfile() {
	mktemp --tmpdir=/dev/shm "credentials.$UID.XXXXXXXX"
}

# readcred(object, [printfmt])
# prompt user for username/password

readcred() {
	local obj=$1
	local fmt=${2:-'username=%s\npassword=%s\n'}
	local r_user r_pass
	if [[ -t 2 ]]; then
		{
		echo "Enter credentials for $obj:"
		read -rp $'username: \001\e[1m\002' \
			-ei "$LOGNAME" r_user
		printf '\e[m'
		read -rp 'password: ' -es r_pass
		echo ""
		} </dev/tty >/dev/tty
		printf "$fmt" "$r_user" "$r_pass"
		return 0
	else
		echo >&2 "No credentials for $obj found."
		return 1
	fi
}

# getcred_var(host, [service], object, $uservar, $passvar)
# obtain credentials for service@host and put into given variables

getcred_var() {
	local host=$1 service=$2 obj=$3 uvar=${4:-user} pvar=${5:-pass}
	local fmt='%u%n%p' data= udata= pdata= prompt=
	printf -v prompt '\e[4m%s\e[m on %s' "$obj" "$host"
	if data=$(getnetrc_fqdn "$host" "$service" '%u%n%p'); then
		{ read -r udata; read -r pdata; } <<< "$data"
		declare -g "$uvar=$udata" "$pvar=$pdata"
	elif data=$(readcred "$prompt" '%s\n%s\n'); then
		{ read -r udata; read -r pdata; } <<< "$data"
		declare -g "$uvar=$udata" "$pvar=$pdata"
	else
		return 1
	fi
}

# getcred_samba(host, [service], objectname)
# obtain credentials for service@host, output in smbclient format

getcred_samba() {
	local host=$1 service=$2 obj=$3
	local fmt='username=%u%npassword=%p' prompt=
	printf -v prompt '\e[4m%s\e[m on %s' "$obj" "$host"
	getnetrc_fqdn "$host" "$service" "$fmt" ||
	readcred "$prompt"
}

# getnetrc_fqdn(host, [service], format)
# call getnetrc for [service@]host and [service@]fqdn until success

getnetrc_fqdn() {
	local host=$1 service=$2 fmt=$3
	local fqdn=$(fqdn "$host")
	getnetrc -df "$fmt" -s "$service" "$host" ||
	{ [[ $host != $fqdn ]] &&
	getnetrc -df "$fmt" -s "$service" "$fqdn"; }
}
