#!/usr/bin/env perl
# Debogosify messages send out by some my teachers using IceWarp Webmail.

while (<STDIN>) {
	if (/^Content-Type:/i) {
		if (/charset=/) {
			s/charset="us-ascii"/charset="Windows-1257"/ig;
		} elsif (m!\btext/\w+\b!) {
			s/$/; charset="Windows-1257"/;
		}
	}
	if (/^(Content-Type|From|Subject):/i) {
		s/=\?US-ASCII\?/=?Windows-1257?/ig;
	}
	print;
}
