#!/bin/sh
# Wrapper for `doveadm exec imap` that takes care of SSH and the weird exit
# status that mutt chokes on.

cmd='doveadm exec imap || [ $? -eq 81 ]'

case $1 in
*@*)
	ssh ${1#@} "$cmd";;
"")
	eval "$cmd";;
esac
