#!/usr/bin/env python3
import email
import email.policy
import os
import sys
import subprocess
import mimetypes

files = sys.argv[1:]

msg = email.message_from_file(sys.stdin,
                              policy=email.policy.default)

for arg in files:
    name = os.path.basename(arg)
    mime = mimetypes.guess_type(arg)[0] or "text/plain"
    buf = open(arg, "rb").read()
    msg.add_attachment(buf, *mime.split("/"), filename=name)

had_from = msg.get_unixfrom()
print(msg.as_string(unixfrom=had_from))
