#!/bin/bash
# Wrapper around GPG pinentry to be used as a simple 'askpass' tool.

usage() {
	echo "Usage: ${0##*/} [OPTION]... [description]"
	echo ""
	echo "    -C canceltext  set Cancel button label"
	echo "    -g             (pinentry) append --no-global-grab"
	echo "    -I windowid    (pinentry) append --parent-wid \$windowid"
	echo "    -O oktext      set OK button label"
	echo "    -o option      (pinentry) append given option"
	echo "    -P path        use a different pinentry executable"
	echo "    -p text        set entry prompt (default is 'PIN:')"
	echo "    -t title       set entry window title"
	exit 2
}

# You can set a default pinentry program and its options here.
# Examples:
#   pinentry=(pinentry-gtk-2 --no-global-grab)
pinentry=(pinentry)

i=0
debug=false
config=("SETPROMPT")

while getopts ':C:Dd:ghI:O:o:P:p:t:x' OPT "$@"; do
	$debug && echo "[$OPTIND] -$OPT '$OPTARG'" >&2
	case "$OPT" in
	C)	config+=("SETCANCEL $OPTARG") ;;
	D)	debug=true ;;
	d)	config+=("SETDESC $OPTARG") ;;
	g)	pinentry+=(--no-global-grab) ;;
	h)	usage ;;
	I)	pinentry+=(--parent-wid "$OPTARG") ;;
	O)	config+=("SETOK $OPTARG") ;;
	o)	pinentry+=("$OPTARG") ;;
	P)	pinentry[0]="$OPTARG" ;;
	p)	config+=("SETPROMPT $OPTARG") ;;
	t)	config+=("SETTITLE $OPTARG") ;;
	\?)	echo "${0##*/}: unknown option '$OPTARG'" >&2; usage >&2 ;;
	*)	echo "${0##*/}: option -$OPT not implemented" >&2; exit 2 ;;
	esac
done

if [[ "${!OPTIND}" ]]; then
	config+=("SETDESC ${!OPTIND}")
fi

configure() {
	if (( $i == ${#config[@]} )); then
		return 1
	else
		echo "${config[$i]}"
		(( ++i ))
	fi
}

trap "trap - SIGTERM; kill \$pinentry_pid" EXIT SIGINT SIGHUP SIGTERM SIGQUIT

# spawn the pinentry program
$debug && echo "pinentry =" "${pinentry[@]}"
coproc "${pinentry[@]}"; pinentry_pid=$!
in=${COPROC[0]}
out=${COPROC[1]}

nextstate=configure
while read status rest <&$in; do
	$debug && echo "[$nextstate] $status {$rest}" >&2
	case "$nextstate" in
	configure)
		case "$status" in
		OK)
			configure >&$out || {
				echo 'getpin' >&$out
				nextstate=waitinput
			} ;;
		ERR)
			echo "$rest" >&2
			exit 2 ;;
		esac ;;
	waitinput)
		# sent GETPIN, waiting for user action
		case "$status" in
		OK)
			# null input
			exit 0 ;;
		D)
			# data
			echo "$rest"
			exit 0 ;;
		ERR)
			# user cancelled
			exit 1 ;;
		esac ;;
	esac
done
