#!/usr/bin/env bash
set -e
pullkey_host=equal.cluenet.org
forward_mail=grawity@gmail.com

if have getent; then
	read _ FQDN _ <<< "$(getent hosts "$HOSTNAME")"
else
	FQDN=$(hostname)
fi

have() { command -v "$1" >&/dev/null; }

log() { printf "\e[1;34m==>\e[;1m %s\e[m\n" "$*"; }

confirm() {
	local msg=$1 ans=
	read -ep "$msg " -t 10 ans && [[ $ans == y ]]
}

check-gpg-version() {
	local version major minor patch rest
	version=$(gpg --version | sed 's/gpg (GnuPG) //; q')
	IFS="." read -r major minor rest <<< "$version"
	(( major >= 2 )) || (( major == 1 && minor >= 4 ))
}

if [[ ! -d ~/lib/dotfiles ]]; then
	log "Cloning dotfiles.git"
	mkdir -p ~/lib
	git clone "https://github.com/grawity/dotfiles.git" \
		~/lib/dotfiles
	~/lib/dotfiles/install
fi

if [[ ! -f ~/.ssh/authorized_keys ]]; then
	if have gpg && check-gpg-version; then
		log "Setting up sshupdate-gpg"
		~/code/sshupdate-gpg -rv
	elif have ssh-keygen && [[ ! -f ~/.ssh/id_sshupdate ]]; then
		log "Setting up sshupdate-ssh"
		opts=(-q -f ~/.ssh/id_sshupdate -N ""
			-C "$USER/sshupdate@$FQDN")
		ssh-keygen "${opts[@]}" -t ecdsa ||
		ssh-keygen "${opts[@]}" -t rsa -b 768
		cat ~/.ssh/id_sshupdate | ssh $pullkey_host "~/bin/pullkey --install"
	fi
fi

if ! crontab -l | grep -qs "code/tools/pull"; then
	log "Adding tools/pull to crontab"
	(crontab -l; echo -e '@daily\t~/code/tools/pull') | crontab -
fi

if [[ ! -f ~/.forward ]]; then
	log "Forwarding mail to $forward_mail"
	echo "$forward_mail" > ~/.forward

	log "Sending a test email"
	(echo "Test";
		hostname -f;
		uname -a;
		id;
		have getent && getent passwd "$USER"
	) | mail -s "Test from $HOSTNAME" "$forward_mail"
fi
