#!/usr/bin/env bash
# Dotfile updater.
. ~/lib/include/util.sh 2> /dev/null

CACERT=~/lib/ssl/ca/nullroute.pem
BASE="https://wind.nullroute.eu.org/~grawity/"

update() {
	cd || die "could not chdir into $HOME"
	rm -vf .bash_login
	rm -vf .bash_profile
	get "${BASE}dot/bashrc" .bashrc
	get "${BASE}dot/profile" .profile
	get "${BASE}dot/vimrc" .vimrc
}

## Other functions

have() { command -v "$@" >& /dev/null; }

log() { [ -t 0 ] && printf "%s\n" "$*"; }

die() { echo "dotrc: fatal: ${1:-previous command failed}" >&2; exit 1; }

get() {
	local url=$1 file=$2 mode=$3 temp=''
	log "fetching $file from $url"

	mkdir -p "$(dirname "$file")"
	temp=$(mktemp "dotrc-$USER.XXXXXX") || die "mktemp failed"
	if fetch "$url" "$temp" && [ -s "$temp" ]; then
		# easiest way to preserve modes
		cat "$temp" > "$file"

		if [ "$mode" ]; then
			log "changing modes for $file to $mode"
			chmod "$mode" "$file"
		fi
	else
		echo "dotrc: fetch failed: $url" >&2
	fi
	rm -f "$temp"
}

if have curl; then
	fetch() { curl -sLSf --cacert "$CACERT" "$1" -o "$2"; }
elif have wget; then
	fetch() { wget -q --ca-certificate "$CACERT" "$1" -O "$2"; }
else
	die "no HTTP client"
fi

## Do stuff.

if ! [ -e "$CACERT" ]; then
	die "CA certificate not found: $CACERT"
fi
mkdir -pm 0700 ~/tmp || die "unable to create temporary directory"
update
