#!/usr/bin/env perl
use warnings;
use strict;
use feature "say";
use Sys::Hostname;
use Net::hostent;
use Data::Dumper;

sub getfqdn {
	my $host = shift;
	my $addr = gethostbyname($host);
	defined $addr ? $addr->name : $host;
}

if (@ARGV) {
	say getfqdn($_) for @ARGV;
} else {
	say getfqdn(hostname);
}
