#!/usr/bin/env bash
set -e

dir=~/code
all=false
force=false

while getopts ad:f OPT; do
	case $OPT in
	a)	all=true;;
	d)	dir=$OPTARG;;
	f)	force=true;;
	esac
done

link() {
	local target="$dir/${1%/}" link=$2
	if [ -e "$link" ] && [ ! -h "$link" ] && ! $force; then
		echo "Not overwriting $link" >&2
	else
		rm -f "$link"
		sym -vf "$target" "$link"
	fi
}
sym() { "$dir/sym.pl" "$@"; }

mkdir -p ~/bin ~/lib
mkdir -pm 0700 ~/tmp

link	bin/args		~/bin/args
link	bin/bgrep		~/bin/bgrep
link	tools/getnetrc.pl	~/bin/getnetrc
link	getpaste.pl		~/bin/getpaste
link	tools/getsession.sh	~/bin/getsession
link	gist.pl			~/bin/gist
link	rdt.php			~/bin/rdt
link	sym.pl			~/bin/sym
link	tools/urlencode.pl	~/bin/urlencode

if { which python2 && ! which python; } >& /dev/null; then
	ln -vsf "$(which python)" ~/bin/python2
fi
