#!/bin/bash
# Command-line interface to Mark Sparks' socket-interface.pl Irssi script.

send() { socat stdio unix:"$IRSSI_SOCKET" <<< "$*"; }

: ${IRSSI_SOCKET:=$HOME/.irssi/socket}

case $1 in
	activelog|windowlist|get_lines)
		# outputs text
		send "$*" || exit 2
		;;
	*)
		# outputs bool 0/1
		if ret=$(send "$*"); then
			[[ $ret ]] && (( ret > 0 ))
		else
			exit 2
		fi
		;;
esac
