#!/usr/bin/env bash
rread() {
	IFS=$'\t' read -r "$@"
}

now=$(date +%s)

# Read ccache contents

tgtickets=()
svtickets=()
ccdata=$(pklist)
while rread key rest; do
	case $key in
		cache)
			rread ccname _ <<< "$rest"
			;;
		principal)
			rread defprinc _ <<< "$rest"
			defrealm=${defprinc##*@}
			;;
		ticket)
			rread _ cserver _ cexpiry _ cflags _ <<< "$rest"
			if [[ $cserver == krbtgt/* ]]; then
				tgtickets+=("$rest")
			else
				svtickets+=("$rest")
			fi
			if [[ $cserver == "krbtgt/$defrealm@$defrealm" ]]; then
				tgt=$cserver
				tgtexpiry=$cexpiry
			fi
			if [[ $cflags == *I* ]]; then
				init=$cserver
				initexpiry=$cexpiry
				initflags=$cflags
			fi
			;;
	esac
done <<< "$ccdata"

# Determine which ticket's expiry to show

if [[ $init ]]; then
	texpiry=$initexpiry
elif [[ $tgt ]]; then
	texpiry=$tgtexpiry
fi

if (( texpiry <= now )); then
	expiry=$'\e[31mexpired\e[m'
else
	expiry="expires $(date -d "@$texpiry" "+%b %d %H:%M")"
fi

# Pretty-print data

printf 'Credentials for \e[1m%s\e[m (%s):\n\n' "$defprinc" "$expiry"
for rest in "${tgtickets[@]}" "${svtickets[@]}"; do
	rread cclient cserver cstart cexpiry crenew cflags <<< "$rest"

	if [[ $cflags == *I* ]]; then
		if (( initexpiry <= now )); then
			color='1;31'
		elif (( initexpiry <= now+600 )); then
			color='1;33'
		else
			color='1;32'
		fi
	elif [[ $cserver == krbtgt/* ]]; then
		color='1;35'
	else
		color=''
	fi

	cserver=${cserver%"@$defrealm"}

	cflags=${cflags//[AT]/}
	[[ $cflags == *I* ]] || cflags=${cflags//[FR]/}

	printf '    \e[%sm%-50s\e[m %-8s\n' "$color" "$cserver" "$cflags"
done
