#!/usr/bin/env bash
rread() {
	IFS=$'\t' read -r "$@"
}

now=$(date +%s)

# Read ccache contents

tgtickets=()
svtickets=()
ccdata=$(pklist) || exit $?
while rread key rest; do
	case $key in
		cache)
			rread ccname _ <<< "$rest"
			;;
		principal)
			rread defprinc _ <<< "$rest"
			defrealm=${defprinc##*@}
			;;
		ticket)
			rread _ server _ expiry _ flags _ <<< "$rest"
			if [[ $server == krbtgt/* ]]; then
				tgtickets+=("$rest")
			else
				svtickets+=("$rest")
			fi
			if [[ $server == "krbtgt/$defrealm@$defrealm" ]]; then
				tgt=$server
				tgtexpiry=$expiry
			fi
			if [[ $flags == *I* ]]; then
				init=$server
				initexpiry=$expiry
				initflags=$flags
			fi
			;;
	esac
done <<< "$ccdata"

# Determine which ticket's expiry to show

if [[ $init ]]; then
	expiry=$initexpiry
elif [[ $tgt ]]; then
	expiry=$tgtexpiry
fi

if (( expiry <= now )); then
	dexpiry=$'\e[31mexpired\e[m'
else
	dexpiry="expires $(date -d "@$expiry" "+%b %d %H:%M")"
fi

# Pretty-print data

printf 'Credentials for \e[1m%s\e[m (%s):\n\n' "$defprinc" "$dexpiry"
for rest in "${tgtickets[@]}" "${svtickets[@]}"; do
	rread client server validity expiry renew flags <<< "$rest"

	if [[ $flags == *I* || $server == $tgt ]]; then
		if (( expiry <= now )); then
			color='1;31'
		elif (( expiry <= now+600 )); then
			color='1;33'
		else
			color='1;32'
		fi
	elif [[ $server == krbtgt/* ]]; then
		color='1;35'
	else
		color=''
	fi

	dserver=${server%"@$defrealm"}
	
	dflags=${flags//[AT]/}
	[[ $server == $tgt ]] ||
		dflags=${dflags//[FR]/}

	printf '    \e[%sm%-50s\e[m %s\n' "$color" "$dserver" "$dflags"
done
