#!/usr/bin/env bash
if [ ! -f ~/.mailrc ]; then
	export NAILRC=~/lib/dotfiles/mailrc
fi

if [[ -z $MAIL || ! -e $MAIL || ( -f $MAIL && ! -s $MAIL ) ]]; then
	MAILOPT="-Anullroute"
fi

exec mailx $MAILOPT "$@"
