#!/bin/bash
# Playlist search tool for `mpd`

printf -v fmt_normal "$(tput setaf 40)%%4d  $(tput sgr0)%%s\n"
printf -v fmt_current "$(tput bold; tput setaf 82)%%4d  $(tput setaf 7)%%s$(tput sgr0)\n"
display_tty_current() {
	printf "$fmt_current" "$cur_pos" "$cur_artist - $cur_title"
}
display_tty_list() {
	local i
	for i in "${!songs[@]}"; do
		IFS=$'\t' read -r artist title <<< "${songs[i]}"
		if [[ $artist == $cur_artist && $title == $cur_title ]]; then
			printf "$fmt_current" "$i" "$artist - $title"
		else
			printf "$fmt_normal" "$i" "$artist - $title"
		fi
	done
}

display_x11_current() {
	return

	local icon
	icon="media-playback-start"
	notify-send -i "$icon" \
		"$cur_title" \
		"by <i>$(xmlescape "$cur_artist")</i>"
}
display_x11_list() {
	local i new
	new=$(for i in "${!songs[@]}"; do
			IFS=$'\t' read -r artist title <<< "${songs[i]}"
			printf '%d\n%s - %s\n' "$i" "$artist" "$title"
		done | zenity --list \
			--width=500 --height=400 \
			--title="Search results for '$pattern'" \
			--text="${#songs[@]} entries. Double-click to play." \
			--hide-header \
			--column="" \
			--column="Title" \
			--hide-column=1)

	if [[ $new ]]; then
		mpc -q play "$new"
	fi
}

get_current() {
	IFS=$'\t' read -r cur_pos cur_artist cur_title <<< "$(mpc current -f "$fmt_input")"
}

xmlescape() {
	printf '%s\n' "$@" | sed 's/&/\&amp;/g; s/"/\&quot;/g; s/</\&lt;/g; s/>/\&gt;/g'
}

if [[ $DISPLAY && ! -t 1 ]]; then
	out=x11
else
	out=tty
fi

fmt_input='%position%\t%artist%\t%title%'

if [[ -z $1 ]]; then
	get_current
	display_${out}_current
else
	pattern=$1
	songs=()

	# parse argument
	if [[ $pattern =~ ^[[:digit:]]+$ ]]; then
		if (( $pattern == 0 )); then
			echo "error: song number must be larger than zero" >&2
			exit 2
		fi
		songs[$pattern]=$(mpc playlist -f "$fmt_input" | sed -n "${pattern}{p;q}")
	else
		while IFS=$'\t' read -r num song; do
			songs[$num]=$song
		done < <(mpc playlist -f "$fmt_input" | grep -Ei -- "$pattern")
	fi

	# if exactly one result, go to song
	if (( ${#songs[@]} == 1 )); then
		mpc -q play "${!songs[@]}"
		get_current
		display_${out}_current
	else
		display_${out}_list
	fi
fi
