#!/usr/bin/env bash
PATH="$HOME/bin:$HOME/usr/bin:$PATH"
set -e
exec 1>/dev/null

if [[ $(git --version | sed 's/^git version //') == 1.[1-5].* ]]; then
	oldgit=true
else
	oldgit=false
fi

git-pull() {
	cd "$1"
	if $oldgit; then
		git pull &>/dev/null
	else
		git pull -q
	fi
	cd -
}

git-pull ~/code

if [[ -d ~/lib/dotfiles ]]; then
	git-pull ~/lib/dotfiles
elif [[ -d ~/.dotfiles ]]; then
	echo "Moving dotfiles.git to ~/lib"
	mkdir -p ~/lib
	mv ~/.dotfiles ~/lib
	git-pull ~/lib/dotfiles
	~/lib/dotfiles/install
else
	echo "Upgrading dotrc to dotfiles.git"
	mkdir -p ~/lib
	git clone -q "https://github.com/grawity/dotfiles.git" ~/lib/dotfiles
	~/lib/dotfiles/install
fi

~/code/sshupdate || {
	echo >&2 "sshupdate failed [$?]"
	exit 1
}

if [[ -f ~/tmp/rwhod-${HOSTNAME}.pid ]]; then
	~/code/useless/rwho/rwhod.sh update
fi
