#!/usr/bin/env bash
PATH="$HOME/bin:$HOME/usr/bin:$PATH"
set -e
exec 1>/dev/null

git-pull() {
	cd "$1"
	if [[ $(git --version | sed 's/^git version //') == 1.5.* ]]; then
		git pull >& /dev/null
	else
		git pull -q
	fi
	cd -
}

git-pull ~/code

if [[ -d ~/.dotfiles ]]; then
	git-pull ~/.dotfiles
else
	~/code/tools/dotrc || {
		echo >&2 "dotrc failed [$?]"
		exit 1
	}
fi

~/code/sshupdate || {
	echo >&2 "sshupdate failed [$?]"
	exit 1
}

if [[ -f ~/tmp/rwhod-${HOSTNAME}.pid ]]; then
	~/code/useless/rwho/rwhod.sh update
fi
