#!/usr/bin/env bash
set -e
[[ -t 0 ]] && set -x
if [[ -z $xyzzy ]]; then
	# Update ~/code and run the new script
	export PATH="$HOME/bin:$HOME/usr/bin:$PATH"
	export xyzzy=42

	cd ~/code
	git pull >& /dev/null
	exec tools/pull
else
	# Update dotfiles
	if [[ -d ~/lib/dotfiles ]]; then
		cd ~/lib/dotfiles
		git pull origin master >& /dev/null
	else
		echo "Migrating to dotfiles.git"
		mkdir -p ~/lib
		git clone "https://github.com/grawity/dotfiles.git" \
			~/lib/dotfiles
	fi
	~/lib/dotfiles/install

	# Update authorized SSH keys
	if [[ -f ~/.ssh/id_sshupdate ]]; then
		~/code/sshupdate-ssh
	elif [[ -f ~/code/sshupdate ]]; then
		# TODO: remove this on Feb 6
		~/code/sshupdate
	else
		~/code/sshupdate-gpg
	fi

	# Restart rwhod if necessary

	if [[ -f ~/tmp/rwhod-${HOSTNAME}.pid ]]; then
		~/code/useless/rwho/rwhod.sh update
	fi
fi
true
