#!/usr/bin/env bash
# quick way to access CIFS/SMB shares
# mount.cifs must be installed setuid-root

if ! [[ $1 ]]; then
	echo "Usage: $0 share mountpoint" >&2
	exit 2
fi

remote=$1
o_remote=$remote
mountpoint=$2
proto=
host=
path=
authhost=

while getopts 'a:' OPT; do
	case $OPT in
		a)	authhost=$OPTARG;;
	esac
done; shift $((--OPTIND))

# Parse remote URL into proto,host,path
if [[ $remote =~ ^(([[:alnum:]]+):)?//(\[.+\]|[[:alnum:]._-]+)(/(.*))?$ ]]; then
	proto=${BASH_REMATCH[2]:-cifs}
	host=${BASH_REMATCH[3]}
	path=${BASH_REMATCH[5]:-$LOGNAME}
elif [[ $remote =~ ^(\[.+\]|[[:alnum:]._-]+)(:(.*))?$ ]]; then
	proto=sftp
	host=${BASH_REMATCH[1]}
	path=${BASH_REMATCH[3]}
fi
remote=$proto://$host/$path

[[ $authhost ]] || authhost=$host

if [[ -z $mountpoint ]]; then
	if [[ $path == $LOGNAME ]]; then
		mountpoint=$host
	else
		mountpoint=${path##/*}
	fi
	mountpoint=$HOME/fs/$mountpoint
	mkdir -pm 0700 "$mountpoint"
fi

readcred() {
	local obj=$1 r_user r_pass
	if [[ -t 0 ]]; then
		echo >/dev/tty "Enter credentials for $obj"
		read </dev/tty -rp 'username: ' -ei "$LOGNAME" r_user
		read </dev/tty -rp 'password: ' -es r_pass
		echo >/dev/tty ""
		printf 'username=%s\npassword=%s\n' "$r_user" "$r_pass"
		return 0
	else
		echo >&2 "No credentials for $obj found."
		return 1
	fi
}

getcred() {
	local fmt='username=%u%npassword=%p'
	getnetrc -df "$fmt" "$authhost" ||
	getnetrc -df "$fmt" "$host" ||
	readcred "$remote"
}

mktemps() {
	mktemp --tmpdir=/dev/shm "$@"
}

connect() {
	case $proto in
	9p)
		9mount -iu "tcp!$host" "$mountpoint"
		;;
	sftp)
		sshfs "$host:$path" "$mountpoint" -o "allow_root"
		;;
	cifs|smb)
		local creds=$(mktemps)
		getcred >$creds

		local secmode="ntlmv2,credentials=$creds"
		if grep -Fxqs "password=*" "$creds"; then
			secmode="krb5,credentials=${KRB5CCNAME#FILE:}"
		fi

		sudo mount -t cifs "//$host/$path" "$mountpoint" \
			-o "sec=$secmode,uid=$(id -u),gid=$(id -g),file_mode=0600,dir_mode=0700,iocharset=utf8,nosuid,noperm"
		rm -f "$creds"
		;;
	esac
}

if [[ $DEBUG ]]; then
	"$@"
else
	connect
fi
