#!/usr/bin/env bash
# quick way to access CIFS/SMB shares
# mount.cifs must be installed setuid-root

if [ -z "$1" ] || [ -z "$2" ]; then
	echo "Usage: $0 share mountpoint" >&2
	exit 2
fi

remote="$1"
mountpoint="$2"

if [[ "$remote" = *:* ]]; then
	# host:share
	host="${remote%%:*}"
	share="${remote#*:}"
	remote="//${host}/${share}"
elif [[ "$remote" = //*/* ]]; then
	host="${remote#//}"
	host="${host%%/*}"
else
	echo "Invalid remote path"
	exit 1
fi

[[ $authhost ]] || authhost=$host

creds="$(mktemp)"
getnetrc -df "username=%u%npassword=%p" "$authhost" > "$creds" || {
	echo "No credentials for $host found" >&2
	exit 1
}
sudo mount.cifs "$remote" "$mountpoint" -o "credentials=$creds,uid=$(id -u),gid=$(id -g),file_mode=0600,dir_mode=0700,iocharset=utf8"
rm -f "$creds"
