#!/usr/bin/env perl
use warnings;
use strict;
use feature "say";

my ($res, $pkg, $file, $inc);
for $pkg (@ARGV) {
	($file = $pkg) =~ s|::|/|g;
	do {
		say;
		++$res;
	} for grep {-f} map {"$_/$file.pm"} @INC;
}
exit(($res // 1) ? 0 : 1);
