#!/usr/bin/env bash
# git-up - fast-forward the latest changes from upstream

set -e

opts=$(git config nullroute.git.up || true)
if [ "$opts" ]; then
	git config nullroute.git-new.options "$opts" &&
	git config --unset nullroute.git.up
fi

opts=$(git config nullroute.git-new.options || true)
paths=$(git config nullroute.git-new.paths || true)
mark=$(git config --bool nullroute.git-new.last-read || true)

old=$(git rev-parse "HEAD")

if [[ $mark == true ]]; then
	git-update-last-read -i .
fi

if [ "$(git rev-parse --is-bare-repository)" = "true" ]; then
	git fetch
else
	git pull --ff-only --no-stat "$@"
fi

new=$(git rev-parse "HEAD")

if [ "$new" != "$old" ]; then
	# Reflogs are't always available in bare repositories; I'd be
	# using "@{1}.." otherwise. Although maybe this is more readable.
	tig $opts "$old..$new" -- $paths
fi

if [[ $mark == true ]]; then
	git-update-last-read -e .
fi
