#!/usr/bin/env bash

set -e

USAGE='<commit> <path-prefix>'

. "$(git --exec-path)/git-sh-setup"

ref=$1 prefix=$2

[[ $ref && $prefix ]] || usage

require_work_tree

git merge -s ours --no-commit "$ref"

git read-tree --prefix="${prefix%/}/" -u "$ref"
