#!/bin/sh
# git-branch-info - verbose branch list
git branch --list --no-color |
sed -e 's/*/ /' |
while read branch; do
	printf -v wbranch "%-12s" "$branch"
	printf -v windent "%-*s" "${#wbranch}" ""
	git log -1 --format=format:"%C(yellow)${wbranch}%C(reset) %s %C(blue)(%cr)%C(reset)" "$branch"
done
