#!/bin/sh
# Usage: git-up
#        git-reup
#
# Like git-pull but show a short and sexy log of changes
# immediately after merging (git-up) or rebasing (git-reup).
#
# Inspired by Kyle Neath's `git up' alias:
# http://gist.github.com/249223
#
# Stolen from Ryan Tomayko
# http://github.com/rtomayko/dotfiles/blob/rtomayko/bin/git-up
#
# Stolen from Zach Holman
# https://github.com/holman/dotfiles/blob/master/bin/git-up

set -e

PULL_ARGS="--no-stat $@"

# when invoked as git-reup, run as `git pull --rebase'
test "$(basename $0)" = "git-reup" &&
PULL_ARGS="--rebase $PULL_ARGS"

old=$(git rev-parse 'HEAD')

if [ "$(git rev-parse --is-bare-repository)" = "true" ]; then
	git fetch
else
	git pull $PULL_ARGS
fi

# show diffstat of all changes if we're pulling with --rebase. not
# sure why git-pull only does this when merging.
test "$(basename $0)" = "git-reup" && {
    echo "Diff:"
    git --no-pager diff --color --stat HEAD@{1}.. |
    sed 's/^/ /'
}

# show an abbreviated commit log of stuff that was just merged.
new=$(git rev-parse 'HEAD')
test "$new" = "$old" ||
tig 'HEAD@{1}..'
