#!/usr/bin/env bash

set -e

if (( $# != 1 )); then
	echo "Usage: git revert-to <commit>"
	exit 2
fi

oldsha=$(git rev-parse --verify "$1")

git read-tree --empty
git read-tree "$oldsha"
git checkout-index --all --force

git commit -t <(echo "Revert to an earlier commit $oldsha")
