#!/usr/bin/env bash

set -e

if [ $# -ne 2 ]; then
	echo "Usage: git link-history <current-branch> <history-branch>"
	echo ""
	echo "Prepend <history> as a parent of the initial commit of <current>."
	exit 2
fi

newtail=$(git --no-replace-objects rev-list "$1" | tail -1)
oldhead=$(git --no-replace-objects rev-parse --verify "$2")

parent=$(git rev-parse --verify "$newtail^")

if [ -n "$parent" ]; then
	echo "error: initial commit of $1 already has a fake parent"
	exit 1
else
	git fake-parent "$newtail" "$oldhead"
	git log -n 2 --decorate "$newtail"
fi
