#!/usr/bin/env bash
# pull - update version control repositories to latest upstream versions

. lib.bash || exit

is() {
	if [[ $1 == none ]]; then
		log2 $'\e[m'"Skipping \"$(basename "$PWD")\" (unknown)"
	else
		log2 $'\e[1m'"Updating \"$(basename "$PWD")\" ($1)"$'\e[m'
	fi
}

log:() {
	lib::msg "$*" 'log' '\e[32m' ' >' '\e[35m'
	"$@"
}

upd:() {
	local old=$1 new=$2 cmd=("${@:3}")
	local bold= reset=
	if [[ -t 1 ]]; then
		bold=$'\e[1m' reset=$'\e[m'
	fi
	if [[ "$old" != "$new" ]]; then
		log "Updated from ${bold}${old}${reset} to ${bold}${new}${reset}"
		echo " # ${cmd[*]}"
	fi
}

svnsync() {
	local lib=$(which libfunsync.so 2>/dev/null)
	if [[ -f $lib ]]; then
		env LD_PRELOAD="$lib" svnsync "$@"
	else
		env svnsync "$@"
	fi
}

is_ignored() {
	[[ -u . ]]
}

do_pull() {
	if [[ -f Pullfile ]]; then
		do_main
	elif [[ -d .git/svn ]]; then
		is "Git – SVN clone"
		if remote=$(git config --get svn-remote.svn.url); then
			rroot=$(svn info "$remote" | sed -n 's/^Repository Root: //p')
			log: svnsync sync "$rroot"
		fi
		log: git svn fetch
		d=$(git rev-parse --git-dir)
		h=$(< "$d/HEAD")
		if [[ $h == 'ref: '* ]]; then
			h=${h#'ref: '}
			if [[ $h == 'refs/heads/'* ]]; then
				br=${h#'refs/heads/'}
				if [[ $(git config branch.$br.remote) == . ]] &&
				   [[ $(git config branch.$br.merge) == refs/remotes/* ]]
				then
					log: git merge --ff-only
				fi
			fi
		fi
	elif [[ -d .git ]]; then
		is "Git"
		rev() { git rev-parse --verify HEAD; }
		old=$(rev)
		log: git pull --ff-only
		new=$(rev)
		if [[ -e .gitmodules ]]; then
			log: git submodule update
		fi
		if [[ "$old" != "$new" ]]; then
			old=${old:0:12}
			new=${new:0:12}
			upd: "$old" "$new" tig $old..$new
		fi
	elif [[ -d .hg ]]; then
		is "Mercurial"
		rev() { hg tip -q; }
		old=$(rev)
		log: hg pull --update
		new=$(rev)
		upd: "$old" "$new" hg log -r ${old#*:}:${new#*:} --pager always
	elif [[ -d .svn ]]; then
		is "SVN"
		rev() { svnversion; }
		old=$(rev)
		rroot=$(svn info "$remote" | sed -n 's/^Repository Root: //p')
		if [[ $rroot == file://* ]]; then
			log: svnsync sync "$rroot"
		fi
		log: svn update
		new=$(rev)
		upd: "$old" "$new" svn log -r "$old:$new"
	elif [[ -d .bzr ]]; then
		is "Bazaar"
		log: bzr pull
	elif [[ -f .fslckout ]]; then
		is "Fossil"
		rev() { fossil info | awk '$1 == "checkout:" {print $2}'; }
		old=$(rev)
		log: fossil update
		new=$(rev)
		upd: "$old" "$new" fossil timeline after "$old"
	elif [[ -d CVS ]]; then
		is "CVS"
		log: cvs -q up -d -P -A
	elif [[ -f format && -f hooks/pre-revprop-change ]]; then
		is "SVN – svnsync mirror"
		log: svnsync sync "file://$PWD"
	elif [[ -f HEAD ]] && d=$(git rev-parse --git-dir 2>/dev/null); then
		is "Git – bare repository"
		rev() { git rev-parse --verify HEAD; }
		old=$(rev)
		log: git fetch
		new=$(rev)
		if [[ "$old" != "$new" ]]; then
			git --no-pager diff --stat "$new" "$new"
			old=${old:0:12}
			new=${new:0:12}
			upd: "$old" "$new" tig "$old..$new"
		fi
	else
		is none
	fi
}

do_main() {
	if (( ! $# )) && [[ -s Pullfile ]]; then
		set -- $(grep '^[^#]' Pullfile)
	fi

	if (( ! $# )); then
		set -- */
	fi

	if (( $# )); then
		declare -A did
		for dir; do
			dir=$(readlink -f "$dir")
			if [[ ! ${did[$dir]} ]]; then
				did[$dir]=y
				(cd "$dir" && ! is_ignored && do_pull)
			fi
		done
	else
		do_pull
	fi
}

do_main "$@"
