#!/usr/bin/env bash
# pull - update version control repositories to latest upstream versions

. lib.bash || exit

_log_color[logcmd]='\e[32m'
_log_fprefix[logcmd]=' >'
_log_fcolor[logcmd]='\e[35m'

is() {
	local dir=$(realpath --relative-to="$_PULL_STARTDIR" "$PWD")
	if [[ $1 == none ]]; then
		log2 "skipping '$dir' (unknown)"
	else
		log2 "updating '$dir' ($1)"
	fi
}

log:() {
	lib::msg "$*" 'logcmd'
	"$@" || err "command '$1' failed (status $?)"
}

upd:() {
	local old=$1 new=$2 cmd=("${@:3}")
	local bold= reset=
	if [[ -t 1 ]]; then
		bold=$'\e[1m' reset=$'\e[m'
	fi
	if [[ "$old" != "$new" ]]; then
		log "Updated from ${bold}${old}${reset} to ${bold}${new}${reset}"
		echo " # ${cmd[*]}"
	fi
}

svnsync() {
	local lib=$(which libfunsync.so 2>/dev/null)
	if [[ -f $lib ]]; then
		env LD_PRELOAD="$lib" svnsync "$@"
	else
		env svnsync "$@"
	fi
}

is_ignored() {
	local dir=$1
	# ignore setuid directories
	[[ -u $dir ]]
}

do_pull() {
	debug "pull[$[++depth],$BASHPID] called, checking '$PWD' for repo"
	local errors=0

	if (( opt_dryrun > 1 )); then
		is "noop"
		return
	elif [[ -f Pullfile ]]; then
		do_main
	elif (( opt_dryrun > 0 )); then
		is "noop"
		return
	elif [[ -d .git/svn ]]; then
		is "Git – SVN clone"
		if remote=$(git config --get svn-remote.svn.url); then
			rroot=$(svn info "$remote" | sed -n 's/^Repository Root: //p')
			if [[ $rroot == file://* ]]; then
				log: svnsync sync "$rroot"
			fi
		fi
		log: git svn fetch
		d=$(git rev-parse --git-dir)
		h=$(< "$d/HEAD")
		if [[ $h == 'ref: refs/heads/'* ]]; then
			br=${h#'ref: refs/heads/'}
			if [[ $(git config branch.$br.remote) == . ]] &&
			   [[ $(git config branch.$br.merge) == refs/remotes/* ]]
			then
				rev() { git rev-parse --verify HEAD; }
				old=$(rev)
				log: git merge --ff-only
				new=$(rev)
				if [[ "$old" != "$new" ]]; then
					old=${old:0:12}
					new=${new:0:12}
					upd: "$old" "$new" tig $old..$new
				fi
			fi
		fi
	elif [[ -e .git ]]; then
		is "Git"
		rev() { git rev-parse --verify ${1:-HEAD}; }
		old=$(rev)
		if log: git pull --ff-only; then
			new=$(rev)
			if [[ -e .gitmodules ]]; then
				log: git submodule update
			fi
		else
			new=$(rev @{u})
			log: git --no-pager diff --stat "@{u}@{1}".."@{u}"
		fi
		if [[ "$old" != "$new" ]]; then
			old=${old:0:12}
			new=${new:0:12}
			upd: "$old" "$new" tig $old..$new
		fi
	elif [[ -d .hg ]]; then
		is "Mercurial"
		rev() { hg tip -q; }
		old=$(rev)
		log: hg pull --update
		new=$(rev)
		upd: "$old" "$new" hg log -r ${old#*:}:${new#*:} --pager always
	elif [[ -d _darcs ]]; then
		is darcs
		rev() { darcs changes --count; }
		old=$(rev)
		log: darcs pull
		new=$(rev)
		upd: "$old" "$new" darcs changes -n "$old-$new"
	elif [[ -d .svn ]]; then
		is "SVN"
		rev() { svnversion; }
		old=$(rev)
		rroot=$(svn info "$remote" | sed -n 's/^Repository Root: //p')
		if [[ $rroot == file://* ]]; then
			log: svnsync sync "$rroot"
		fi
		log: svn update
		new=$(rev)
		upd: "$old" "$new" svn log -v -r "$old:$new"
	elif [[ -d .bzr ]]; then
		is "Bazaar"
		rev() { bzr revno; }
		old=$(rev)
		log: bzr pull
		new=$(rev)
		upd: "$old" "$new" bzr log -r$((old+1))..$new
	elif [[ -f _MTN/format ]]; then
		is "Monotone"
		rev() { mtn automate get_base_revision_id; }
		old=$(rev)
		log: mtn pull
		new=$(rev)
		upd: "$old" "$new" mtn log --from "$old" --to "$new"
	elif [[ -f .fslckout ]]; then
		is "Fossil"
		rev() { fossil info | awk '$1 == "checkout:" {print $2}'; }
		old=$(rev)
		log: fossil update
		new=$(rev)
		upd: "$old" "$new" fossil timeline after "$old"
	elif [[ -d CVS ]]; then
		is "CVS"
		log: cvs -q up -d -P -A
	elif [[ -f format && -f hooks/pre-revprop-change ]]; then
		is "SVN – svnsync mirror"
		log: svnsync sync "file://$PWD"
	elif [[ "$(git config core.bare)" == "true" ]]; then
		is "Git – bare repository"
		rev() { git rev-parse --verify HEAD; }
		old=$(rev)
		log: git fetch
		new=$(rev)
		if [[ "$old" != "$new" ]]; then
			git --no-pager diff --stat "$old" "$new"
			old=${old:0:12}
			new=${new:0:12}
			upd: "$old" "$new" tig "$old..$new"
		fi
	else
		is none
	fi || (( ++errors ))

	debug "pull[$depth,$BASHPID] returning with ${errors:-0} errors"
	(( !errors ))
}

do_main() {
	debug "main[$[++depth],$BASHPID] called, checking for Pullfile"
	local errors=0
	local -A did

	if [[ ! $_PULL_STARTDIR ]]; then
		export _PULL_STARTDIR=$PWD
	fi

	if (( ! $# )) && [[ -s Pullfile ]]; then
		debug "reading args from Pullfile"
		set -- $(grep '^[^#]' Pullfile)
	fi

	if (( ! $# )) && [[ -f Pullfile ]] && [[ ! -s Pullfile ]]; then
		debug "empty Pullfile, assuming '*/'"
		set -- */
	fi

	if (( ! $# )); then
		debug "no args, assuming '.'"
		set -- .
	fi

	for arg; do
		debug "processing arg '$arg'"

		if [[ $arg == -* ]]; then
			arg=${arg#-}
			if [[ ! -d $arg ]]; then
				debug "- exclusion is not a directory, ignoring"
				continue
			fi
			dir=$(readlink -f "$arg")
			debug "- excluding dir '$dir'"
			did[$dir]=y
			continue
		fi

		if [[ $arg == !* ]]; then
			arg=${arg#!}
			debug "- excluding glob '$arg'"
			_skip_glob+="|$arg"
			skip_glob="@(${_skip_glob#|})"
			debug "- skip_glob is now '$skip_glob'"
			continue
		fi

		if [[ $skip_glob && $arg == $skip_glob ]]; then
			debug "- arg '$arg' is excluded, skipping"
			continue
		fi

		if [[ ! -d $arg && -d $arg.git ]]; then
			arg+=.git
		fi

		if [[ ! -d $arg ]]; then
			err "not a directory: '$arg'"
			continue
		fi

		dir=$(readlink -f "$arg")

		if [[ ${did[$dir]} ]]; then
			debug "- dir '$dir' already seen, skipping"
			continue
		fi
		did[$dir]=y

		if is_ignored "$dir"; then
			debug "- dir '$dir' is ignored (+u), skipping"
			continue
		fi

		debug "- updating '$dir'"
		(cd "$dir" && do_pull) || err "update of '$dir' failed"
	done

	debug "main[$depth,$BASHPID] returning with ${errors:-0} errors"
	(( !errors ))
}

depth=0
opt_dryrun=0

while getopts ":n" OPT; do
	case $OPT in
	n) (( ++opt_dryrun ));;
	*) lib::die_getopts;;
	esac
done; shift $((OPTIND-1))

do_main "$@" && (( !errors ))
