#!/usr/bin/env perl

sub trace {
	my %what = @_;
	for my $section (keys %what) {
		my $v = $what{$section};
		if (ref $v eq 'HASH') {
			@ENV{keys %$v} = values %$v;
		}
	}
}

trace _main_ => {DEBUG => 1};

trace adb => {ADB_TRACE => "all"};

trace curl => {GIT_CURL_VERBOSE => 1};

trace git => {GIT_TRACE => 1};

trace glib => {G_MESSAGES_DEBUG => "all"};

trace gnutls => {GNUTLS_DEBUG_LEVEL => 4};

trace gpgme => {GPGME_DEBUG => 9};

trace gsseap => {GSSEAP_TRACE => "/dev/stderr"};

trace kerberos => {KRB5_TRACE => "/dev/stderr"};

trace libgl => {LIBGL_DEBUG => "verbose"};

trace libutil_linux => {
	LIBBLKID_DEBUG => "all",
	LIBFDISK_DEBUG => "all",
	LIBMOUNT_DEBUG => "all",
	#LIBSMARTCOLS_DEBUG => "all",
	LOOPDEV_DEBUG => "all",
	TERMINAL_COLORS_DEBUG => "all",
};

trace libval => {VAL_LOG_TARGET => "5:stdout"};

trace mesa => {MESA_DEBUG => 1};

trace p11_kit => {P11_KIT_DEBUG => "all"};

trace systemd => {SYSTEMD_LOG_LEVEL => "debug"};

trace tracker => {TRACKER_VERBOSITY => 3};

trace util_linux => {
	CFDISK_DEBUG => "all",
	FDISK_DEBUG => "all",
	LSBLK_DEBUG => "all",
	SFDISK_DEBUG => "all",
	WHEREIS_DEBUG => "all",
};

exec {$ARGV[0]} @ARGV;

if ($!) { die "exec: $!\n"; }
