#!/usr/bin/env perl

sub trace {
	my %what = @_;
	for my $section (keys %what) {
		my $v = $what{$section};
		if (ref $v eq 'HASH') {
			@ENV{keys %$v} = values %$v;
		}
	}
}

trace _main_ => {DEBUG => 1};

trace curl => {GIT_CURL_VERBOSE => 1};

trace git => {GIT_TRACE => 1};

trace glib => {G_MESSAGES_DEBUG => "all"};

trace gsseap => {GSSEAP_TRACE => "/dev/stderr"};

trace kerberos => {KRB5_TRACE => "/dev/stderr"};

trace libutil_linux => {
	LIBBLKID_DEBUG => 255,
	LIBFDISK_DEBUG => 255,
	LIBMOUNT_DEBUG => 255,
	LIBSMARTCOLS_DEBUG => 255,
	LOOPDEV_DEBUG => 255,
	TERMINAL_COLORS_DEBUG => 255,
};

trace libval => {VAL_LOG_TARGET => "5:stdout"};

trace p11_kit => {P11_KIT_DEBUG => "all"};

trace systemd => {SYSTEMD_LOG_LEVEL => "debug"};

trace tracker => {TRACKER_VERBOSITY => 3};

trace util_linux => {
	CFDISK_DEBUG => 255,
	FDISK_DEBUG => 255,
	LSBLK_DEBUG => 255,
	SFDISK_DEBUG => 255,
	WHEREIS_DEBUG => 255,
};

exec {$ARGV[0]} @ARGV;

if ($!) { die "exec: $!\n"; }
