#!/usr/bin/env bash
# rejournal -- incrementally read new journal messages, e.g. from crontab

CURSOR_TAG="-- cursor: "

if (( UID )); then
	statedir=${XDG_CACHE_HOME:-$HOME/.cache}/rejournal
else
	statedir=/var/lib/rejournal
fi

statefile=$statedir/cursor
args=(--show-cursor)
filter=("$@")

if [ -s "$statefile" ]; then
	cursor=$(< "$statefile")
	args+=(--after-cursor="$cursor")
else
	mkdir -p "$statedir"
	args+=(--boot --lines=100)
fi

journalctl "${args[@]}" "${filter[@]}" | {
	while read -r line; do
		if [[ "$line" == "$CURSOR_TAG"* ]]; then
			cursor=${line#"$CURSOR_TAG"}
		fi
		if [[ "$line" == "--"* ]]; then
			printf "%s\n" "$line" >&2
		else
			printf "%s\n" "$line"
		fi
	done
	printf "%s" "$cursor" > "$statefile"
}
