#!/usr/bin/env bash

. lib.bash || exit

grep_hwdb() {
	systemd-hwdb query "$1" | sed -n "s/^$2=//p"
}

grep_nmap() {
	sed -n "/^${1:0:6} /{s///;p;q}" "$NMAP_MAC_DB"
}

NMAP_MAC_DB="/usr/share/nmap/nmap-mac-prefixes"

B=$'\e[1m'
I=$'\e[3m'
U=$'\e[4m'
R=$'\e[m'

arg_mode=

case ${0##*/} in
	oui)	mode=oui;;
esac

while getopts "m" OPT; do
	case $OPT in
	m) mode=oui;;
	esac
done; shift $((OPTIND-1))

mac_re='^[0-9A-Fa-f]{12}$|^([0-9A-Fa-f]{1,2}[:-]){5}[0-9A-Fa-f]{1,2}$'

if [[ ! $mode && $1 =~ $mac_re ]]; then
	mode=oui
fi

case $mode in
	oui)
		arg=$1
		arg=${arg//[:-]}
		arg=${arg^^}
		echo "query: $arg (MAC address)"
		local=$(( 0x${arg:0:2} & 0x2 ))
		multicast=$(( 0x${arg:0:2} & 0x1 ))
		if (( multicast )); then
			echo "kind: multicast"
		elif (( local )); then
			echo "kind: locally administered"
		else
			echo "kind: globally unique"
		fi
		if have systemd-hwdb; then
			v=$(grep_hwdb "OUI:$arg" ID_OUI_FROM_DATABASE)
			echo "vendor: ${B}${v:--}${R} (from hwdb)"
		fi
		if [ -s "$NMAP_MAC_DB" ]; then
			v=$(grep_nmap "$arg")
			echo "vendor: ${B}${v:--}${R} (from nmap)"
		fi
		;;
	*)
		die "mode not specified"
		;;
esac
