#!/usr/bin/env bash
# copies given files to the Dropbox public area and shows upload status

anims=("   " ".  " ".. " "..." " .." "  .")
nanim=${#anims[@]}

fill=$(printf '%*s' ${#anims} "" | sed 's/ /./g')

cursor_show() { printf '\e[?25h'; }
cursor_hide() { printf '\e[?25l'; }

trap 'cursor_show' EXIT

for file; do
	pubfile=~/Dropbox/Public/${file##*/}
	cp "$file" "$pubfile"
	puburl=$(dropbox puburl "$pubfile")
	echo "URL: $puburl"
	printf '[%s] status: ...' "${anims[anim=0]}"
	while sleep 1; do
		status=$(dropbox filestatus "$pubfile" || echo 'failed')
		status=${status#"$pubfile: "}
		status=${status,,}
		printf '\r[%s] status: %s' "${anims[++anim%nanim]}" "$status"
		if [ "$status" != "syncing" ]; then
			printf '\r[%s]\n' "$fill"
			break
		fi
	done
done
