#!/usr/bin/env perl
use warnings;
use strict;
use Sys::Hostname;

sub getfqdn {
	my $host = shift;
	my @ret = gethostbyname($host);
	$ret[0] // $host;
}

if (@ARGV) {
	print getfqdn($_)."\n" for @ARGV;
} else {
	print getfqdn(hostname)."\n";
}
