#!/usr/bin/env python
import sys
from ipaddress import *
from nullroute import Core

def nprint(k, *v):
    width = 12
    print("\033[33m%*s\033[m" % (width, k), *v)

def addr2props(addr):
    mapping = [
        ("is_loopback", "loopback"),
        ("is_link_local", "link-local"),
        ("is_site_local", "site-local"),
        ("is_global", "global"),
        ("is_private", "private"),
        ("is_multicast", "multicast"),
        ("is_reserved", "reserved"),
        ("teredo", "Teredo"),
        ("sixtofour", "6to4"),
    ]
    props = []
    for prop, name in mapping:
        if getattr(addr, prop, False):
            props.append(name)
    return props

def show_addr(addr):
    nprint("address", addr)
    if addr.version == 6:
        nprint("->", addr.exploded)
    props = addr2props(addr)
    if props:
        nprint("properties", ", ".join(props))
    if addr.version == 6 and addr.teredo:
        relay, v4addr = addr.teredo
        nprint("relay", relay)
        nprint("v4 address", v4addr)
    if addr.version == 6 and addr.sixtofour:
        nprint("v4 address", addr.sixtofour)

def show_net(net):
    nprint("network", net)
    if addr.version == 4:
        nprint("netmask", net.netmask, "(%d addresses)" % net.num_addresses)
    else:
        nprint("netmask", net.netmask.exploded)
    nprint("first addr", net.network_address.exploded)
    nprint("last addr", net.broadcast_address.exploded)
    next_net = ip_network("%s/%s" % (net.broadcast_address + 1, net.prefixlen))
    nprint("next net", next_net)

try:
    arg = sys.argv[1]
    if arg.startswith("/"):
        plen = int(arg[1:])
        if plen < 0:
            Core.die("prefix length must be positive")
        elif plen > 128:
            Core.die("prefix length too large for any family")

        nprint("prefix", "/%d" % plen)
        if plen <= 32:
            net = ip_network("0.0.0.0/%d" % plen)
            nprint("v4 netmask", net.netmask, "(%d addresses)" % net.num_addresses)
        net = ip_network("::/%d" % plen)
        nprint("v6 netmask", net.netmask.exploded)
    elif "/" in arg:
        addr = ip_interface(arg)
        show_addr(addr)
        print()
        show_net(addr.network)
    else:
        addr = ip_address(arg)
        if addr.version == 4 and addr._is_valid_netmask(arg):
            net = ip_network("0.0.0.0/%s" % arg)
            nprint("netmask", net.netmask)
            nprint("prefix", "/%d" % net.prefixlen)
            nprint("size", net.num_addresses)
        else:
            show_addr(addr)
except IndexError:
    Core.die("not enough arguments")
except ValueError as e:
    Core.die(str(e))
