#!/usr/bin/env python
# ip-subnet - print subnets of a network for given prefix length
import sys
from ipaddress import *
from nullroute import Core

def usage():
    print("Usage: %s <ip_network> /<prefix>" % Core.arg0)
    print("       %s <ip_network> +<increment>" % Core.arg0)

try:
    network = ip_network(sys.argv[1])
    if sys.argv[2].startswith("/"):
        submask = int(sys.argv[2][1:])
        increment = submask - network.prefixlen
    elif sys.argv[2].startswith("+"):
        increment = int(sys.argv[2][1:])
    else:
        Core.die("submask should be /x or +x")

    subnets = network.subnets(increment)
    for net in subnets:
        print(net)
except IndexError:
    Core.die("not enough arguments")
except ValueError as e:
    Core.die(e)
