#!/usr/bin/env python3
# ip-summarize - print summarized CIDR masks for a given IP address range
import sys
from ipaddress import *
from nullroute.core import *

def usage():
    print("Usage: %s <first_addr> <last_addr>" % Core.arg0)

try:
    first_addr = ip_address(sys.argv[1])
    last_addr  = ip_address(sys.argv[2])

    masks = summarize_address_range(first_addr, last_addr)
    for net in masks:
        print(net)
except IndexError:
    usage()
    Core.die("not enough arguments")
except ValueError as e:
    Core.die(e)
