#!/usr/bin/env bash
# mc-presence - tool to control status of all Telepathy accounts with a single command.

. lib.bash || exit

usage() {
	echo "Usage: $progname <command> [...]"
	echo ""
	echo "  $progname available [message]"
	echo "  $progname busy [message]"
	echo "  $progname away [message]"
	echo "  $progname xa [message]"
	echo "  $progname offline [message]"
	echo "  $progname auto"
	echo "  $progname dump [> file]"
	echo "  $progname load [< file]"
}

case $1 in
    available|busy|away|xa|offline)
	mc-tool list |
	while read -r acct; do
		mc-tool request "$acct" "$1" "$2"
	done
	;;
    auto)
	mc-tool list |
	while read -r acct; do
		st=$(mc-tool show "$acct" |
			awk '$1 == "Automatic:" {print $2}')
		mc-tool request "$acct" "$st"
	done
	;;
    dump)
	mc-tool list |
	while read -r acct; do
		curr=$(mc-tool show "$acct" |
			awk '$1 == "Current:" {print $2}')
		echo "$acct $curr"
	done
	;;
    dump-auto)
	mc-tool list |
	while read -r acct; do
		st=$(mc-tool show "$acct" |
			awk '$1 == "Automatic:" {print $2}')
		echo "$acct $st"
	done
	;;
    load)
	while read -r acct st; do
		mc-tool request "$acct" "$st"
	done
	;;
    a)
	exec "$0" "available" "${@:2}"
	;;
    b)
	exec "$0" "busy" "${@:2}"
	;;
    w)
	exec "$0" "away" "${@:2}"
	;;
    o)
	exec "$0" "offline" "${@:2}"
	;;
    ""|help|--help)
	usage
	;;
    *)
	die -2 "unknown command '$1'"
	;;
esac
