#!/bin/bash
# Tool to control status of all Telepathy accounts with a single command.

case $1 in
	""|help|--help)
		app=${0##*/}
		echo "Usage:"
		echo ""
		echo "  $app available [message]"
		echo "  $app busy [message]"
		echo "  $app away [message]"
		echo "  $app xa [message]"
		echo "  $app offline [message]"
		echo "  $app auto"
		echo "  $app dump > state"
		echo "  $app load < state"
		echo ""
		;;
	available|busy|away|xa|offline)
		mc-tool list |
		while read -r acct; do
			mc-tool request "$acct" "$1" "$2"
		done
		;;
	auto)
		mc-tool list |
		while read -r acct; do
			st=$(mc-tool show "$acct" |
				awk '$1 == "Automatic:" {print $2}')
			mc-tool request "$acct" "$st"
		done
		;;
	dump)
		mc-tool list |
		while read -r acct; do
			curr=$(mc-tool show "$acct" |
				awk '$1 == "Current:" {print $2}')
			echo "$acct $curr"
		done
		;;
	dump-auto)
		mc-tool list |
		while read -r acct; do
			st=$(mc-tool show "$acct" |
				awk '$1 == "Automatic:" {print $2}')
			echo "$acct $st"
		done
		;;
	load)
		while read -r acct st; do
			mc-tool request "$acct" "$st"
		done
		;;
	*)
		echo "Invalid command '$1'" >&2
		exit 2
esac
