#!/usr/bin/env python
from collections import namedtuple
import fdb
from hashlib import md5
from nullroute.core import *
import nullroute.sec
import sys

class MyQDatabase(object):
    User = namedtuple("User", ["id", "name", "fullname", "email", "card"])

    def __init__(self, host):
        self.host = host
        creds = nullroute.sec.get_netrc_service(self.host, "fdb")
        Core.debug("connecting to %r as %r", self.host, creds["login"])
        self.conn = fdb.connect(host=self.host, database="myq",
                                user=creds["login"], password=creds["password"])

    def find_user(self, arg):
        Core.debug("searching for %r", arg)
        qry = """
        SELECT e.id, e.name, u.fullname, u.email, c.card_id
            FROM tblEntities e
            JOIN tblUsers u ON u.id=e.id
            JOIN tblCard c ON c.user_id=e.id
            WHERE LOWER(name) = ?
        UNION DISTINCT
        SELECT e.id, e.name, u.fullname, u.email, c.card_id
            FROM tblEntities e
            JOIN tblUsers u ON u.id=e.id
            JOIN tblCard c ON c.user_id=e.id
            WHERE LOWER(email) = ?
        UNION DISTINCT
        SELECT e.id, e.name, u.fullname, u.email, c.card_id
            FROM tblEntities e
            JOIN tblUsers u ON u.id=e.id
            JOIN tblCard c ON c.user_id=e.id
            WHERE u.id = (SELECT FIRST 1 user_id FROM tblAliases a WHERE LOWER(alias) = ?)
        """
        cur = self.conn.cursor()
        cur.execute(qry, (arg.lower(),)*3)
        for row in cur:
            yield self.User(*row)

def crack_md5(arg, digits=4):
    arg = arg.lower()
    for i in range(10 ** digits):
        pin = "%0*d" % (digits, i)
        hash = md5(pin.encode()).hexdigest()
        if hash == arg:
            return pin
    return None

def crack_pin(arg):
    Core.debug("cracking hash %r", arg)
    for digits in [4, 5, 6]:
        result = crack_md5(arg, digits)
        if result:
            break
    return result

host = "aqrate.utenos-kolegija.lt"
db = None
args = sys.argv[1:]

for arg in args:
    if len(arg) == 32:
        pin = crack_pin(arg)
        print("%s = %s" % (arg, pin or "not found"))
    else:
        if not db:
            db = MyQDatabase(host)
        for row in db.find_user(arg):
            Core.debug("found row %r", row)
            pin = crack_pin(row.card)
            print("%s (%s) = %s" % (row.fullname, row.email, pin or "not found"))
