#!/usr/bin/env bash
# rdo -- run command across all hosts

. lib.bash || exit

usage() {
	echo "Usage: $progname [-H HOSTS] [-S] <command>"
	echo
	echo "Run a command simultaneously on all hosts."
	echo
	echo_opt "-H HOSTS"	"list of hosts to connect to"
	echo_opt "-S"		"connect as superuser (root)"
}

hosts=
user=
wait=0

while getopts ":H:SW" OPT; do
	case $OPT in
	H) hosts=${OPTARG//,/ };;
	S) user="root@";;
	W) wait=1;;
	*) lib::die_getopts;;
	esac
done; shift $((OPTIND-1))

hosts=$(rlisthosts "$hosts") || exit

if (( ! $# )); then
	die "command not specified"
elif (( $# == 1 )); then
	cmd=$1
else
	cmd=${*@Q}
fi

# Make sure to show return code on failure. (XXX: This could probably also be
# done locally, as ssh propagates the exit status.)
cmd="(${cmd:-:}) 2>&1 || echo '=> '\$?"

for host in $hosts; do
	(
		out=$(mktemp /tmp/rdo.XXXXXXXX) || exit
		echo -n "$host:" > "$out"
		ssh -n $user$host "$cmd" |
			awk '{print "\t"$0} END {if (!NR) print}' >> "$out"
		flock /dev/stdout cat "$out"
		rm -f "$out"
	) &
	if (( wait )); then wait; fi
done
wait
