#!/usr/bin/env perl
use strict;
use LWP::UserAgent;

my $ua = LWP::UserAgent->new;

sub get_raw_url {
	my ($id) = @_;

	if ($id =~ m|^(http://article\.gmane\.org/.+?/\d+)|) {
		return "$1/raw";
	} elsif ($id =~ m|^http://permalink\.gmane\.org/(.+)$|) {
		return "http://article.gmane.org/$1/raw";
	} else {
		my $id_res = $ua->head("http://mid.gmane.org/$id");
		my $art_url = $id_res->request->uri_canonical;
		return "$art_url/raw";
	}
}

sub fetch_raw {
	my ($mid) = @_;

	my $raw_url = get_raw_url($mid);
	my $raw_res = $ua->get($raw_url);
	return $raw_res->decoded_content;
}

for my $mid (@ARGV) {
	my $raw = fetch_raw($mid);
	print "From dummy\@dummy Thu Jan  1 03:00:00 1970\n";
	print $raw, "\n";
}
