#!/usr/bin/env python2
# scrape-reddit-comment - scraper for Reddit comments

from __future__ import print_function
import os
import sys
import urllib2
from BeautifulSoup import BeautifulSoup
import time
import datetime
import json
import re

rx_time = re.compile(r'(\d+)-(\d+)-(\d+)T(\d+):(\d+):(\d+)(?:\.(\d+))?([+-]\d+:\d+)')

rx_msgid = re.compile(r'.*/comments/(\w+)/.*/(\w+)/?$')

DELTA_ZERO = datetime.timedelta(0)

class FixedOffset(datetime.tzinfo):
    def __init__(self, stroffset):
        self._name = stroffset
        self._offset = datetime.timedelta(hours=int(stroffset[:3]),
                                          minutes=int(stroffset[4:6]))

    def utcoffset(self, dt):
        return self._offset

    def tzname(self, dt):
        return self._name

    def dst(self, dt):
        return DELTA_ZERO

def scrape(url):
    url += ".json"
    req = urllib2.Request(url + "?limit=1", headers={"User-Agent": "Mozilla/5.0"})
    page = urllib2.urlopen(req).read()
    data = json.loads(page)
    post = data[0]["data"]["children"][0]["data"]

    title = post["title"]
    author = post["author"]
    url = post["url"]
    date = datetime.datetime.fromtimestamp(post["created_utc"])

    import HTMLParser

    text = post["selftext_html"]
    text = HTMLParser.HTMLParser().unescape(text)
    text = BeautifulSoup(text, convertEntities=BeautifulSoup.HTML_ENTITIES)
    txtbody = text.find("div", {"class": "md"})
    if txtbody:
        text = txtbody.renderContents().strip()


    yield  {"url": url,
            "subject": title,
            "author": author,
            "date": date,
            "text": text}

TIMEFMT_MBOX = "%a %b %_d %H:%M:%S %Y"
TIMEFMT_MIME = "%a, %d %b %Y %H:%M:%S %z"

for url in sys.argv[1:]:
    for comment in scrape(url):
        mboxdate = comment["date"].strftime(TIMEFMT_MBOX)
        mimedate = comment["date"].strftime(TIMEFMT_MIME)

        msgid = "%s.%s@reddit" % (comment["author"],
                    comment["date"].isoformat())
        author = "%s@reddit" % comment["author"]
        length = len(comment["text"]) + 1

        print("From %s %s" % (author, mboxdate))
        print("URL: %s" % comment["url"])
        print("Message-ID: <%s>" % msgid)
        print("From: <%s>" % author)
        print("Date: %s (%s)" % (mimedate, comment["date"].isoformat()))
        print("Subject: %s" % comment["subject"])
        #print("Content-Type: text/plain; charset=utf-8")
        print("Content-Type: text/html; charset=utf-8")
        print("Content-Length: %d" % length)
        print("")
        print(comment["text"])
        print("")
        sys.stdout.flush()
