#!/usr/bin/env perl
use strict;
use LWP::UserAgent;

my $ua = LWP::UserAgent->new;

sub get_raw_url {
	my ($id) = @_;

	if ($id =~ m|^http://article\.olduse\.net/.+?$|) {
		return "$id/raw";
	} else {
		return "http://article.olduse.net/$id/raw";
	}
}

sub fetch_raw {
	my ($mid) = @_;

	my $raw_url = get_raw_url($mid);
	my $raw_res = $ua->get($raw_url);
	return $raw_res->decoded_content;
}

for my $mid (@ARGV) {
	my $msg = join "\n",
		grep {!/^Xref: dummy/i}
		split /\n/, fetch_raw($mid);
	if ($msg !~ /\n$/) {
		$msg .= "\n";
	}
	print $msg;
}
