#!/usr/bin/env bash
# Simple sprunge.us pastebin client

. lib.bash || exit
. libks.bash || exit

now() {
	printf "%(%Y%m%d.%H%M%S)T"
}

seturl() {
	local file=$1 url=$2
	ks:setattr "$file" xdg.origin.url "$url"
	ln -s -f "${file##*/}" "${file%/*}/${url##*/}.txt"
}

getsel() {
	if have xclip; then
		xclip -out -selection primary
	elif have xsel; then
		xsel -o -p
	else
		err "no xclip nor xsel"
	fi
}

putclip() {
	if [ "$DISPLAY" ]; then
		if have xclip; then
			echo "$1" | xclip -in -selection clipboard
		elif have xsel; then
			echo "$1" | xsel -i -b
		fi
	fi
	putclip() { true; }
}

post() {
	local file=$1
	echo -n "$file → "
	local url=$(curl -sF "sprunge=<$file" http://sprunge.us/)
	if [ "$url" ]; then
		seturl "$file" $url
		echo $url
		putclip $url
	else
		err "upload failed"
	fi
}

cache=${XDG_CACHE_HOME:-$HOME/.cache}/sprunge

err=0
umask 077

if [ ! "$1" ] || [ "$*" = "-" ]; then
	# curl handles stdin buffering in a funny way, often
	# resulting in only the first write() to be pastebinned
	if [ -d "$cache" ]; then
		file="$cache/$(now).txt"
	else
		file=`mktemp /tmp/sprunge.XXXXXXXX`
	fi

	if [ ! "$1" ] && [ -t 0 ] && [ "$DISPLAY" ]; then
		getsel > "$file"
	else
		: > "$file"
	fi

	if [ ! -s "$file" ]; then
		if [ -t 0 ]; then
			printf "\e[1mInput text to pastebin:\e[m\n"
		fi
		cat > "$file"
		if [ -t 0 ]; then
			printf "\e[1mEOF\e[m\n"
		fi
	fi

	if [ -s "$file" ]; then
		post "$file"
		if [ ! -d "$cache" ]; then
			rm -f "$file"
		fi
	else
		err "stdin: empty"
		rm -f "$file"
	fi
else
	for file; do
		if [ ! -f "$file" ]; then
			err "$file: not a file"
		elif [ -s "$file" ]; then
			post "$file"
		elif [ -e "$file" ]; then
			err "$file: empty"
		else
			err "$file: not found"
		fi
	done
fi

lib::exit
