#!/usr/bin/env bash
# helper script for youtube-dl

options=(
	--console-title
	--continue
	--write-description
	#--write-info-json
	)
urls=()

for arg; do
	case $arg in
	http://*|https://*)
		urls+=("$arg");;
	*)
		options+=("$arg");;
	esac
done

re_youtube_full='^https?://www.youtube.com/watch.*[?&]v=([A-Za-z0-9_-]+)(&|$)'
re_youtube_short='^https?://youtu.be/([A-Za-z0-9_-]+)(\?|$)'

for url in "${urls[@]}"; do
	if [[ $url =~ $re_youtube_full ]]; then
		url="http://www.youtube.com/watch?v=${BASH_REMATCH[1]}"
	elif [[ $url =~ $re_youtube_short ]]; then
		url="http://www.youtube.com/watch?v=${BASH_REMATCH[1]}"
	fi
	echo "url: $url"

	file=$(youtube-dl -o "%(title)s.%(ext)s" --get-filename "$url")
	f_name=${file%.*}
	f_ext=${file##*.}
	if read -e -p "name: " -i "$f_name" f_name && [[ $f_name ]]; then
		file=$f_name.$f_ext
	fi
	descr="$file.description"

	youtube-dl "${options[@]}" "$url" -o "${file//%/%%}"
	test -s "$file" || continue

	case $file in
	*.flv)
		temp=$file; file=${file%.*}.mp4
		ffmpeg -i "$temp" -acodec copy -vcodec copy "$file" \
			&& rm -f "$temp"
		;;
	esac

	mp4tags -xid "youtube:$url" "$file"
	if [[ -s "$descr" ]]; then
		mp4tags -longdesc "$(< "$descr")" "$file"
	fi
	rm -f "$descr"
done
