#!/usr/bin/env python
import os, sys, re
import urllib.parse

def trace(fmt, *args):
    if "DEBUG" in os.environ:
        print("\033[36m%s\033[m" % fmt, *args, file=sys.stderr)

def load_mappings(path):
    mappings = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if (not line) or line.startswith("#"):
                continue
            line = line.split()
            line[0] = re.compile("^%s$" % line[0])
            mappings.append(line)
    return mappings

def find_mapping(mappings, uri):
    #print("looking up %r" % uri)
    for regex, replace, *rest in mappings:
        #print("considering %r / %r" % (regex, replace))
        flags = ""
        if rest:
            flags = rest.pop(0)
        m = regex.match(uri)
        if m:
            if replace != "$0":
                yield subst(replace, m)
            if not ("+" in flags):
                return

def subst(template, match):
    state = 0
    out = ""
    buf = fbuf = ""
    for char in template:
        if state == 0:
            if char == "$":
                state = 1
            elif char == "\\":
                state = 3
            else:
                out += char
        elif state == 1:
            if char in "0123456789":
                try:
                    out += match.group(int(char))
                except IndexError:
                    pass
                state = 0
            elif char == "&":
                out += match.group(0)
                state = 0
            elif char == "{":
                buf = fbuf = ""
                state = 2
            else:
                out += "$" + char
                state = 0
        elif state == 2:
            if char in "0123456789" and not fbuf:
                buf += char
            elif char == "}":
                try:
                    r = match.group(int(buf))
                    if "/" in fbuf:
                        r = r.replace(":", "/")
                    if "%" in fbuf:
                        r = urllib.parse.quote(r)
                    out += r
                except IndexError:
                    pass
                state = 0
            elif char in "%/" and buf:
                fbuf += char
            else:
                out += "${" + buf + char
                state = 0
        elif state == 3:
            out += char
            state = 0
    return out

conf_path = os.path.expanduser("~/lib/uri")
mappings = load_mappings(conf_path)
seen = set()

for start_uri in sys.argv[1:]:
    trace("start arg: %r" % start_uri)
    inputs = [start_uri]
    found = 0
    while inputs:
        trace("- have inputs: %r" % inputs)
        next = []
        for uri in inputs:
            trace("- trying to map %r" % uri)
            if uri in seen:
                trace("... already seen, skipping")
                continue
            mapped = list(find_mapping(mappings, uri))
            trace("... output %r" % mapped)
            if mapped:
                trace("... mapping found, adding to next-inputs")
                next += mapped
            else:
                trace("... no mapping, uri is final")
                found += 1
                print(uri)
            seen.add(uri)
        if len(seen) > 100:
            raise Exception("possible infinite loop at %r" % start_uri)
        inputs = next
    trace("- no more inputs")
    if found == 0:
        trace("... no mappings ever found, returning original arg")
        print(start_uri)
