#!/usr/bin/env bash
# whois4, whois6 -- make Whois queries for a domain's IP addresses

. lib.bash || exit

case ${0##*/} in
	whois4) af='-4' afname='IPv4';;
	whois6) af='-6' afname='IPv6';;
	*) af='' afname='IP';;
esac

name=$1

addr=$(name2addr $af "$name")

[[ $addr ]] || die "name '$name' has no $afname address"

info "looking up $addr"

whois "$addr"
