#!/usr/bin/env python3
# show-file -- reveal specified items in a file manager window
import argparse
import dbus
import os
import urllib.parse

def path2url(path):
    path = os.path.abspath(path)
    return "file://" + urllib.parse.quote(path)

parser = argparse.ArgumentParser()
parser.add_argument("path", nargs="+")
args = parser.parse_args()

for f in args.path:
    if not os.path.exists(f):
        exit("error: Path %r does not exist" % f)

urls = [path2url(p) for p in args.path]

bus = dbus.SessionBus()
fm = dbus.Interface(bus.get_object("org.freedesktop.FileManager1",
                                   "/org/freedesktop/FileManager1"),
                    "org.freedesktop.FileManager1")
fm.ShowItems(urls, "")
