#!/usr/bin/env python3
# show-fm - Reveal specified items in a file manager window
import dbus
import os
import sys
import urllib.parse

def path2url(path):
    path = os.path.abspath(path)
    return "file://" + urllib.parse.quote(path)

files = sys.argv[1:]

if not files:
    exit("Usage: %s PATH..." % sys.argv[0])

for f in files:
    if not os.path.exists(f):
        exit("error: Path %r does not exist" % f)

urls = [path2url(p) for p in files]

bus = dbus.SessionBus()
fm = dbus.Interface(bus.get_object("org.freedesktop.FileManager1",
                                   "/org/freedesktop/FileManager1"),
                    "org.freedesktop.FileManager1")
fm.ShowItems(urls, "")
