#!/bin/sh

if ! vt="vt$(fgconsole)"; then
	echo "error: could not determine current VT"
	exit 1
fi

unset DBUS_SESSION_BUS_ADDRESS
unset SHLVL
export DISPLAY=$(next-display)
export XAUTHORITY=~/.Xauthority
if [ ! "$DISPLAY" ]; then
	echo "error: could not find a free display"
	exit 1
fi

XINITRC=${XDG_CONFIG_HOME:-~/.config}/xinitrc
if [ ! -e "$xintirc" ]; then
	XINITRC=~/.xinitrc
fi

cd ~
xauth remove "$HOSTNAME$DISPLAY"
xauth remove "$DISPLAY"
xauth add "$DISPLAY" MIT-MAGIC-COOKIE-1 $(mcookie)

echo "Starting Xorg on display $DISPLAY"
xinit "$XINITRC" "$@" -- "$DISPLAY" "$vt" \
	-noreset \
	-auth "$XAUTHORITY" \
	-quiet \
	-background none \
	< /dev/null; r=$?

xauth remove "$DISPLAY"
exit $r
