#!/bin/sh

if ! vt="vt$(fgconsole)"; then
	echo "error: could not determine current VT"
	exit 1
fi

: ${XDG_CONFIG_HOME:=~/.config}
if [ -e "$XDG_CONFIG_HOME/xinitrc" ]; then
	xinitrc=$XDG_CONFIG_HOME/xinitrc
else
	xinitrc=~/.xinitrc
fi

export DISPLAY=$(next-display)
export XAUTHORITY=~/.Xauthority
if [ ! "$DISPLAY" ]; then
	echo "error: could not find a free display"
	exit 1
fi

cd ~
xauth remove "$HOSTNAME$DISPLAY"
xauth remove "$DISPLAY"
xauth add "$DISPLAY" MIT-MAGIC-COOKIE-1 $(mcookie)

echo "Starting Xorg on display $DISPLAY"
xinit "$xinitrc" "$@" -- "$DISPLAY" "$vt" \
	-noreset \
	-auth "$XAUTHORITY" \
	-quiet \
	-background none \
	< /dev/null; r=$?

xauth remove "$DISPLAY"
exit $r
