#!/bin/bash
# Monitor the progress of tracker-extract-3

if [ "$1" = "-m" ]; then
	proc='tracker-miner-fs-3'
else
	proc='tracker-extract-3'
fi

pids=(`pidof $proc`) || {
	echo "$proc is not running" >&2
	exit 1
}

#if (( ${#pids[@]} > 1 )); then

sudo stdbuf -oL -- strace -p ${pids[0]} -e statx |&
	perl -nE 'chomp;
		($err) = /= -\d+ (E\w+) \(.+?\)$/;
		$col = $err ? 91 : 93;
		if(s/.*AT_FDCWD, "(.+?)", AT_STATX.*/$1/) {
			s/\\(\d{3})/chr oct $1/ge;
			s!^(.+/)([^/]+)$!\033[${col}m$2\033[m \033[2m($1$2)\033[m!;
			say;
		}'
